Repository HippieStation/HippieStation, pull requests merged in 2018-03, with the labels that each got.

#6859 Adds Carbonhell's Cheap Cuisine to vendors near you!
  hippiestation.dme
  hippiestation/code/game/machinery/vending.dm
  hippiestation/code/game/objects/items/cheapcuisine.dm
  hippiestation/icons/obj/food/food.dmi
  hippiestation/icons/obj/items_and_weapons.dmi
Labels: Feature, Fix

#6830 Fixes war op pop limit.
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
Labels: Fix

#6863 Bomb suit buffs + integrated doppler array
  code/game/machinery/doppler_array.dm
  hippiestation.dme
  hippiestation/code/modules/clothing/suits/utility.dm
Labels: Balance/Rebalance, Feature

#6925 Fixed and modularised butt code
  code/modules/mob/living/carbon/human/species.dm
  hippiestation.dme
  hippiestation/code/game/objects/items/storage/butts.dm
  hippiestation/code/modules/clothing/clothing.dm
  hippiestation/code/modules/mob/living/carbon/human/human_defense.dm
  hippiestation/code/modules/mob/living/carbon/human/species.dm
Labels: Fix, Priority: CRITICAL

#6979 Hippiestation map update
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Box Map Changes, Feature, Fix, Map Edit, tg saves us

#6991 Map Fixes created by pyko1 :)
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Fix, Map Edit

#6994 Fixes vault wires + tiny fans around external airlock + chemistry shu…
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Fix, Map Edit

#6971 Buffs the Energy Balisong's backstab damage.
  hippiestation/code/game/objects/items/butterfly_knives.dm
  hippiestation/code/modules/uplink/uplink_item.dm
Labels: Balance/Rebalance

#6972 Lowers Syndicate Banhammer price to 6 TC and removes its Nuke Ops exclusion
  hippiestation/code/game/objects/items/weaponry.dm
  hippiestation/code/modules/uplink/uplink_item.dm
Labels: Balance/Rebalance

#6250 Dufflebag = toggable weight
  hippiestation/code/game/objects/items/storage/backpack.dm
Labels: Controversial, Old Hippiestation Port, Ready for Review, Tweak

#6825 Adds 2 new cloaks and adds new function for them
  hippiestation.dme
  hippiestation/code/game/objects/items/storage/internal.dm
  hippiestation/code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  hippiestation/code/modules/clothing/suits/cloaks.dm
  hippiestation/icons/mob/cloaks.dmi
  hippiestation/icons/obj/clothing/back.dmi
Labels: Balance/Rebalance, Feature, Ready for Review, Sprites, Tweak

#7044 Adds mining mech + TG Windows,vents,scrubbers have been fully added.
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Feature, Fix, Map Edit, Tweak

#7092 Fix mentors
  code/modules/client/client_procs.dm
  hippiestation.dme
  hippiestation/code/modules/client/client_procs.dm
  hippiestation/code/modules/mentor/mentor.dm
  hippiestation/code/modules/mentor/mentorpm.dm
Labels: Fix, Work In Progress

#7078 Little map additions and fixes.
  _maps/map_files/HippieStation/hippiestation.dmm
  hippiestation/icons/obj/doors/hazarddoor.dmi
Labels: Feature, Fix, Map Edit, Ready for Review

#7077 Greyscales pool water
  hippiestation/code/modules/pool/pool_controller.dm
  hippiestation/code/modules/pool/pool_main.dm
  hippiestation/icons/turf/pool.dmi
Labels: Code Improvement, Feature

#7105 removes all traits, sets up the hippie specific files for writing our own
  hippiestation.dme
  hippiestation/code/__DEFINES/traits.dm
  hippiestation/code/datums/traits/good.dm
  hippiestation/code/datums/traits/negative.dm
  hippiestation/code/datums/traits/neutral.dm
Labels: Revert/Removal

#7083 Adds a Spurdo Sparde mask to Loadout, featuring Pyko!
  hippiestation.dme
  hippiestation/code/modules/client/loadout/mask.dm
  hippiestation/code/modules/clothing/masks/spurdo.dm
  hippiestation/icons/mob/mask.dmi
  hippiestation/icons/obj/clothing/masks.dmi
  hippiestation/sound/voice/finnish_1.ogg
  hippiestation/sound/voice/finnish_2.ogg
  hippiestation/sound/voice/finnish_3.ogg
  strings/hippie_word_replacement.json
Labels: Feature

#6957 Adds Sopa de Macaco
  hippiestation.dme
  hippiestation/code/modules/food_and_drinks/food/snacks_soup.dm
  hippiestation/code/modules/food_and_drinks/recipes/tablecraft/recipes_soup.dm
Labels: +1, Feature, Needs Head Input

#7102 Removes tgui from pool controller
  hippiestation/code/modules/pool/pool_controller.dm
  tgui/src/interfaces/poolcontrol.ract
Labels: Revert/Removal, Tweak

#6857 Modularizes #5998
  code/game/machinery/vending.dm
  hippiestation/code/game/machinery/vending.dm
Labels: Fix

#7142 Adds Zootsuit, Elvis Jumpsuit, and Pimpstick
  hippiestation/code/game/machinery/vending.dm
  hippiestation/code/game/objects/items/weaponry.dm
  hippiestation/code/modules/clothing/under.dm
  hippiestation/icons/mob/inhands/lefthand.dmi
  hippiestation/icons/mob/inhands/righthand.dmi
  hippiestation/icons/mob/uniform.dmi
  hippiestation/icons/obj/clothing/uniforms.dmi
  hippiestation/icons/obj/items_and_weapons.dmi
Labels: Feature, Old Hippiestation Port, Ready for Review, Sprites

#7153 Get our Pubby updated to current TG
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit

#7145 Add guillotine to the game
  _maps/map_files/HippieStation/hippiestation.dmm
  hippiestation.dme
  hippiestation/code/game/objects/structures/guillotine.dm
  hippiestation/code/modules/mob/living/carbon/update_icons.dm
  hippiestation/code/modules/mob/living/emote.dm
  hippiestation/icons/obj/structures/guillotine.dmi
  hippiestation/sound/misc/clap1.ogg
  hippiestation/sound/misc/clap2.ogg
  hippiestation/sound/misc/clap3.ogg
  hippiestation/sound/misc/clap4.ogg
Labels: Feature, Map Edit, Ready for Review

#7155 Pixel x = 0 removal
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Code Improvement, Fix, Map Edit

#7166 Adds more IPC screens (and fixes them)
  code/__HELPERS/mobs.dm
  hippiestation/code/modules/mob/dead/new_player/sprite_accessories.dm
  hippiestation/icons/mob/mutant_bodyparts.dmi
Labels: Feature

#7189 Refartcors butts!
  hippiestation/code/modules/mob/living/carbon/human/emote.dm
Labels: Refactor

#6808 Flyswatter changes 2: Electric Boogaloo
  hippiestation/code/game/objects/items/weaponry.dm
Labels: Tweak

#7143 Added new roundend sound
  hippiestation.dme
  hippiestation/code/controllers/subsystem/ticker.dm
  hippiestation/sound/roundend/gameoverinsertfourcoinstoplayagain.ogg
Labels: Sound

#7258 Fixed being able to hang headless people
  hippiestation/code/game/objects/noose.dm
  hippiestation/code/modules/surgery/bodyparts/dismemberment.dm
Labels: Fix

#6985 Un-nerfs that shitty r&d nerf tg hamfisted in for better R&D parts.
  hippiestation.dme
  hippiestation/code/modules/techweb/all_nodes.dm
Labels: Balance/Rebalance, Needs Head Input

#7261 @johnginnane is a liar
  code/modules/research/machinery/_production.dm
Labels: Fix

#7109 [/tg/ Balancing] Unfucks the Spray Cleaner
  hippiestation.dme
  hippiestation/code/modules/reagents/reagent_containers/spray.dm
Labels: Balance/Rebalance, Ready for Review

#7259 [FIX] Openwire opens the door when pulsed
  code/datums/wires/airlock.dm
Labels: Fix, Old Hippiestation Port

#7203 Adds four new butt related traits.
  hippiestation/code/datums/traits/good.dm
  hippiestation/code/datums/traits/negative.dm
Labels: +1, +2, +3, Feature

#7257 Medbots dispense lollipops on successful medication
  code/modules/mob/living/simple_animal/bot/medbot.dm
  hippiestation.dme
  hippiestation/code/modules/mob/living/simple_animal/bot/medbot.dm
Labels: +1, +2, Feature, Ready for Review

#7244 Adds small chance of doom door sound effect to play when opening/closing an airlock
  hippiestation.dme
  hippiestation/code/game/machinery/doors/airlock.dm
  hippiestation/code/game/machinery/doors/poddoor.dm
  hippiestation/sound/machines/airlockclose_doom.ogg
  hippiestation/sound/machines/airlockopen_doom.ogg
  hippiestation/sound/machines/blast_door.ogg
  hippiestation/sound/machines/denied.ogg
Labels: +1, +2, Feature, Needs Head Input, Sound

#7339 Fixed our icons not loading
  hippiestation/code/game/atoms.dm
Labels: Fix, Priority: High

#7356 Modularised vending code
  hippiestation/README.md
  hippiestation/code/modules/vending/_vending.dm
  hippiestation/code/modules/vending/autodrobe.dm
  hippiestation/code/modules/vending/clothesmate.dm
  hippiestation/code/modules/vending/security.dm
  hippiestation/code/modules/vending/snack.dm
Labels: Code Improvement, Refactor
