Repository HippieStation/HippieStation, pull requests merged in 2018-10, with the labels that each got.

#9181 [Ready][Tested] New circuit: Wire connector
  hippiestation.dme
  hippiestation/code/modules/integrated_electronics/subtypes/power.dm
Labels: Feature, Needs Review

#9306 fixes clowns not being able to exit the roundstart clown car.
  hippiestation/code/modules/vehicles/clown_car.dm
Labels: Fix

#9294 Replaces the current Syndicate Elite Hardsuit sprite with our old one.
  hippiestation/code/modules/clothing/spacesuits/hardsuit.dm
  hippiestation/icons/mob/head.dmi
  hippiestation/icons/mob/suit.dmi
  hippiestation/icons/obj/clothing/hats.dmi
  hippiestation/icons/obj/clothing/suits.dmi
Labels: Sprites

#9311 i fucking hate AI vox
  code/__DEFINES/~hippie_defines/preferences.dm
  code/modules/mob/living/silicon/ai/say.dm
  hippiestation/code/modules/client/preferences_toggles.dm
  hippiestation/code/modules/mob/living/silicon/ai/vox_sounds.dm
Labels: Feature, Removal

#9088 [READY]Further nerfing atmos stuff
  hippiestation/code/modules/integrated_electronics/subtypes/atmospherics.dm
Labels: Needs Review

#9341 Get rid of retarded positioning of cult action buttons
  hippiestation.dme
  hippiestation/code/modules/antagonists/cult/blood_magic.dm
Labels: Tweak

#9435 Cigarettes no longer block you from seeing if someone is a thrall
  hippiestation/code/modules/mob/living/carbon/examine.dm
Labels: Tweak

#9068 [READY] Adds firetrucks
  hippiestation.dme
  hippiestation/code/modules/vehicles/firetruck.dm
  hippiestation/icons/mob/actions/actions_vehicle.dmi
  hippiestation/icons/obj/vehicles.dmi
Labels: Feature, Needs Review, PRE-APPROVED!!

#9436 Fixes humans not having thrall message
  code/modules/mob/living/carbon/human/examine.dm
Labels: Fix

#9486 Fix non-roundstart infiltrators not being able to use Agent IDs
  hippiestation/code/modules/antagonists/infiltrator/infiltrator.dm
Labels: Fix

#9502 Revert "Get rid of retarded positioning of cult action buttons"
  hippiestation.dme
  hippiestation/code/modules/antagonists/cult/blood_magic.dm
Labels: Revert

#9488 Fixes teg anchoring
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Fix, Map Edit

#9434 Add animation for admin heals
  hippiestation.dme
  hippiestation/code/modules/admin/verbs/randomverbs.dm
Labels: Feature

#9537 Compiles tgui and corrects fire alarm directions
  _maps/map_files/HippieStation/hippiestation.dmm
  tgui/assets/tgui.css
  tgui/assets/tgui.js
Labels: Fix, Map Edit, UI

#9538 Fixed tasers and projectiles not using new paralyze vars
  hippiestation/code/modules/projectiles/projectile/bullets.dm
  hippiestation/code/modules/projectiles/projectile/energy.dm
Labels: Fix

#9533 Raise ogg upload limit to 3mb
  code/modules/client/client_procs.dm
Labels: Administration

#9540 Flag and parent call cleanup for nanosuit.dm
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Code Improvement

#9551 Moves modularized stuff to paralyze
  hippiestation/code/_onclick/hud/stamina.dm
  hippiestation/code/datums/martial/cqc.dm
  hippiestation/code/datums/martial/krav_maga.dm
  hippiestation/code/datums/martial/plasma_fist.dm
  hippiestation/code/datums/martial/sleeping_carp.dm
  hippiestation/code/modules/antagonists/changeling/lesserform.dm
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
  hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
Labels: Code Improvement, Fix, Nice

#9555 [MIRROR] Fixes shuttle overlapping with centcom supplypod bays (READY TO MERGE)
  _maps/map_files/generic/CentCom.dmm
Labels: FUCK, Fix

#9586 fixes failure setting up secret
  code/game/gamemodes/cult/cult.dm
Labels: Fix

#9587 Re-removes war op pop limit
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
Labels: Removal

#9588 fixes nuke ops causing secret to fail
  code/game/gamemodes/nuclear/nuclear.dm
Labels: Fix

#9598 Fix holotool radial menus
  hippiestation/code/game/objects/items/holotool/holotool.dm
Labels: Fix
