Repository HippieStation/HippieStation, pull requests merged in 2018-06, with the labels that each got.

#7621 Final map fixes
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: good... good...

#7616 Fixed a BUNCH of runtimes
  code/controllers/subsystem/lighting.dm
  code/game/objects/items/extinguisher.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  hippiestation.dme
  hippiestation/code/datums/components/storage/concrete/butt.dm
  hippiestation/code/datums/traits/good.dm
  hippiestation/code/datums/traits/negative.dm
  hippiestation/code/datums/traits/neutral.dm
  hippiestation/code/modules/food_and_drinks/drinks/drinks.dm
  hippiestation/code/modules/mob/living/carbon/carbon.dm
  hippiestation/code/modules/reagents/chemistry/holder.dm
  hippiestation/code/modules/reagents/chemistry/reagents.dm
  hippiestation/code/modules/reagents/chemistry/recipes/other.dm
  hippiestation/code/modules/reagents/chemistry/recipes/others.dm
  hippiestation/code/modules/surgery/organs/butts.dm
  hippiestation/code/modules/surgery/organs/tongue.dm
Labels: 80 year old man eating 10 bags of Cheetos., Candidate for Testmerge, FUCK, Fix, HHHHOLY FUCK IM GOING TO ACTUALLY DIE, MADMAN GOES WILD ON PERFORMANCE, Priority: CRITICAL, Ready for Review, Tested/Reproduced

#7630 Fixes a ton of performance sucking runtimes
  code/controllers/subsystem/lighting.dm
  code/datums/beam.dm
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/objects/effects/effect_system/effect_system.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/obj_defense.dm
  code/modules/atmospherics/machinery/portable/portable_atmospherics.dm
  code/modules/atmospherics/machinery/portable/pump.dm
  code/modules/awaymissions/capture_the_flag.dm
  code/modules/awaymissions/mission_code/challenge.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/monkey/monkey_defense.dm
  code/modules/power/tesla/energy_ball.dm
  hippiestation/code/modules/reagents/chemistry/reagents.dm
Labels: Fix, MADMAN GOES WILD ON PERFORMANCE, Tweak, good... good...

#7631 Tiny map fixes
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Fix, Map Edit, Ready for Review, good... good...

#7609 Some more virology fixes
  code/__DEFINES/diseases.dm
  hippiestation/code/datums/diseases/advance/symptoms/heal.dm
Labels: Fix, Old Hippiestation Port

#7573 Made it possible to damage lawset boards by jamming a screwdriver into them
  hippiestation.dme
  hippiestation/code/game/objects/items/Ai_modules.dm
Labels: +1, Feature, Needs Head Input

#7662 Added a server restart vote and an emergency shuttle call vote - also some vote tweaks
  code/controllers/subsystem/vote.dm
  hippiestation.dme
  hippiestation/code/controllers/configuration/entries/general.dm
  hippiestation/code/controllers/subsystem/vote.dm
Labels: +2, Cautious +1, Feature, Needs Head Input, Ready for Review, Test Merge Candidate, Tweak

#7620 Buffs and fixes the nanosuit punch slightly + howto guide
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Fix, Ready for Review

#7667 added bone sword/scimitar merge
  hippiestation/code/game/objects/items/weaponry.dm
  hippiestation/code/modules/crafting/recipies.dm
  hippiestation/icons/mob/inhands/lefthand.dmi
  hippiestation/icons/mob/inhands/righthand.dmi
  hippiestation/icons/obj/items_and_weapons.dmi
Labels: FUCK, Feature, Needs Head Input, Ready for Review, Sprites

#7615 Fire Suppression Sprinklers
  hippiestation.dme
  hippiestation/code/game/machinery/sprinkler.dm
  hippiestation/icons/obj/machines/sprinkler.dmi
Labels: Feature, Needs Head Input, Ready for Review

#7560 Makes colossus vocal cords a force to be reckoned with
  code/modules/surgery/organs/vocal_cords.dm
Labels: Needs Head Input, Tweak

#7763 fixes butterdog spam
  hippiestation/code/game/objects/items/cheapcuisine.dm
Labels: Fix, Ready for Review

#7806 Fixes Item slot issues on various items.
  hippiestation/code/datums/martial/sleeping_carp.dm
  hippiestation/code/game/objects/items/forged_weapons.dm
  hippiestation/code/game/objects/items/storage/dakis.dm
  hippiestation/code/modules/client/loadout/head.dm
  hippiestation/code/modules/projectiles/guns/ballistic/launchers.dm
  hippiestation/code/modules/sports/hockey.dm
  hippiestation/code/modules/surgery/organs/butts.dm
Labels: Fix

#7816 [MIRROR] Adds package-lock as requested by cyberboss (CONFLICTS FIXED)
  tgui/package-lock.json
Labels: Fix, Upstream PR Merged

#7809 Ports back old hippie arrivals
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Feature, Old Hippiestation Port

#7846 Removes pixel_x and pixel_y from map.
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Easy Fix

#7876 Update package-lock.json
  tgui/package-lock.json
Labels: Fix

#7848 Nerfs the nanosuit a bit
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Balance/Rebalance

#7670 You can now fill fire extinguishers with any reagent container!
  hippiestation/code/game/objects/items/extinguisher.dm
Labels: Feature, Needs Head Input, Ready for Review

#7911 Players can now only play as catbeasts
  README.md
Labels: Feature

#7913 Replaces all food with tacos
  README.md
Labels: Feature

#7935 Fixes report issue button by reverting it to tg
  hippiestation/interface/interface.dm
Labels: Fix, Revert
