Repository HippieStation/HippieStation, pull requests merged in 2018-07, with the labels that each got.

#7780 Added a fluxitus virus bottle and a super heal virus bottle (for adminbus shittery)
  hippiestation/code/datums/diseases/advance/presets.dm
  hippiestation/code/modules/reagents/reagent_containers/bottle.dm
Labels: FUCK, Feature, Needs Head Input, Ready for Review

#7960 Re-adds hiding tiny items in vent pumps (Ready)
  hippiestation/code/modules/atmospherics/unary_devices/vent_pump.dm
Labels: Feature, Old Hippiestation Port, Ready for Review

#8002 Reverted auto no vote shenanigans
  hippiestation.dme
  hippiestation/code/controllers/subsystem/vote.dm
Labels: Revert

#8000 Old map features + updates from box!!
  _maps/map_files/HippieStation/hippiestation.dmm
  hippiestation/code/game/area/Space_Station_13_areas.dm
  hippiestation/code/game/objects/structures/crates_lockers/closets.dm
Labels: Map Edit, Old Hippiestation Port, Trips get

#8018 Standardizes cam networks, minor tweaks/fixes
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/HippieStation/hippiestation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/shuttles/aux_base_default.dmm
  code/game/machinery/camera/camera.dm
  code/game/machinery/camera/motion.dm
  code/game/machinery/camera/presets.dm
  code/game/machinery/computer/camera.dm
Labels: Map Edit

#8024 Fixes morgue door air alarm and table blocking it
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Map Edit, Tweak

#7854 Adds the locker mech
  hippiestation.dme
  hippiestation/code/game/mecha/makeshift/lockermech.dm
  hippiestation/code/game/mecha/makeshift/makeshift_tools.dm
  hippiestation/code/modules/crafting/recipies.dm
  hippiestation/icons/mecha/lockermech.dmi
Labels: +1, Feature, Ready for Review

#8023 Lightbulb effects
  hippiestation.dme
  hippiestation/code/modules/power/lighting.dm
Labels: AWWWW FUCK YEAH, Feature, Tweak

#7959 Refactors nanosuit code and fixes/rebalance stuff.
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Balance/Rebalance, Feature, Fix, Ready for Review, Refactor

#8113 Fixes coffins and crate freezers
  hippiestation.dme
  hippiestation/code/game/objects/structures/crates_lockers/crates.dm
Labels: Fix

#8128 Fixes telescreens and cameras id tags
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Fix, Map Edit

#8135 Corrects nanosuit recharge times and consumption values
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Balance/Rebalance

#8148 Fixes floor pills not spawning
  hippiestation/code/_globalvars/lists/maintenance_loot.dm
Labels: Fix

#8151 fixes moth eyes being more vulnerable to flashes thanks tg
  hippiestation/code/modules/surgery/organs/eyes.dm
Labels: Fix, Tweak

#8158 Fixes loadout options not showing up.
  code/modules/client/preferences.dm
  hippiestation/code/modules/client/preferences.dm
Labels: Fix

#8173 Update misc.dm
  code/__DEFINES/misc.dm
Labels: Fix, Priority: CRITICAL

#8175 Update configuration.dm
  code/controllers/configuration/configuration.dm
Labels: Fix

#8199 Fixes telescreens around the map
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Fix, Map Edit

#8217 Adds delays to votes
  hippiestation/code/controllers/subsystem/vote.dm
Labels: Feature

#8280 Fixes garbage subsystem
  code/controllers/subsystem/garbage.dm
  hippiestation.dme
  hippiestation/code/game/turfs/turf.dm
Labels: Fix, Performance

#8285 Fixed conflicts
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Map Edit

#8142 Cybersun sponsorship kit
  hippiestation.dme
  hippiestation/code/game/objects/items/devices/synthmorpher.dm
  hippiestation/code/game/objects/items/storage/uplink_kits.dm
  hippiestation/code/modules/uplink/uplink_items.dm
Labels: Feature

#8302 Fixes wiki manuals
  code/game/objects/items/manuals.dm
  hippiestation.dme
  hippiestation/code/game/objects/items/manuals.dm
Labels: Fix

#8136 MMI tank circuit
  hippiestation/code/modules/integrated_electronics/subtypes/smart.dm
Labels: Feature, Tweak

#8319 Scream and fart keybinds have been changed back to using ctrl instead of shift
  hippiestation/code/modules/keybindings/bindings_hippie.dm
Labels: AWWWW FUCK YEAH, Old Hippiestation Port, Priority: CRITICAL, Tweak

#8320 disables pickup animations
  hippiestation.dme
  hippiestation/code/game/atoms_movable.dm
Labels: Removal

#8310 Fixes nanosuit causes runtime errors from overrides
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Fix

#8139 Adding list input
  hippiestation/code/modules/integrated_electronics/subtypes/input.dm
Labels: Feature

#8349 biogenerator fix
  hippiestation/code/modules/hydroponics/biogenerator.dm
  hippiestation/code/modules/research/designs/biogenerator_designs.dm
Labels: Code Improvement, Fix

#8355 Adding new merged PR files
  hippiestation.dme
Labels: Feature, Fix

#8350 Adds golden tools
  hippiestation.dme
  hippiestation/code/game/objects/items/tools/crowbar.dm
  hippiestation/code/game/objects/items/tools/screwdriver.dm
  hippiestation/code/game/objects/items/tools/weldingtool.dm
  hippiestation/code/game/objects/items/tools/wirecutters.dm
  hippiestation/code/game/objects/items/tools/wrench.dm
  hippiestation/icons/mob/inhands/equipment/tools_lefthand.dmi
  hippiestation/icons/mob/inhands/equipment/tools_righthand.dmi
  hippiestation/icons/obj/tools.dmi
Labels: Feature, Sprites

#8317 nerfs toolspeed due to popular demand [ready]
  hippiestation/code/game/objects/items/tools.dm
Labels: Balance/Rebalance, Needs Review, Tweak

#8356 some old icons added
  hippiestation.dme
  hippiestation/code/game/objects/structures/crematorium.dm
  hippiestation/code/modules/reagents/machinery.dm
  hippiestation/code/modules/research/rdmachines.dm
  hippiestation/icons/obj/chairs.dmi
  hippiestation/icons/obj/stationobjs.dmi
Labels: Code Improvement, Feature, Fix, Removal

#8368 add staplers
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Feature, Fix, Map Edit

#8399 Cult2
  hippiestation.dme
  hippiestation/code/game/gamemodes/cult/needed_players.dm
Labels: Fix

#8401 Fixes assstrong
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#8407 Rebuilt tgui
  tgui/assets/tgui.js
Labels: Pull Request Branch, UI

#8404 Mapfix + Adds resource storage
  _maps/RandomRuins/LavaRuins/lavaland_surface_seed_vault.dmm
  _maps/boxstation.json
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/HippieStation/hippiestation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/shuttles/aux_base_small.dmm
  _maps/shuttles/whiteship_box.dmm
  code/datums/components/material_container.dm
  code/datums/components/remote_materials.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas/shuttles.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/mining/laborcamp/laborstacker.dm
  code/modules/mining/machine_redemption.dm
  code/modules/mining/machine_silo.dm
  code/modules/mining/machine_stacking.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/designs/smelting_designs.dm
  code/modules/research/destructive_analyzer.dm
  code/modules/research/machinery/_production.dm
  code/modules/research/rdconsole.dm
  code/modules/research/techweb/all_nodes.dm
  hippiestation.dme
  icons/obj/clothing/accessories.dmi
  tgstation.dme
  tgui/assets/tgui.js
  tgui/src/interfaces/ore_redemption_machine.ract
Labels: Fix, Map Edit, Sprites, UI

#8318 Adds Thermo-electric Generator to Supermatter Engine Loop
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Feature, Fix, Map Edit

#8363 Gangs, boys
  code/__DEFINES/role_preferences.dm
  code/__DEFINES/~hippie_defines/antagonists.dm
  code/__DEFINES/~hippie_defines/atom_hud.dm
  code/__DEFINES/~hippie_defines/misc.dm
  code/game/objects/items/crayons.dm
  hippiestation.dme
  hippiestation/code/datums/hud.dm
  hippiestation/code/game/gamemodes/gangs/dominator.dm
  hippiestation/code/game/gamemodes/gangs/gang_items.dm
  hippiestation/code/game/gamemodes/gangs/gang_pen.dm
  hippiestation/code/game/gamemodes/gangs/gangs.dm
  hippiestation/code/game/gamemodes/gangs/gangtool.dm
  hippiestation/code/game/objects/effects/countdown.dm
  hippiestation/code/game/objects/effects/decals/crayon.dm
  hippiestation/code/game/objects/items/crayons.dm
  hippiestation/code/game/objects/items/implants/implant_gang.dm
  hippiestation/code/game/objects/items/implants/implant_mindshield.dm
  hippiestation/code/modules/antagonists/blob/blob/blob_report.dm
  hippiestation/code/modules/antagonists/gang/gang.dm
  hippiestation/code/modules/antagonists/gang/gang_datums.dm
  hippiestation/code/modules/antagonists/gang/gang_hud.dm
  hippiestation/icons/effects/crayondecal.dmi
  hippiestation/icons/obj/device.dmi
Labels: Candidate for Testmerge, Feature, LIQUID, PRE-APPROVED!!, Priority: High

#8415 new arc forge sprite by Satou
  hippiestation/icons/obj/3x3.dmi
Labels: Sprites

#8419 Removes Greytiding
  _maps/map_files/HippieStation/hippiestation.dmm
  code/game/machinery/doors/airlock_types.dm
Labels: Map Edit, Removal, Tweak

#8431 Fixes gang problems from the last event
  hippiestation.dme
  hippiestation/code/game/gamemodes/gangs/gang_items.dm
  hippiestation/code/game/gamemodes/gangs/gang_pen.dm
  hippiestation/code/game/objects/items/crayons.dm
  hippiestation/code/game/objects/items/implants/implant_gang.dm
  hippiestation/code/modules/antagonists/blob/blob/blob_report.dm
  hippiestation/code/modules/antagonists/gang/gang.dm
Labels: Fix, Tweak

#8360 [Ready] improvised glass hatchets
  hippiestation/code/game/objects/items/weaponry.dm
  hippiestation/code/modules/crafting/recipies.dm
  hippiestation/icons/mob/inhands/lefthand.dmi
  hippiestation/icons/mob/inhands/righthand.dmi
  hippiestation/icons/obj/weapons.dmi
Labels: Feature, Needs Review, PRE-APPROVED!!

#8435 Fix vote spamming
  hippiestation/code/controllers/subsystem/vote.dm
Labels: Fix

#8437 Truly fixes mentor memos...I think.
  code/modules/admin/admin_verbs.dm
  hippiestation/code/modules/admin/topic.dm
Labels: Fix
