Repository HippieStation/HippieStation, pull requests merged in 2018-09, with the labels that each got.

#8865 Fixes chem dispenser icon disappearing when power turns off
  hippiestation/code/modules/reagents/machinery.dm
Labels: Fix

#8645 Nerfs carbonhell's cheap cuisine
  hippiestation/code/game/objects/items/cheapcuisine.dm
  hippiestation/code/modules/vending/snack.dm
Labels: Balance/Rebalance, Tweak

#8709 [READY] Sopa de gondola
  hippiestation.dme
  hippiestation/code/modules/food_and_drinks/food/snacks_meat.dm
  hippiestation/code/modules/food_and_drinks/food/snacks_soup.dm
  hippiestation/code/modules/food_and_drinks/recipes/tablecraft/recipes_soup.dm
  hippiestation/code/modules/mob/living/simple_animal/friendly/gondola.dm
  hippiestation/icons/obj/food/food.dmi
  hippiestation/icons/obj/food/soupsalad.dmi
Labels: Feature, Needs Review, Sprites

#8895 Fixed preferences
  code/__DEFINES/preferences.dm
  hippiestation/code/modules/client/preferences_toggles.dm
Labels: Fix

#8893 [MIRROR] Refactor status displays
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/HippieStation/hippiestation.dmm
  _maps/map_files/MetaLake/MetaLake.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/debug/runtimestation.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/arrival_delta.dmm
  _maps/shuttles/emergency_asteroid.dmm
  _maps/shuttles/emergency_backup.dmm
  _maps/shuttles/emergency_bar.dmm
  _maps/shuttles/emergency_box.dmm
  _maps/shuttles/emergency_clown.dmm
  _maps/shuttles/emergency_cramped.dmm
  _maps/shuttles/emergency_delta.dmm
  _maps/shuttles/emergency_goon.dmm
  _maps/shuttles/emergency_imfedupwiththisworld.dmm
  _maps/shuttles/emergency_meta.dmm
  _maps/shuttles/emergency_mini.dmm
  _maps/shuttles/emergency_narnar.dmm
  _maps/shuttles/emergency_omega.dmm
  _maps/shuttles/emergency_raven.dmm
  _maps/shuttles/emergency_russiafightpit.dmm
  _maps/shuttles/emergency_scrapheap.dmm
  _maps/shuttles/emergency_supermatter.dmm
  _maps/shuttles/emergency_wabbajack.dmm
  _maps/shuttles/escape_pod_default.dmm
  _maps/shuttles/escape_pod_large.dmm
  _maps/shuttles/infiltrator_basic.dmm
  code/game/machinery/status_display.dm
  code/game/objects/objs.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/ai/login.dm
  code/modules/mob/living/silicon/ai/logout.dm
  code/modules/shuttle/shuttle.dm
Labels: Map Edit, Refactor

#8831 Nanosuit var tweaks, renames and code cleanup [READY]
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Code Improvement, Feature, Needs Review, Ready for Review

#8903 Improves pool code and makes makes more objects return initialize hints [READY]
  hippiestation/code/controllers/subsystem/ticker.dm
  hippiestation/code/datums/components/spell_catalyst.dm
  hippiestation/code/datums/dna.dm
  hippiestation/code/game/gamemodes/gangs/dominator.dm
  hippiestation/code/game/gamemodes/gangs/gang_pen.dm
  hippiestation/code/game/gamemodes/gangs/gangtool.dm
  hippiestation/code/game/gamemodes/vampire/vampire_powers.dm
  hippiestation/code/game/machinery/doors/blastco.dm
  hippiestation/code/game/machinery/reagent_forge.dm
  hippiestation/code/game/machinery/reagent_material_manipulator.dm
  hippiestation/code/game/machinery/trapdoors.dm
  hippiestation/code/game/mecha/clockwork/clockwork_mech.dm
  hippiestation/code/game/mecha/working/ripley.dm
  hippiestation/code/game/objects/effects/decals/cleanable/chem.dm
  hippiestation/code/game/objects/effects/decals/crayon.dm
  hippiestation/code/game/objects/effects/effect_system/effects_smoke.dm
  hippiestation/code/game/objects/inflatables.dm
  hippiestation/code/game/objects/items/cheapcuisine.dm
  hippiestation/code/game/objects/items/crayons.dm
  hippiestation/code/game/objects/items/implants/implant_gang.dm
  hippiestation/code/game/objects/items/implants/implant_teleporter.dm
  hippiestation/code/game/objects/items/staples.dm
  hippiestation/code/game/objects/items/weaponry.dm
  hippiestation/code/game/objects/noose.dm
  hippiestation/code/modules/pool/pool_controller.dm
  hippiestation/code/modules/pool/pool_drain.dm
  hippiestation/code/modules/pool/pool_main.dm
  hippiestation/code/modules/reagents/chemistry/machinery/lcasschem.dm
  hippiestation/code/modules/teeth/teeth.dm
Labels: Code Improvement, Consistency Issue, Needs Review

#8931 Fixes ghosts interacting with pool controller
  hippiestation/code/modules/pool/pool_controller.dm
  hippiestation/code/modules/pool/pool_main.dm
Labels: Fix

#8930 Performance fixes to TTS
  hippiestation/code/controllers/subsystem/tts.dm
Labels: Priority: High, Refactor

#8938 Fixes vamp mistform
  hippiestation/code/game/gamemodes/vampire/vampire_powers.dm
Labels: Fix

#8952 [READY] Making pAI connectors and mmi tanks work easier
  hippiestation/code/modules/integrated_electronics/subtypes/smart.dm
Labels: Needs Review, Tweak

#8956 re-adds Redail to our lobby music playlist
  hippiestation/sound/lobby/Bomberman Hero - Redail.ogg
  strings/round_start_sounds.txt
Labels: Sound

#8948 Adds a preference for footsteps, disables them by default
  code/__DEFINES/~hippie_defines/preferences.dm
  hippiestation.dme
  hippiestation/code/datums/components/footstep.dm
  hippiestation/code/modules/client/preferences.dm
  hippiestation/code/modules/client/preferences_toggles.dm
Labels: Tweak

#8959 Wheel chair badminbus
  hippiestation/code/modules/vehicles/wheelchair.dm
Labels: Administration

#8925 replaces the nerfed protolathe with a liberated one
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Balance/Rebalance, Feature, Map Edit

#8946 [READY]makes the circuit lab and RnD look better
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Feature, Map Edit, Needs Review, Nice, Tweak

#8997 Fix vampire revive
  hippiestation/code/game/gamemodes/vampire/vampire_powers.dm
Labels: Fix, Tweak

#9038 Fixes gangtool displaying like 10,000 seconds remaining for domination
  hippiestation/code/game/gamemodes/gangs/gangtool.dm
Labels: Fix

#9037 Gang-wide messages now show the name of who sends them
  hippiestation/code/game/gamemodes/gangs/gangtool.dm
  hippiestation/code/modules/antagonists/gang/gang.dm
Labels: Tweak

#9013 Fixes thralls having no examine message
  code/modules/mob/living/carbon/examine.dm
  hippiestation/code/modules/mob/living/carbon/examine.dm
Labels: Fix

#8996 Some vampire fixes
  hippiestation/code/game/gamemodes/vampire/vampire_bat.dm
  hippiestation/code/game/gamemodes/vampire/vampire_powers.dm
Labels: Fix

#9032 Adds warning message in player panel when player has related accounts
  code/modules/admin/admin.dm
Labels: Administration, Feature

#8999 Adds radial mode selection menu into Nanosuit [READY]
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
  hippiestation/icons/mob/actions/actions_nanosuit.dmi
Labels: Feature, Needs Review

#8991 [READY] Adding beaker slot circuit and extending selfref PR to all hippie reagent circuits
  hippiestation/code/modules/integrated_electronics/subtypes/reagents.dm
Labels: Feature, Needs Review

#9069 [READY] New bluespace floor tiles (#40126)
  icons/turf/floors.dmi
Labels: Needs Review, Sprites

#9070 Fixes pubby's missing tiles and a cleans a few other maps. (#40147)
  _maps/RandomRuins/SpaceRuins/deepstorage.dmm
  _maps/RandomRuins/SpaceRuins/vaporwave.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/shuttles/emergency_cere.dmm
Labels: Fix, Map Edit

#9071 [MIRROR] standardizes pubby atmospherics
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Feature, Fix, Map Edit

#8728 [READY] [HOLY FUCK FINALLY] Adding atmos circuits
  hippiestation.dme
  hippiestation/code/modules/integrated_electronics/subtypes/atmospherics.dm
Labels: Feature, Needs Review

#9060 Increase Captain's sabre hit speed by 25%
  hippiestation.dme
  hippiestation/code/game/objects/items/melee/misc.dm
Labels: Balance/Rebalance

#9027 Holotool refactor
  code/game/machinery/doors/airlock.dm
  code/game/objects/structures/window.dm
  code/modules/mob/living/silicon/robot/robot.dm
  hippiestation.dme
  hippiestation/code/game/objects/items/holotool.dm
  hippiestation/code/game/objects/items/holotool/holotool.dm
  hippiestation/code/game/objects/items/holotool/modes.dm
  hippiestation/icons/obj/holotool.dmi
  hippiestation/icons/obj/tools.dmi
Labels: Fix, Refactor

#9082 [URGENT] Nerfing atmos circuits
  hippiestation/code/modules/integrated_electronics/subtypes/atmospherics.dm
Labels: Balance/Rebalance

#8771 [READY] Adds waddle quirk and drunk side effect
  hippiestation.dme
  hippiestation/code/datums/components/waddling.dm
  hippiestation/code/datums/traits/neutral.dm
  hippiestation/code/modules/mob/living/carbon/life.dm
Labels: Feature, Fix, Needs Review, Ready for Review

#9089 Fixes catbans and cluwnebans once and for all fucking damn it
  code/controllers/subsystem/job.dm
  code/modules/client/preferences.dm
  hippiestation.dme
  hippiestation/code/controllers/subsystem/job.dm
  hippiestation/code/datums/dna.dm
  hippiestation/code/modules/mob/dead/new_player/new_player.dm
Labels: Fix

#9028 [Ready] Adds weaker roundstart clown car
  _maps/map_files/HippieStation/hippiestation.dmm
  _maps/map_files/MetaLake/MetaLake.dmm
  hippiestation.dme
  hippiestation/code/modules/vehicles/clown_car.dm
  hippiestation/icons/obj/vehicles.dmi
Labels: Feature, Map Edit, Needs Review, PRE-APPROVED!!, Sprites

#9127 Reverts initialize icon_hippie removal
  hippiestation/code/game/atoms.dm
Labels: Refactor, Revert

#9129 Fixes car runtime at roundstart
  hippiestation.dme
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Fix

#8998 Makes reagent states subsystem a processing SS
  hippiestation/code/controllers/subsystem/reagent_states.dm
Labels: Code Improvement, Performance

#9174 Prevents farting from doing damage outside of their ass-fall-off condition, adds a log to the attack log.
  hippiestation/code/modules/mob/living/carbon/human/emote.dm
Labels: Fix

#9185 [Ready][Tested]Fixed a bug in the join list circuit
  hippiestation/code/modules/integrated_electronics/subtypes/lists.dm
Labels: Fix, Needs Review

#9094 Changes some map related things
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Feature, Fix, Map Edit

#9188 Fixes the Contender not working
  code/modules/projectiles/boxes_magazines/_box_magazine.dm
Labels: Fix

#9210 Fixes Shotguns being 100% broken
  code/modules/projectiles/boxes_magazines/_box_magazine.dm
Labels: Fix

#9133 Nanosuit signals [READY]
  hippiestation/code/_onclick/item_attack.dm
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
  hippiestation/code/modules/mob/living/carbon/carbon.dm
Labels: Code Improvement, Needs Review

#9231 Ghetto cattle prod now works + code cleanup [READY]
  hippiestation/code/game/objects/items/stunbaton.dm
Labels: Code Improvement, Fix, Needs Review

#8929 Infiltration gamemode
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/infiltrator_cutter.dmm
  _maps/templates/infiltrator_base.dmm
  code/__DEFINES/role_preferences.dm
  code/__DEFINES/~hippie_defines/antagonists.dm
  code/__DEFINES/~hippie_defines/atom_hud.dm
  code/__DEFINES/~hippie_defines/misc.dm
  code/datums/components/uplink.dm
  code/datums/hud.dm
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/clothing/chameleon.dm
  code/modules/mob/living/silicon/ai/life.dm
  config/game_options.txt
  hippiestation.dme
  hippiestation/code/__HELPERS/game.dm
  hippiestation/code/_globalvars/lists/mapping.dm
  hippiestation/code/datums/action.dm
  hippiestation/code/datums/shuttles.dm
  hippiestation/code/game/area/areas/centcom.dm
  hippiestation/code/game/area/areas/shuttles.dm
  hippiestation/code/game/gamemodes/infiltration/infiltration.dm
  hippiestation/code/game/gamemodes/objective.dm
  hippiestation/code/game/gamemodes/objective_items.dm
  hippiestation/code/game/machinery/suit_storage_unit.dm
  hippiestation/code/game/objects/effects/landmarks.dm
  hippiestation/code/game/objects/effects/spawners/mapping.dm
  hippiestation/code/game/objects/items/devices/powersink.dm
  hippiestation/code/game/objects/items/implants/implant_dusting.dm
  hippiestation/code/game/objects/items/implants/implantuplink.dm
  hippiestation/code/modules/admin/topic.dm
  hippiestation/code/modules/admin/verbs/one_click_antag.dm
  hippiestation/code/modules/antagonists/hijacked_ai/hijacked_ai.dm
  hippiestation/code/modules/antagonists/infiltrator/_mapping.dm
  hippiestation/code/modules/antagonists/infiltrator/infiltrator.dm
  hippiestation/code/modules/antagonists/infiltrator/items/ai_hijack.dm
  hippiestation/code/modules/antagonists/infiltrator/items/hardsuit.dm
  hippiestation/code/modules/antagonists/infiltrator/items/pinpointer.dm
  hippiestation/code/modules/antagonists/infiltrator/items/services.dm
  hippiestation/code/modules/antagonists/infiltrator/objectives.dm
  hippiestation/code/modules/antagonists/infiltrator/outfit.dm
  hippiestation/code/modules/antagonists/infiltrator/team.dm
  hippiestation/code/modules/antagonists/traitor/equipment/Malf_Modules.dm
  hippiestation/code/modules/clothing/chameleon.dm
  hippiestation/code/modules/mob/living/silicon/ai/ai.dm
  hippiestation/code/modules/mob/living/silicon/ai/life.dm
  hippiestation/code/modules/shuttle/syndicate.dm
  hippiestation/code/modules/uplink/uplink_items.dm
  hippiestation/icons/obj/device.dmi
  hippiestation/icons/obj/module.dmi
  hippiestation/sound/ambience/antag/infiltrator.ogg
Labels: Config Update, Feature, Map Edit, ✋ Do Not Merge ✋

#9300 Infiltrator fixes
  hippiestation/code/modules/antagonists/infiltrator/infiltrator.dm
  hippiestation/code/modules/antagonists/infiltrator/objectives.dm
  hippiestation/code/modules/antagonists/infiltrator/team.dm
  hippiestation/icons/obj/device.dmi
Labels: Fix
