Repository HippieStation/HippieStation, pull requests merged in 2018-12, with the labels that each got.

#9956 Adds right legs
  code/__DEFINES/atmospherics.dm
  code/game/machinery/pipe/construction.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/atmospherics/machinery/components/binary_devices/binary_devices.dm
  code/modules/atmospherics/machinery/components/binary_devices/dp_vent_pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/passive_gate.dm
  code/modules/atmospherics/machinery/components/binary_devices/pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/valve.dm
  code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm
  code/modules/atmospherics/machinery/components/components_base.dm
  code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
  code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
  code/modules/atmospherics/machinery/components/unary_devices/heat_exchanger.dm
  code/modules/atmospherics/machinery/components/unary_devices/outlet_injector.dm
  code/modules/atmospherics/machinery/components/unary_devices/portables_connector.dm
  code/modules/atmospherics/machinery/components/unary_devices/tank.dm
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/atmospherics/machinery/other/meter.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/he_pipes.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/junction.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/manifold.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/manifold4w.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/simple.dm
  code/modules/atmospherics/machinery/pipes/layermanifold.dm
  code/modules/atmospherics/machinery/pipes/manifold.dm
  code/modules/atmospherics/machinery/pipes/manifold4w.dm
  code/modules/atmospherics/machinery/pipes/mapping.dm
  code/modules/atmospherics/machinery/pipes/pipes.dm
  code/modules/atmospherics/machinery/pipes/simple.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  hippiestation.dme
  icons/obj/atmospherics/components/binary_devices.dmi
  icons/obj/atmospherics/components/trinary_devices.dmi
  icons/obj/atmospherics/components/unary_devices.dmi
  icons/obj/atmospherics/pipes/he-junction.dmi
  icons/obj/atmospherics/pipes/he-manifold.dmi
  icons/obj/atmospherics/pipes/he-simple.dmi
  icons/obj/atmospherics/pipes/manifold.dmi
  icons/obj/atmospherics/pipes/meter.dmi
  icons/obj/atmospherics/pipes/pipe_item.dmi
  icons/obj/atmospherics/pipes/pressure_tank.dmi
  icons/obj/atmospherics/pipes/simple.dmi
  tgstation.dme
Labels: Revert, Sprites

#9985 Fixes right arms
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/surgery/bodyparts/bodyparts.dm
Labels: Fix, Priority: CRITICAL

#9986 fixes assistants and sec having no maint access and ghosts can spin chairs
  config/game_options.txt
Labels: Config Update

#9995 Multitool Functionality on Circuits Fix
  hippiestation/code/modules/integrated_electronics/core/assemblies.dm
  hippiestation/code/modules/integrated_electronics/core/integrated_circuit.dm
Labels: Fix

#9993 Moves all air supply pipes to piping layer 1
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Feature, Map Edit, Tweak

#9857 stun nettle introduction
  hippiestation.dme
  hippiestation/code/modules/hydroponics/grown/nettle.dm
  hippiestation/icons/mob/inhands/weapons/plants_lefthand.dmi
  hippiestation/icons/mob/inhands/weapons/plants_righthand.dmi
  hippiestation/icons/obj/hydroponics/growing.dmi
  hippiestation/icons/obj/hydroponics/seeds.dmi
  hippiestation/icons/obj/items_and_weapons.dmi
Labels: +1, +2, Feature

#9911 [MIRROR] Various map fixes 2 (FIXED)
  _maps/RandomRuins/SpaceRuins/TheDerelict.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/shuttles/pirate_default.dmm
Labels: Map Edit, Ready for Review

#9997 Adds telescience research node to our .dme file
  hippiestation.dme
Labels: Fix

#10000 Fixes forge not working
  hippiestation/code/controllers/subsystem/ticker.dm
  hippiestation/code/game/machinery/reagent_forge.dm
  hippiestation/code/game/machinery/reagent_material_manipulator.dm
Labels: 10000 get, Fix, Priority: High

#10003 Fixes map bugs from previous main map PR
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Fix, Map Edit

#10013 Fixes reagent floors, make reagent refinery upgrade-able
  hippiestation.dme
  hippiestation/code/game/machinery/reagent_sheet.dm
  hippiestation/code/game/turfs/simulated/floor.dm
  hippiestation/code/game/turfs/simulated/floor/mineral_floor.dm
Labels: Administration, Feature, Fix

#10020 More Integrated Circuits Fixes
  hippiestation/code/modules/integrated_electronics/core/assemblies.dm
  hippiestation/code/modules/integrated_electronics/passive/power.dm
  hippiestation/code/modules/integrated_electronics/subtypes/reagents.dm
Labels: Fix

#10021 Fixes cat brains not changing target mobs species
  hippiestation/code/modules/surgery/bodyparts/dismemberment.dm
Labels: Fix

#10029 Fixes some pipes, the Hippie Station 13 logo and other corrections.
  _maps/map_files/HippieStation/hippiestation.dmm
  hippiestation.dme
Labels: Fix, Map Edit, Tweak

#10033 Fixes chapel office have 2 apcs and chapel having no apc at all
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Fix, Map Edit

#9988 replaces switchblade with civilian switchblade as in the previous PR
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Balance/Rebalance, Map Edit

#9996 Grey Bull rebranding
  hippiestation.dme
  hippiestation/code/modules/food_and_drinks/drinks/drinks/drinks.dm
  hippiestation/code/modules/reagents/chemistry/reagents/drink_reagents.dm
Labels: Tweak, nice >:]

#10097 Fixes nanosuit insta-killing other targets
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Fix

#10098 Allows deconstruction of reagent refinery
  hippiestation/code/game/machinery/reagent_sheet.dm
Labels: Tweak

#10103 Compiles tgui
  hippiestation.dme
  tgui/assets/tgui.css
  tgui/assets/tgui.js
Labels: UI

#10132 Fixes reagent refinery and corpses being big gay
  code/modules/mob/dead/observer/observer_movement.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/living.dm
  hippiestation/code/game/machinery/reagent_sheet.dm
Labels: Fix, Priority: CRITICAL, nice >:]

#10151 Adds renamer circuit
  hippiestation/code/modules/integrated_electronics/subtypes/manipulation.dm
Labels: Feature

#10142 Makes nanosuit use cell.use() proc
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Code Improvement, Nanosuit

#10146 Fixes catbans not applying
  code/modules/admin/sql_ban_system.dm
  hippiestation/code/controllers/subsystem/job.dm
Labels: Administration

#10154 Fixes SQL error with mentors in admin_log table
  hippiestation/code/modules/admin/topic.dm
Labels: Administration

#10158 Pressing who verb now shows admin rank
  hippiestation/code/modules/client/verbs/who.dm
Labels: Administration, Feature

#10127 Department Cards
  hippiestation/code/modules/jobs/job_types/captain.dm
  hippiestation/code/modules/jobs/job_types/engineering.dm
  hippiestation/code/modules/jobs/job_types/medical.dm
  hippiestation/code/modules/jobs/job_types/science.dm
  hippiestation/code/modules/jobs/job_types/security.dm
Labels: Fix

#10165 Fixed cybernetic organs not having icons
  icons/obj/surgery.dmi
Labels: Fix, Sprites

#10164 Fixes reagent refinery not removing working reagent causing it to always be busy
  hippiestation/code/game/machinery/reagent_sheet.dm
Labels: Fix

#10004 various security refurbishments
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Do Not Merge, Feature, Map Edit, Tweak

#10182 Re-adds strange room, moves the forge, adds autolathe into testing lab.
  _maps/map_files/HippieStation/hippiestation.dmm
  hippiestation/code/game/area/Space_Station_13_areas.dm
Labels: Balance/Rebalance, Feature, Fix, Map Edit, Removal

#10178 adds hl2 scientist scream fixes issue #9804
  hippiestation.dme
  hippiestation/code/modules/clothing/suits/labcoat.dm
  hippiestation/sound/voice/halflife2scientist.ogg
Labels: Feature, Sound

#10167 Removes tts line from _DEFINES/preferences.dm file
  code/__DEFINES/preferences.dm
Labels: Code Improvement, Removal

#10179 Non-magic non-special projectiles become four times faster
  hippiestation.dme
  hippiestation/code/modules/projectiles/projectile.dm
  hippiestation/code/modules/projectiles/projectile/energy.dm
Labels: Balance/Rebalance

#10198 [READY] A Rather Large Escape Shuttle
  _maps/shuttles/emergency_big.dmm
  config/unbuyableshuttles.txt
  hippiestation/code/datums/shuttles.dm
Labels: +1, +2, Config Update, Feature, Map Edit, Needs Review

#10185 processors now actually accepts monkeys
  hippiestation/code/modules/food_and_drinks/kitchen_machinery/processor.dm
Labels: Fix

#10230 Fixes wheel chair division by zero
  hippiestation/code/modules/vehicles/wheelchair.dm
Labels: Fix

#10231 Fixes custom emotes saying you're banned
  code/modules/mob/living/emote.dm
Labels: Fix

#10144 Blacklists mime's cats from pictures
  hippiestation/code/modules/paperwork/photography.dm
Labels: Balance/Rebalance, Fix

#10145 Blacklists neurotoxin from state changes
  hippiestation/code/_globalvars/lists/typecache.dm
Labels: Balance/Rebalance
