Repository HippieStation/HippieStation, pull requests merged in 2018-11, with the labels that each got.

#9597 Fix damp rag smothering
  hippiestation.dme
  hippiestation/code/modules/detectivework/footprints_and_rag.dm
Labels: Fix

#9439 Don't panic!
  _maps/map_files/HippieStation/hippiestation.dmm
  _maps/map_files/MetaLake/MetaLake.dmm
  hippiestation.dme
  hippiestation/code/game/objects/effects/contraband.dm
  hippiestation/icons/obj/contraband.dmi
Labels: Feature, Map Edit

#9601 Revert ling nerf
  code/modules/antagonists/changeling/powers/tiny_prick.dm
  hippiestation.dme
  hippiestation/code/datums/status_effects/buffs.dm
  hippiestation/code/modules/antagonists/changeling/absorb.dm
  hippiestation/code/modules/antagonists/changeling/changeling.dm
  hippiestation/code/modules/antagonists/changeling/fakedeath.dm
  hippiestation/code/modules/antagonists/changeling/glands.dm
  hippiestation/code/modules/antagonists/changeling/headcrab.dm
  hippiestation/code/modules/antagonists/changeling/horrorform.dm
  hippiestation/code/modules/antagonists/changeling/lesserform.dm
  hippiestation/code/modules/antagonists/changeling/mutations.dm
  hippiestation/code/modules/antagonists/changeling/powers/tiny_prick.dm
  hippiestation/code/modules/antagonists/changeling/revive.dm
  hippiestation/icons/mob/inhands/changeling_lefthand.dmi
  hippiestation/icons/mob/inhands/changeling_righthand.dmi
  hippiestation/icons/mob/screen_gen.dmi
  hippiestation/icons/obj/items_and_weapons.dmi
  hippiestation/icons/obj/projectiles.dmi
Labels: Removal, Revert

#9637 Fix circuit lab not being wired properly
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Map Edit

#9636 Emote sensor nanites!
  code/__DEFINES/~hippie_defines/components.dm
  code/modules/research/techweb/all_nodes.dm
  hippiestation.dme
  hippiestation/code/datums/components/nanites.dm
  hippiestation/code/modules/mob/emote.dm
  hippiestation/code/modules/research/designs/nanite_designs.dm
  hippiestation/code/modules/research/nanites/nanite_programs.dm
  hippiestation/code/modules/research/nanites/nanite_programs/sensor.dm
Labels: Feature

#9611 Fixes shuttle seats having /tg/ arm rest
  hippiestation/code/game/objects/structures/beds_chairs/chair.dm
  hippiestation/icons/obj/chairs.dmi
Labels: Fix

#9645 Removes roundstart clown car
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Map Edit, Removal

#9635 Allows pool temp and drain to be activated by silicon and admins without hacking (READY)
  hippiestation/code/modules/pool/pool_controller.dm
  hippiestation/code/modules/pool/pool_wires.dm
Labels: Code Improvement, Feature

#9697 Removes antistun from hulk - keeps wall punching
  code/datums/mutations/hulk.dm
Labels: Balance/Rebalance, Removal

#9698 [MIRROR] Fixes the cargo bug
  tgui/assets/tgui.css
  tgui/assets/tgui.js
  tgui/src/interfaces/cargo.ract
Labels: UI

#9675 Adds combo moves to nanosuit + bug fixes and code cleanup.
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Code Improvement, Feature, Removal

#9724 Fixes holotool sticking to your suit storage
  hippiestation/code/game/objects/items/holotool/holotool.dm
Labels: Fix

#9671 Fix: Adding forgotten atmos file for circuits
  hippiestation.dme
Labels: Fix

#9672 REMOVES FREE NO DOWNSIDE ADRENALS FROM R&D
  code/modules/research/designs/nanite_designs.dm
Labels: Removal

#9752 Goat plushie nerf
  hippiestation/code/game/machinery/computer/arcade.dm
  hippiestation/code/game/objects/items/plushes.dm
Labels: Fix

#9747 Fixes pool silicon/aghost interaction not working properly.
  hippiestation/code/modules/pool/pool_controller.dm
  hippiestation/code/modules/pool/pool_drain.dm
  hippiestation/code/modules/pool/pool_main.dm
  hippiestation/code/modules/pool/pool_noodles.dm
Labels: Code Improvement, Fix, Maintainability/Hinders improvements

#9753 Fixes arcade prizes breaking compile
  hippiestation/code/game/machinery/computer/arcade.dm
Labels: Fix, Priority: CRITICAL

#9590 Stock parts can now be printed by any protolathe
  code/modules/research/designs/stock_parts_designs.dm
Labels: Balance/Rebalance, Tweak

#9769 Some Integrated Electronics Fixes
  hippiestation/code/modules/integrated_electronics/core/helpers.dm
  hippiestation/code/modules/integrated_electronics/core/special_pins/boolean_pin.dm
  hippiestation/code/modules/integrated_electronics/core/special_pins/color_pin.dm
  hippiestation/code/modules/integrated_electronics/core/special_pins/dir_pin.dm
  hippiestation/code/modules/integrated_electronics/subtypes/converters.dm
  hippiestation/code/modules/integrated_electronics/subtypes/text.dm
Labels: Fix

#9763 Adds a 'different' Booze-O-Mat for Space Pirates
  _maps/shuttles/pirate_default.dmm
  code/modules/vending/boozeomat.dm
Labels: Map Edit

#9760 Fix AI vox prefs not saving
  hippiestation/code/modules/client/preferences.dm
Labels: Fix

#9761 Fixes pool hacking not allow temp adjust until update [READY]
  hippiestation/code/modules/pool/pool_controller.dm
Labels: Fix, Needs Review, Ready for Review

#9667 Buffs cattle-prod stamina force from 80 to 100
  hippiestation/code/game/objects/items/stunbaton.dm
Labels: Balance/Rebalance

#9582 lube now requires 10u to apply to a tile and has an extremely more obvious sprite (blue sparkles) and no longer bypasses noslips
  code/datums/components/wet_floor.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  hippiestation.dme
  hippiestation/code/datums/components/wet_floor.dm
Labels: Balance/Rebalance, FUCK, GRUDGECODE

#9725 Buff blood-red hardsuit bomb resistance
  hippiestation/code/modules/clothing/suit.dm
Labels: Balance/Rebalance

#9827 Fixes cold pool temps frying you to death
  hippiestation/code/modules/pool/pool_controller.dm
  hippiestation/code/modules/pool/pool_wires.dm
Labels: Fix

#9847 Adds !new! AI death noise
  hippiestation/code/modules/mob/living/silicon/ai/ai.dm
  hippiestation/sound/voice/ai_death_hippie.ogg
Labels: Feature

#9634 [READY] Adding a new Circuitry UI and removing unneeded color limitation
  hippiestation/code/modules/integrated_electronics/core/assemblies.dm
  hippiestation/code/modules/integrated_electronics/core/integrated_circuit.dm
  hippiestation/code/modules/integrated_electronics/core/saved_circuits.dm
  html/browser/assembly_ui.css
Labels: Needs Review, Tweak

#9668 comments out blastco
  hippiestation/code/modules/uplink/uplink_items.dm
Labels: Removal

#9844 [WIP] Adds ban message so users know they got banned more clearly
  code/__DEFINES/~hippie_defines/layers.dm
  hippiestation.dme
  hippiestation/code/_onclick/hud/fullscreen.dm
  hippiestation/code/modules/admin/DB_ban/functions.dm
  hippiestation/icons/mob/screen_full.dmi
Labels: Feature, Work In Progress

#9860 Fixed assemblies not showing a list of inputs that ask for input
  hippiestation/code/modules/integrated_electronics/core/assemblies.dm
Labels: Fix

#9677 Slimes stop waiting 5 minutes before growing or splitting like the entitled fucking bastards they are
  code/modules/mob/living/simple_animal/slime/life.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/research/xenobiology/xenobiology.dm
  hippiestation.dme
  hippiestation/code/modules/mob/living/simple_animal/slime.dm
Labels: Balance/Rebalance, Tweak

#9896 sadsddassda
  hippiestation/code/game/gamemodes/vampire/vampire.dm
Labels: Fix

#9878 Another integrated circuits assembly fix
  hippiestation/code/modules/integrated_electronics/core/assemblies.dm
Labels: Fix

#9905 Fixes ticker.dm being outdated from tg
  hippiestation/code/controllers/subsystem/ticker.dm
Labels: Fix

#9893 Are you Australian? [port from old hippie]
  hippiestation/code/modules/mob/living/simple_animal/hostile/giant_spider.dm
Labels: +1, +2, +3, Feature, Old Hippiestation Port

#9890 Nanosuit armor slowdown removed, quick cuff breaking, bug fixes and code cleanup.
  code/modules/mob/living/carbon/human/human.dm
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Balance/Rebalance, Code Improvement, Feature, Fix, Nanosuit, Ready for Review

#9937 Fixes mentor say F4 not working
  hippiestation.dme
  hippiestation/code/modules/keybindings/bindings_admin.dm
  hippiestation/code/modules/keybindings/bindings_mentor.dm
  hippiestation/code/modules/mentor/mentorsay.dm
Labels: Administration, Fix, Priority: High

#9938 Actually fixes mentorsay not working with F4
  hippiestation/code/modules/keybindings/bindings_mentor.dm
Labels: Fix, Priority: CRITICAL

#9949 Actually fixes mentor say
  hippiestation.dme
  hippiestation/code/modules/keybindings/bindings_client.dm
  hippiestation/code/modules/keybindings/bindings_mentor.dm
Labels: Fix
