Repository HippieStation/HippieStation, pull requests merged in 2018-05, with the labels that each got.

#7499 Displays lobby theme name when playing.
  hippiestation.dme
  hippiestation/code/controllers/subsystem/ticker.dm
  hippiestation/code/game/sound.dm
Labels: Ready for Review, Tweak

#7570 metal rods can mine through rock [QoL]
  hippiestation.dme
  hippiestation/code/game/objects/items/stacks/rods.dm
Labels: +1, +2

#7580 many map fixes
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Fix, Map Edit

#7574 Protolathe printed power cells spawn with full power
  hippiestation.dme
  hippiestation/code/modules/research/designs/power_designs.dm
Labels: Balance/Rebalance, Feature, Needs Head Input

#7587 minor fix; lights up chapel and removes a space tile under a fakewall [quickmerge]
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Fix, Map Edit, Priority: CRITICAL

#7589 fixes the stacked pipe bug of the new map [critical quickmerge]
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Priority: CRITICAL

#7551 Makes reverse bear traps craftable, removes them from traitor uplink, also renamed uplink_item.dm to uplink_items.dm
  hippiestation.dme
  hippiestation/code/modules/crafting/recipies.dm
  hippiestation/code/modules/uplink/uplink_items.dm
Labels: +1, +2, Feature, Needs Head Input

#7599 Fixes the arrivals shuttle issue along with the pods/aux base/ mining shuttle and everything else related to dockers.
  _maps/hippiestation.json
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: FUCK, Fix, PRE-APPROVED!!, Priority: CRITICAL, Priority: High

#7543 Fixes ayylmao tongues not allowing communication unless you're antag
  hippiestation.dme
  hippiestation/code/modules/surgery/organs/tongue.dm
Labels: Feature, Needs Head Input

#7546 Old virology healing symptoms have been brought back!
  hippiestation.dme
  hippiestation/code/datums/diseases/advance/symptoms/genetics.dm
  hippiestation/code/datums/diseases/advance/symptoms/heal.dm
  hippiestation/code/datums/diseases/advance/symptoms/sensory.dm
  hippiestation/code/datums/diseases/advance/symptoms/viral.dm
Labels: +1, +2, Feature

#7550 Made plastic require salt instead of sulphuric acid, and lowered the required temp to make plastic
  hippiestation.dme
  hippiestation/code/modules/reagents/chemistry/recipes/others.dm
Labels: +1, Feature, Needs Head Input

#7561 Allows non-humans to gain the hulk mutation
  hippiestation/code/datums/mutations.dm
Labels: Feature

#7617 fixes farting and alternate screams
  code/game/objects/items.dm
  hippiestation/code/modules/mob/living/carbon/human/emote.dm
Labels: 80 year old man eating 10 bags of Cheetos., FUCK, Fix, Priority: CRITICAL

#7567 Adds the Monk mrtial art as a null-rod variant. Code by goofball,
  hippiestation.dme
  hippiestation/code/datums/martial/martial.dm
  hippiestation/code/datums/martial/monk.dm
  hippiestation/code/modules/mob/living/carbon/human/species.dm
Labels: +2, Cautious +1, Feature, Ready for Review
