Repository HippieStation/HippieStation, pull requests merged in 2018-02, with the labels that each got.

#6601 Fix invisible IPCs
  code/modules/surgery/bodyparts/bodyparts.dm
Labels: Fix

#6600 Removes spare from cap locker
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Revert/Removal

#6473 Re-adds our missing vending loot changes.
  hippiestation/code/game/machinery/vending.dm
  hippiestation/code/game/objects/items/vending_items.dm
Labels: Feature, Old Hippiestation Port, Revert/Removal

#6266 Newton's fart
  hippiestation/code/modules/mob/living/carbon/human/emote.dm
Labels: Priority: CRITICAL, Ready for Review, Tweak

#6453 Add additional functionality to hat stacking
  code/game/turfs/open.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/death.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  hippiestation.dme
  hippiestation/code/modules/clothing/head/misc.dm
  hippiestation/code/modules/mob/emote.dm
  hippiestation/code/modules/mob/living/carbon/carbon.dm
Labels: Feature, Ready for Review, Tweak

#6143 Fixes mentors
  code/__DEFINES/~hippie_defines/admin.dm
  code/__DEFINES/~hippie_defines/mentor.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/type2type.dm
  code/controllers/subsystem/vote.dm
  code/game/objects/items/charter.dm
  code/game/world.dm
  code/modules/admin/IsBanned.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_ranks.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/adminmenu.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/admin/verbs/adminsay.dm
  code/modules/admin/verbs/deadsay.dm
  code/modules/admin/verbs/pray.dm
  code/modules/awaymissions/capture_the_flag.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/verbs/ooc.dm
  code/modules/client/verbs/who.dm
  config/admin_ranks.txt
  config/hippiestation_config.txt
  config/mentors.txt
  hippiestation.dme
  hippiestation/SQL/mentor.sql
  hippiestation/code/_globalvars/lists/mobs.dm
  hippiestation/code/controllers/configuration.dm
  hippiestation/code/controllers/configuration/entries/general.dm
  hippiestation/code/init.dm
  hippiestation/code/modules/admin/admin.dm
  hippiestation/code/modules/admin/holder2.dm
  hippiestation/code/modules/admin/topic.dm
  hippiestation/code/modules/client/client_procs.dm
  hippiestation/code/modules/client/verbs/who.dm
  hippiestation/code/modules/mentor/follow.dm
  hippiestation/code/modules/mentor/mentor.dm
  hippiestation/code/modules/mentor/mentor_memo.dm
  hippiestation/code/modules/mentor/mentor_ranks.dm
  hippiestation/code/modules/mentor/mentor_verbs.dm
  hippiestation/code/modules/mentor/mentorhelp.dm
  hippiestation/code/modules/mentor/mentorpm.dm
  hippiestation/code/modules/mentor/mentorsay.dm
Labels: Config Update, Fix, SQL

#6690 Kills changeling adrenals again
  hippiestation.dme
Labels: Fix

#6704 Updated hippie code to match tg
  hippiestation/code/game/gamemodes/wizard/spellbook.dm
Labels: Fix

#6656 Hotel sec now gets TPed back when attempting to leave hotel
  hippiestation/code/game/objects/structures/ghost_role_spawners.dm
Labels: Tweak

#6646 Upgrades Soymilk
  hippiestation/code/modules/reagents/chemistry/reagents/drink_reagents.dm
Labels: Feature, Memecode, Tweak

#6675 Adds a pet cat to clown office
  _maps/map_files/HippieStation/hippiestation.dmm
  hippiestation/code/modules/mob/living/simple_animal/friendly/cat.dm
  hippiestation/icons/mob/pets.dmi
  hippiestation/sound/creatures/clownCatHonk.ogg
  hippiestation/sound/creatures/clownCatHonk2.ogg
  hippiestation/sound/creatures/clownCatHonk3.ogg
Labels: Map Edit

#6679 Armstrong Style
  code/modules/mob/living/carbon/human/species.dm
  hippiestation.dme
  hippiestation/code/datums/martial/armstrong.dm
  hippiestation/code/game/objects/items/storage/uplink_kits.dm
  hippiestation/code/modules/uplink/uplink_item.dm
  hippiestation/icons/mob/actions.dmi
  hippiestation/sound/weapons/armstrong_combo.ogg
  hippiestation/sound/weapons/armstrong_headbutt.ogg
  hippiestation/sound/weapons/armstrong_horse.ogg
  hippiestation/sound/weapons/armstrong_newcombo.ogg
  hippiestation/sound/weapons/armstrong_palmthrust.ogg
  hippiestation/sound/weapons/armstrong_punch.ogg
  hippiestation/sound/weapons/armstrong_success.ogg
  hippiestation/sound/weapons/armstrong_zipper.ogg
Labels: Feature, Fix, Ready for Review, Sound

#6653 Valentine's day thing
  hippiestation.dme
  hippiestation/code/modules/events/holiday/vday.dm
Labels: Ready for Review, Tweak

#6735 Undos bombs not fitting in bags
  hippiestation.dme
  hippiestation/code/game/objects/items/devices/transfer_valve.dm
Labels: +1, Balance/Rebalance, Needs Head Input, Tweak

#6754 Mime/Clown Pets Addition and Revamp
  _maps/map_files/HippieStation/hippiestation.dmm
  hippiestation/code/modules/mob/living/simple_animal/friendly/cat.dm
  hippiestation/code/modules/mob/living/simple_animal/hostile/feral_cat.dm
  hippiestation/icons/mob/pets.dmi
  hippiestation/sound/creatures/mimeCatInitialScream.ogg
  hippiestation/sound/creatures/mimeCatScream.ogg
  hippiestation/sound/creatures/mimeCatScream2.ogg
Labels: Feature, Map Edit, Sound

#6788 Fixes No-Slip shoes not actually being no-slip.
  hippiestation/code/modules/uplink/uplink_item.dm
Labels: Fix

#6645 Fixed surgery bugs that I introduced
  hippiestation/code/modules/surgery/surgery_step.dm
Labels: Fix, Ready for Review

#6851 Fixes Donkpocket Box Sprite
  hippiestation/icons/obj/storage.dmi
Labels: Fix, Sprites
