Repository HippieStation/HippieStation, pull requests merged in 2018-04, with the labels that each got.

#7325 Hippie self administration and automatic grief prevention system part 1.
  code/controllers/subsystem/processing/traits.dm
  code/modules/admin/verbs/adminhelp.dm
  hippiestation/code/datums/traits/negative.dm
Labels: Administration, Needs Head Input, Revert/Removal, Work In Progress

#7396 Fixes a bug on autoadmin pt 1.
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#7406 Revert "Fixes a bug on autoadmin pt 1."
  code/modules/mob/living/carbon/human/human.dm
Labels: Revert/Removal

#7410 Antigriff fix
  code/controllers/subsystem/processing/traits.dm
Labels: Fix

#7312 Tourettes stun duration reduced from 10 seconds to 2 seconds
  hippiestation/code/datums/mutations.dm
  hippiestation/code/datums/traits/neutral.dm
Labels: Fix, Ready for Review

#7307 Hedgehog
  hippiestation.dme
  hippiestation/code/modules/mob/living/simple_animal/friendly/hedgehog.dm
  hippiestation/icons/mob/animal.dmi
Labels: Feature, Ready for Review

#7374 THE MEGASEED 10 STRANGE SEEDS VIA COIN ARE BACK BABY
  hippiestation.dme
  hippiestation/code/modules/vending/megaseed.dm
Labels: Feature, Needs Head Input

#7472 Krav Maga for Security
  hippiestation.dme
  hippiestation/code/modules/jobs/job_types/security.dm
Labels: Feature

#7375 Weightless2
  hippiestation/code/modules/events/weightless.dm
Labels: +1, +2, Feature

#7387 Potted lean update
  hippiestation/code/modules/mob/living/simple_animal/hostile/retaliate/potted_lean.dm
Labels: +1, +2, Feature, Needs Head Input, Tweak

#7494 fixes issue #7185
  hippiestation/code/modules/uplink/uplink_item.dm
Labels: Balance/Rebalance, Fix

#7474 Updates staff list in the changelog
  html/changelog.html
Labels: Administration

#7520 Rebuilt tgui
  tgui/assets/tgui.css
  tgui/assets/tgui.js
  tgui/package-lock.json
Labels: Fix

#7516 Fixed sounds from emotes playing despite the emote not being able to run
  hippiestation/code/modules/mob/living/emote.dm
Labels: Fix

#7435 You can now get strange seeds from the biogenerator!
  hippiestation/code/modules/hydroponics/biogenerator.dm
  hippiestation/code/modules/research/designs/biogenerator_designs.dm
Labels: +1, +2, Feature, Needs Head Input, Ready for Review

#7504 Refactors and fixes Kanada code.
  hippiestation/code/datums/action.dm
  hippiestation/code/modules/sports/hockey.dm
Labels: Fix, Refactor

#7412 Adds Old School Vision trait, Inverted Colour Vision and adds some leftover code from my attempt at the Vibrancy trait
  hippiestation.dme
  hippiestation/code/datums/traits/neutral.dm
  hippiestation/code/modules/client/client_colour.dm
Labels: +1, Needs Head Input, Ready for Review

#7536 fixes some lobby runtimes
  code/controllers/subsystem/lighting.dm
  code/controllers/subsystem/vote.dm
  code/modules/projectiles/guns/magic.dm
  hippiestation/code/modules/mob/living/carbon/human/species_types/skeletons.dm
Labels: Fix

#7522 Added tool_behaviour to holotool
  hippiestation/code/game/objects/items/holotool.dm
Labels: Fix

#7537 makes shanks a tiny item. Like glass shards.
  hippiestation/code/modules/crafts/weaponry.dm
Labels: +1, +2, Balance/Rebalance

#7482 readds old baseball bat sprites
  hippiestation/code/game/objects/items/weaponry.dm
  hippiestation/icons/mob/inhands/lefthand.dmi
  hippiestation/icons/mob/inhands/righthand.dmi
  hippiestation/icons/obj/items_and_weapons.dmi
Labels: +1, +2, Ready for Review, Revert/Removal, Sprites

#7446 Adds a new hat, the turban
  hippiestation/code/modules/clothing/head/misc.dm
  hippiestation/code/modules/vending/clothesmate.dm
  hippiestation/icons/mob/head.dmi
  hippiestation/icons/obj/clothing/hats.dmi
Labels: +1, Feature, Needs Head Input

#7539 Fixes and Tweaks
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: +1, Feature, Fix, Map Edit, Needs Head Input

#7517 Talking in soft crit makes you whisper automatically
  hippiestation/code/modules/mob/living/say.dm
Labels: +1, +2, Tweak

#7357 #BroughtBack unstable mutation toxin to green slimes *READY TO MERGE*
  hippiestation.dme
  hippiestation/code/modules/reagents/chemistry/reagents/other_reagents.dm
  hippiestation/code/modules/reagents/chemistry/reagents/slime_extracts.dm
  hippiestation/code/modules/reagents/chemistry/recipes/toxins.dm
Labels: +1, +2, Fix, Needs Head Input

#7486 Makes you able to select you e-sword's color with a multi-tool
  hippiestation.dme
  hippiestation/code/game/objects/items/melee/energy.dm
Labels: +1, +2, Feature, Revert/Removal

#7558 Ends the racial bigotry
  hippiestation/code/modules/mob/living/carbon/human/species_types/avians.dm
  hippiestation/code/modules/mob/living/carbon/human/species_types/ipcs.dm
  hippiestation/code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  hippiestation/code/modules/mob/living/carbon/human/species_types/mothmen.dm
  hippiestation/code/modules/mob/living/carbon/human/species_types/skeletons.dm
  hippiestation/code/modules/mob/living/carbon/human/species_types/tarajans.dm
Labels: Fix

#7559 Fixed being unable to superfart while in soft crit
  hippiestation.dme
  hippiestation/code/modules/mob/living/say.dm
Labels: Fix

#7495 Gives Nukeops a combat knife* upon spawning
  hippiestation.dme
  hippiestation/code/game/gamemodes/nuclear/nuclear.dm
Labels: +1, Feature, Ready for Review

#7556 fixes round end sounds and adds a new one thanks to BlackPantsLegion Tex
  hippiestation/code/controllers/subsystem/ticker.dm
  hippiestation/sound/roundend/reasonsunknown.ogg
Labels: Fix, Sound

#7540 Crysis Nanosuit
  hippiestation.dme
  hippiestation/code/modules/clothing/spacesuits/hardsuit.dm
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
  hippiestation/code/modules/uplink/uplink_item.dm
  hippiestation/icons/mob/actions/actions_nanosuit.dmi
  hippiestation/icons/mob/nanosuit.dmi
  hippiestation/icons/obj/nanosuit.dmi
Labels: AWWWW FUCK YEAH, Feature, Needs Head Input

#7502 HERE WE GO, ADDS WHEELCHAIRS *READY TO MERGE*
  hippiestation.dme
  hippiestation/code/game/objects/structures/beds_chairs/chair.dm
  hippiestation/code/modules/crafting/recipies.dm
  hippiestation/code/modules/vehicles/_vehicle.dm
  hippiestation/code/modules/vehicles/wheelchair.dm
  hippiestation/icons/obj/vehicles.dmi
Labels: +2, Feature, Old Hippiestation Port
