Repository HippieStation/HippieStation, pull requests merged in 2018-08, with the labels that each got.

#8460 Adds shit to the .dme
  hippiestation.dme
Labels: Priority: High

#8468 fixes crayons
  hippiestation/code/game/objects/effects/decals/crayon.dm
  hippiestation/code/game/objects/items/crayons.dm
Labels: Fix

#8474 Adds back important admin commands, forgotten in time
  code/modules/admin/admin_verbs.dm
Labels: Administration

#8445 Petting the honks
  hippiestation/code/modules/mob/living/simple_animal/friendly/cat.dm
Labels: Feature

#8487 Mood Code Improvements [Merge-Ready?] (#39075)
  code/datums/brain_damage/special.dm
  code/datums/components/mood.dm
  code/datums/status_effects/debuffs.dm
  code/modules/mining/equipment/regenerative_core.dm
  code/modules/mob/living/carbon/alien/larva/life.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/living_defines.dm
  code/modules/surgery/organs/heart.dm
  code/modules/surgery/organs/lungs.dm
Labels: Balance/Rebalance, Fix

#8489 fixes removing mentor memos and orders show
  hippiestation/code/modules/mentor/mentor_memo.dm
Labels: Administration

#8414 Moves the Medieval Sec Armor kit to the Sec Wardrobe, and fixes a bug related to the wardrobe.
  hippiestation/code/modules/vending/security.dm
  hippiestation/icons/obj/vending.dmi
Labels: Fix, Tweak

#8374 Dildos
  code/__HELPERS/unsorted.dm
  hippiestation.dme
  hippiestation/code/game/objects/items/dildo.dm
  hippiestation/icons/obj/dicks.dmi
Labels: Code Improvement, Controversial, Feature, Sprites

#8494 Nerfs nanosuit armor block to 50%
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Balance/Rebalance

#8423 Add drain and extinguisher circuit
  hippiestation/code/modules/integrated_electronics/subtypes/reagents.dm
Labels: Feature

#8463 The Brickening
  hippiestation/code/_globalvars/lists/maintenance_loot.dm
  hippiestation/code/game/objects/items/weaponry.dm
  hippiestation/code/modules/uplink/uplink_items.dm
  hippiestation/icons/obj/weapons.dmi
  hippiestation/sound/effects/ZUBALAWA.ogg
  hippiestation/sound/effects/brick.ogg
Labels: Feature

#8418 Adds cartoon hitsounds for clown outfit
  hippiestation.dme
  hippiestation/code/modules/clothing/under/jobs/civilian.dm
  hippiestation/sound/misc/hitsounds/cartoon_badoing.ogg
  hippiestation/sound/misc/hitsounds/cartoon_bird_whistle_down.ogg
  hippiestation/sound/misc/hitsounds/cartoon_boing.ogg
  hippiestation/sound/misc/hitsounds/cartoon_boing1.ogg
  hippiestation/sound/misc/hitsounds/cartoon_boing2.ogg
  hippiestation/sound/misc/hitsounds/cartoon_boing_wobble.ogg
  hippiestation/sound/misc/hitsounds/cartoon_clown_nose.ogg
  hippiestation/sound/misc/hitsounds/cartoon_doying.ogg
  hippiestation/sound/misc/hitsounds/cartoon_drum_roll_smash.ogg
  hippiestation/sound/misc/hitsounds/cartoon_heavy_badoing.ogg
  hippiestation/sound/misc/hitsounds/cartoon_heavy_bong.ogg
  hippiestation/sound/misc/hitsounds/cartoon_hit_on_head.ogg
  hippiestation/sound/misc/hitsounds/cartoon_short_whistle.ogg
  hippiestation/sound/misc/hitsounds/cartoon_slide_whistle_down_crash.ogg
  hippiestation/sound/misc/hitsounds/cartoon_slip_donk.ogg
  hippiestation/sound/misc/hitsounds/cartoon_spin_whistle.ogg
  hippiestation/sound/misc/hitsounds/cartoon_waboing.ogg
  hippiestation/sound/misc/hitsounds/cartoon_wet_boing.ogg
  hippiestation/sound/misc/hitsounds/cartoon_whack.ogg
  hippiestation/sound/misc/hitsounds/cartoon_whiggle_whistle_down.ogg
  hippiestation/sound/misc/hitsounds/cartoon_whistle_down.ogg
  hippiestation/sound/misc/hitsounds/cartoon_whistle_up.ogg
  hippiestation/sound/misc/hitsounds/cartoon_wiggle_metal1.ogg
  hippiestation/sound/misc/hitsounds/cartoon_wiggle_metal2.ogg
  hippiestation/sound/misc/hitsounds/cartoon_wiggle_whistle_up.ogg
  hippiestation/sound/misc/hitsounds/cartoon_woink.ogg
  hippiestation/sound/misc/hitsounds/cartoon_woink.wav
Labels: Feature, Ready for Review, Sound

#8488 Now turn back to normal after lean exits your system.
  hippiestation/code/modules/reagents/chemistry/reagents/drink_reagents.dm
Labels: Tweak

#8430 ChemistryChanges
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Feature, Map Edit, Removal

#8538 Places a monument to our failure to defeat tg.
  _maps/map_files/HippieStation/hippiestation.dmm
  hippiestation.dme
  hippiestation/code/game/objects/structures/statues.dm
  hippiestation/icons/obj/statue.dmi
Labels: Feature, Map Edit, Sprites

#8613 Fixes our job.dm
  hippiestation/code/modules/jobs/job_types/job.dm
Labels: Fix

#8625 Fixes ling claw glitch
  hippiestation/code/modules/antagonists/changeling/mutations.dm
Labels: Fix

#8633 Vamp fixes
  hippiestation/code/datums/antagonists/vampire.dm
  hippiestation/code/game/gamemodes/vampire/vampire_other.dm
Labels: Do Not Merge, Fix, Tweak

#8637 Points at our contribution guidelines in the PR template and updates them
  .github/PULL_REQUEST_TEMPLATE.md
  hippiestation/README.md
Labels: GitHub

#8658 Fixes invisible Avians
  code/modules/surgery/bodyparts/bodyparts.dm
  hippiestation/code/modules/mob/living/carbon/human/species_types/avians.dm
  hippiestation/code/modules/mob/living/carbon/human/species_types/ipcs.dm
Labels: Fix

#8534 Add pAI connector
  code/modules/mob/living/silicon/pai/pai_shell.dm
  hippiestation/code/modules/integrated_electronics/subtypes/smart.dm
Labels: Balance/Rebalance, Feature

#8662 Changing commenting system
  code/modules/mob/living/silicon/pai/pai_shell.dm
  hippiestation/changes.md
Labels: Tweak

#8484 Clone scanners will not beep while scanning if the clone pod is in use
  code/game/machinery/computer/cloning.dm
  hippiestation/changes.md
Labels: Tweak

#8659 Vamp fixup
  hippiestation/code/datums/antagonists/vampire.dm
  hippiestation/code/game/gamemodes/vampire/traitor_vamp.dm
  hippiestation/code/game/gamemodes/vampire/vampire.dm
  hippiestation/code/game/gamemodes/vampire/vampire_other.dm
  hippiestation/code/game/gamemodes/vampire/vampire_powers.dm
  hippiestation/code/modules/mob/living/carbon/carbon.dm
Labels: Fix

#8673 Fix some minor shadowling bugs
  hippiestation/code/game/gamemodes/shadowling/shadowling.dm
  hippiestation/code/game/gamemodes/shadowling/shadowling_abilities.dm
Labels: Fix, Tweak

#8687 Adds new feature request template to unify them with issues
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: GitHub

#8710 Re-adds the old saxophone to the bar
  _maps/map_files/HippieStation/hippiestation.dmm
  hippiestation/code/game/objects/items/clown_items.dm
  hippiestation/sound/items/sax1.ogg
  hippiestation/sound/items/sax2.ogg
  hippiestation/sound/items/sax3.ogg
  hippiestation/sound/items/sax4.ogg
  hippiestation/sound/items/sax5.ogg
  hippiestation/sound/items/sax6.ogg
Labels: Feature, Map Edit

#8708 Various Sling fixes
  hippiestation/code/datums/antagonists/shadowling.dm
  hippiestation/code/datums/antagonists/thrall.dm
  hippiestation/code/game/gamemodes/shadowling/shadowling_abilities.dm
Labels: Fix, Tweak, ✋ Do Not Merge ✋

#8724 improving code for extinguisher circuit
  hippiestation/code/modules/integrated_electronics/subtypes/reagents.dm
Labels: Code Improvement

#8585 Null rods are now cosmetic differences only
  hippiestation.dme
  hippiestation/code/game/objects/items/holy_weapons.dm
Labels: Feature, Tweak

#8746 Prevent roundstart shadowlings from being repeated in roundend report
  hippiestation/code/datums/antagonists/shadowling.dm
Labels: Fix

#8723 Updates science from box station and adds nanite lab
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Feature, Map Edit, Removal, Tweak

#8380 Add MetaLake map
  _maps/_basemaphippie.dm
  _maps/map_files/MetaLake/MetaLake.dmm
  _maps/metalake.dm
  _maps/metalake.json
  config/maps.txt
  hippiestation/code/game/area/Space_Station_13_areas.dm
  hippiestation/icons/turf/areas.dmi
Labels: Config Update, Feature, Map Edit

#8775 MetaLake tweaks
  _maps/map_files/MetaLake/MetaLake.dmm
Labels: Feature, Map Edit

#8774 Fixes map issues caused by nanite lab add-on
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Fix, Map Edit, Tweak

#8776 Shadowlings no longer take oxy damage
  hippiestation/code/game/gamemodes/shadowling/shadowling.dm
Labels: Fix

#8794 Fixes shadowling veil only turning lights to emergency mode
  hippiestation/code/game/gamemodes/shadowling/shadowling_abilities.dm
Labels: Fix, Tweak

#8803 Fixes thralls?
  hippiestation/code/datums/antagonists/thrall.dm
Labels: Fix

#8804 Adds discord emojis
  hippiestation/icons/emoji.dmi
Labels: Feature

#8810 Removes now obsolete floorgrime path and icon (#39816)
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/RandomRuins/SpaceRuins/TheDerelict.dmm
  _maps/RandomRuins/SpaceRuins/caravanambush.dmm
  _maps/RandomRuins/SpaceRuins/cloning_facility.dmm
  _maps/RandomRuins/SpaceRuins/crashedship.dmm
  _maps/RandomRuins/SpaceRuins/deepstorage.dmm
  _maps/RandomRuins/SpaceRuins/listeningstation.dmm
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
  _maps/RandomRuins/SpaceRuins/onehalf.dmm
  _maps/RandomZLevels/Academy.dmm
  _maps/RandomZLevels/VR/snowdin_VR.dmm
  _maps/RandomZLevels/moonoutpost19.dmm
  _maps/RandomZLevels/snowdin.dmm
  _maps/RandomZLevels/undergroundoutpost45.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/HippieStation/hippiestation.dmm
  _maps/map_files/MetaLake/MetaLake.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/shuttles/emergency_meta.dmm
  _maps/shuttles/emergency_russiafightpit.dmm
  _maps/shuttles/pirate_default.dmm
  _maps/shuttles/ruin_caravan_victim.dmm
  _maps/shuttles/ruin_pirate_cutter.dmm
  _maps/shuttles/whiteship_box.dmm
  _maps/shuttles/whiteship_delta.dmm
  _maps/shuttles/whiteship_meta.dmm
  code/game/turfs/simulated/floor/plasteel_floor.dm
  icons/turf/floors.dmi
Labels: Map Edit, Removal, Sprites

#8813 Fix atom ordering problem in map files (#39889)
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/RandomRuins/SpaceRuins/TheDerelict.dmm
  _maps/RandomRuins/SpaceRuins/caravanambush.dmm
  _maps/RandomRuins/SpaceRuins/cloning_facility.dmm
  _maps/RandomRuins/SpaceRuins/crashedship.dmm
  _maps/RandomRuins/SpaceRuins/deepstorage.dmm
  _maps/RandomRuins/SpaceRuins/derelict6.dmm
  _maps/RandomRuins/SpaceRuins/listeningstation.dmm
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
  _maps/RandomZLevels/Academy.dmm
  _maps/RandomZLevels/VR/snowdin_VR.dmm
  _maps/RandomZLevels/moonoutpost19.dmm
  _maps/RandomZLevels/snowdin.dmm
  _maps/RandomZLevels/undergroundoutpost45.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/shuttles/emergency_meta.dmm
  _maps/shuttles/emergency_russiafightpit.dmm
  _maps/shuttles/pirate_default.dmm
  _maps/shuttles/ruin_caravan_victim.dmm
  _maps/shuttles/ruin_pirate_cutter.dmm
  _maps/shuttles/whiteship_box.dmm
  _maps/shuttles/whiteship_delta.dmm
  _maps/shuttles/whiteship_meta.dmm
  tools/mapmerge2/dmm.py
  tools/mapmerge2/precommit.py
Labels: Map Edit, Tools

#8827 Fixes ling absorbing getting stuck
  code/modules/antagonists/changeling/powers/absorb.dm
  hippiestation/code/modules/antagonists/changeling/absorb.dm
Labels: Fix

#8833 Fixes catbans
  code/controllers/subsystem/job.dm
  code/modules/admin/topic.dm
  hippiestation/code/datums/dna.dm
  hippiestation/code/modules/admin/topic.dm
  hippiestation/code/modules/jobs/job_types/job.dm
Labels: Administration

#8843 [READY] Fixes mindshield nanites fucking up gangs badly
  hippiestation/code/modules/antagonists/gang/gang.dm
Labels: Fix, Needs Review

#8842 [READY] Fixes changeling last resort newing null entities
  hippiestation/code/modules/antagonists/changeling/headcrab.dm
Labels: Fix, Needs Review

#8841 [READY] Fixes drift crawling in space while crit
  hippiestation/code/modules/mob/mob_movement.dm
Labels: Fix, Needs Review

#8849 Fixes reagent dispensers icons and adds glow in dark locker lights
  hippiestation/code/game/objects/structures/crates_lockers/closets.dm
  hippiestation/code/modules/reagents/reagent_dispenser.dm
Labels: Feature, Fix

#8875 Fixes vampires revive taking more than 1 minute
  hippiestation/code/game/gamemodes/vampire/vampire_powers.dm
Labels: Fix

#8878 fixes empty wizard box
  hippiestation/code/modules/clothing/outfits/standard.dm
Labels: Fix

#8584 [WIP] Adds Text-to-Speech
  .gitignore
  code/__DEFINES/preferences.dm
  code/__DEFINES/~hippie_defines/mobs.dm
  code/modules/client/preferences.dm
  config/hippiestation_config.txt
  hippiestation.dme
  hippiestation/code/_onclick/hud/hud.dm
  hippiestation/code/_onclick/hud/human.dm
  hippiestation/code/_onclick/hud/stamina.dm
  hippiestation/code/_onclick/hud/tts.dm
  hippiestation/code/controllers/configuration/entries/game_options.dm
  hippiestation/code/controllers/subsystem/tts.dm
  hippiestation/code/datums/dna.dm
  hippiestation/code/modules/admin/admin_verbs.dm
  hippiestation/code/modules/client/client_defines.dm
  hippiestation/code/modules/client/client_procs.dm
  hippiestation/code/modules/client/preferences_toggles.dm
  hippiestation/code/modules/mob/living/living.dm
  hippiestation/code/modules/mob/living/say.dm
  hippiestation/code/modules/tts/tts.dm
  hippiestation/icons/mob/screen_gen.dmi
  hippiestation/tools/tts_generator/FonixTalk.dll
  hippiestation/tools/tts_generator/OggEnc.exe
  hippiestation/tools/tts_generator/SharpTalk.dll
  hippiestation/tools/tts_generator/ftalk_us.dic
  hippiestation/tools/tts_generator/ftalk_us.dll
  hippiestation/tools/tts_generator/tts_generator.exe
Labels: Config Update, Feature, Needs Head Input, Work In Progress
