Repository HippieStation/HippieStation, pull requests merged in 2019-11, with the labels that each got.

#12234 optimizes lighting algorithm
  code/modules/lighting/lighting_source.dm
Labels: Performance, Tweak

#12248 Fixes bees and swarmers
  code/modules/mob/living/simple_animal/hostile/bees.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Fix

#12250 Fixes bees automated movement check having no delay
  code/modules/mob/living/simple_animal/hostile/bees.dm
Labels: Fix

#12241 Tgui next stuff (Sorry for the stupid amount of commits)
  code/game/machinery/computer/Operating.dm
  code/game/machinery/computer/crew.dm
  tgui-next/packages/tgui/components/Table.scss
  tgui-next/packages/tgui/interfaces/CrewConsole.js
  tgui-next/packages/tgui/interfaces/OperatingComputer.js
  tgui-next/packages/tgui/public/tgui.bundle.css
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/packages/tgui/routes.js
  tgui-next/packages/tgui/styles/color-map.scss
  tgui-next/packages/tgui/styles/variables.scss
  tgui/assets/tgui.css
  tgui/assets/tgui.js
  tgui/src/interfaces/clockwork_slab.ract
Labels: Code Improvement, Performance, UI

#12187 Re-opens SM cider
  hippiestation/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Labels: Feature

#12254 Adds cable layers + fixes SMES wiring
  _maps/map_files/HippieStation/hippiestation.dmm
  code/__DEFINES/layers.dm
  code/__DEFINES/power.dm
  code/game/turfs/turf.dm
  code/modules/plumbing/plumbers/reaction_chamber.dm
  code/modules/power/cable.dm
  code/modules/power/lighting.dm
  code/modules/power/power.dm
  hippiestation.dme
  icons/mob/radial.dmi
  icons/obj/power.dmi
  icons/obj/power_cond/layer_cable.dmi
  tgstation.dme
Labels: Fix, Map Edit, Sprites

#12161 Adds embed chance to forged weaponry
  hippiestation/code/game/objects/items/forged_weapons.dm
Labels: Feature

#12178 Buffs the Interdimensional Sword
  hippiestation/code/modules/spells/spell_types/bfs.dm
Labels: Balance/Rebalance

#12256 Build-A-Stand in tgui-next
  hippiestation/code/modules/guardian/guardianbuilder.dm
  tgui-next/packages/tgui/interfaces/Guardian.js
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/packages/tgui/routes.js
  tgui/src/interfaces/guardian.ract
Labels: Feature, UI

#12259 Adds 2 adminbus guns, Singulo and Tesla spawners
  hippiestation.dme
  hippiestation/code/modules/projectiles/ammunition/energy.dm
  hippiestation/code/modules/projectiles/ammunition/special.dm
  hippiestation/code/modules/projectiles/guns/energy/stun.dm
  hippiestation/code/modules/projectiles/projectile/energy.dm
  hippiestation/code/modules/projectiles/projectile/tesla.dm
Labels: Administration, Feature

#12260 Fixes the Ghost Stone
  hippiestation/code/modules/gauntlet/ghost.dm
Labels: Fix

#12242 Maybe fix syndie stone super jump melting your jumpsuit?
  hippiestation/code/modules/gauntlet/syndie.dm
Labels: Fix

#12261 Fixes atmospheres sometimes not mixing when they should
  code/__DEFINES/atmospherics.dm
Labels: Atmospherics, Fix

#12264 Fixes supermatter not properly outputting
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Fix, Map Edit

#12263 Some tweaks to singulo adminbus gun
  hippiestation/code/modules/projectiles/projectile/energy.dm
Labels: Fix, Tweak

#12240 Port dynamic fixes from /tg/
  code/__DEFINES/traits.dm
  code/__HELPERS/roundend.dm
  code/controllers/configuration/entries/game_options.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/modules/admin/admin.dm
  code/modules/admin/check_antagonists.dm
  code/modules/antagonists/revolution/revolution.dm
  code/modules/antagonists/wizard/equipment/spellbook.dm
  code/modules/mob/living/carbon/human/death.dm
  config/dynamic.json
  config/game_options.txt
  hippiestation/code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  html/changelogs/AutoChangeLog-pr-46132.yml
  html/changelogs/AutoChangeLog-pr-47100.yml
  html/changelogs/AutoChangeLog-pr-47313.yml
  html/changelogs/AutoChangeLog-pr-47341.yml
  html/changelogs/AutoChangeLog-pr-47351.yml
  html/changelogs/AutoChangeLog-pr-47395.yml
  html/changelogs/AutoChangeLog-pr-47491.yml
Labels: Config Update

#12253 Fix gangmageddon stuff
  hippiestation/code/game/gamemodes/gangs/gangtool.dm
  hippiestation/code/modules/antagonists/gang/gang.dm
  hippiestation/code/modules/antagonists/gang/vigilante.dm
Labels: Fix, Sprites

#12270 Logs superfarts better
  hippiestation/code/modules/mob/living/carbon/human/emote.dm
Labels: Administration, Logging

#12282 Fix mousetrap grenades
  hippiestation/code/game/objects/items/grenades/chem_grenade.dm
Labels: Fix

#12287 Fix predator stands
  hippiestation/code/modules/guardian/abilities/major/predator.dm
Labels: Fix, Tweak

#12246 Removes the filters
  hippiestation/code/modules/mob/living/say.dm
Labels: Removal

#12288 Adds debug deck for holoparasite testing
  hippiestation/code/modules/guardian/guardianbuilder.dm
Labels: Code Improvement

#12118 Fixes some shit catbeast code
  hippiestation/code/datums/dna.dm
  hippiestation/code/modules/admin/topic.dm
  hippiestation/code/modules/client/verbs/g2g.dm
  hippiestation/code/modules/jobs/job_types/job.dm
  hippiestation/code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  hippiestation/code/modules/mob/living/carbon/human/species_types/tarajans.dm
  hippiestation/code/modules/mob/living/emote.dm
  hippiestation/code/modules/power/supermatter/supermatter.dm
  hippiestation/code/modules/surgery/organs/ears.dm
  hippiestation/code/modules/surgery/organs/tails.dm
Labels: Code Improvement, Fix, Work In Progress

#12268 Chem dispenser fixes/tweaks
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Labels: Fix, Tweak

#12290 SSDiscord and Round Notifications
  SQL/database_changelog.txt
  SQL/tgstation_schema.sql
  SQL/tgstation_schema_prefixed.sql
  code/__DEFINES/subsystems.dm
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/discord.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/chat_commands.dm
  code/modules/discord/accountlink.dm
  code/modules/discord/manipulation.dm
  code/modules/discord/tgs_commands.dm
  code/modules/discord/toggle_notify.dm
  config/config.txt
  hippiestation.dme
  html/changelogs/AutoChangeLog-pr-44231.yml
  tgstation.dme
Labels: Config Update, SQL

#12291 Explosion stun rebalance
  code/__DEFINES/combat.dm
  code/game/objects/effects/effect_system/effects_other.dm
  code/game/objects/items/devices/doorCharge.dm
  code/game/objects/items/grenades/plastic.dm
  code/modules/antagonists/devil/true_devil/_true_devil.dm
  code/modules/mob/living/carbon/alien/alien_defense.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/monkey/monkey_defense.dm
  code/modules/mob/living/simple_animal/animal_defense.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  html/changelogs/AutoChangeLog-pr-45819.yml
Labels: Balance/Rebalance

#12295 Fix being unable to buy privately in Cargo UI
  code/modules/cargo/console.dm
Labels: Fix

#12297 Hippie chem fixes
  hippiestation/code/game/objects/effects/effect_system/effects_vapour.dm
  hippiestation/code/modules/reagents/chemistry/holder.dm
  hippiestation/code/modules/reagents/chemistry/reagents.dm
Labels: Fix

#12300 Fix special attack logs and dual saber special
  hippiestation/code/game/objects/item.dm
  hippiestation/code/game/objects/items/special_attacks.dm
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Fix

#12301 Fix ORM tgui-next
  hippiestation/code/modules/mining/machine_redemption.dm
  tgui-next/packages/tgui/interfaces/OreRedemptionMachine.js
  tgui-next/packages/tgui/public/tgui.bundle.js
Labels: Fix, UI

#12292 update permissions
  icons/mob/screen_alert.dmi
Labels: Sprites, Tweak

#12304 Woohoo Vending TGUI!
  code/modules/vending/_vending.dm
  hippiestation/code/modules/vending/_vending.dm
  tgui-next/packages/tgui/interfaces/Vending.js
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/packages/tgui/routes.js
Labels: Feature, UI

#12302 [PORT] Citadel Magnetic Weaponry
  code/game/machinery/recharger.dm
  hippiestation.dme
  hippiestation/code/modules/projectiles/ammunition/ballistic/magammo.dm
  hippiestation/code/modules/projectiles/guns/ballistic/ballistic.dm
  hippiestation/code/modules/projectiles/guns/ballistic/magweapon.dm
  hippiestation/code/modules/projectiles/guns/ballistic/magweapon_energy.dm
  hippiestation/icons/obj/guns/cit_guns.dmi
  hippiestation/sound/weapons/magburst.ogg
  hippiestation/sound/weapons/magpistol.ogg
  hippiestation/sound/weapons/magrifle.ogg
Labels: Feature, Tweak

#12286 adds spooky saxophone to caves away mission skeleton spawn
  _maps/RandomZLevels/caves.dmm
Labels: Feature, Map Edit

#12293 Re-add BlastCo
  code/modules/uplink/uplink_purchase_log.dm
  hippiestation.dme
  hippiestation/code/modules/antagonists/nukeop/blastco.dm
  hippiestation/code/modules/antagonists/nukeop/nukeop.dm
  hippiestation/code/modules/uplink/uplink_items.dm
Labels: Feature

#12218 Makes the thanos wardec sound more noice.
  hippiestation/sound/misc/wizard_wardec.ogg
Labels: Sound

#12303 Enables mentor PM verb
  hippiestation/code/modules/mentor/mentor_verbs.dm
  hippiestation/code/modules/mentor/mentorpm.dm
Labels: Feature

#12299 Increases restart/shuttle call vote delay
  hippiestation/code/controllers/subsystem/vote.dm
Labels: Tweak

#12296 513 stuff
  Dockerfile
  code/__DEFINES/typeids.dm
  code/__HELPERS/text.dm
  code/game/atoms.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/newscaster.dm
  code/game/machinery/status_display.dm
  code/game/objects/structures/musician.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/modifyvariables.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/death.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/mob_helpers.dm
  dependencies.sh
  hippiestation/code/datums/martial/knifeboxing.dm
  hippiestation/code/game/objects/structures/flora.dm
  hippiestation/code/modules/clothing/mask.dm
  hippiestation/code/modules/clothing/shoe.dm
  hippiestation/code/modules/mob/mob_helpers.dm
  hippiestation/code/modules/sports/hockey.dm
  tools/Redirector/textprocs.dm
Labels: Tools

#12314 Adds the OG X-COM Rifle.
  hippiestation.dme
  hippiestation/code/modules/projectiles/guns/ballistic/xcomrifle.dm
  hippiestation/code/modules/research/designs/weapon_designs.dm
  hippiestation/code/modules/research/techweb/all_nodes.dm
  hippiestation/icons/mob/inhands/weapons/xcom_lefthand.dmi
  hippiestation/icons/mob/inhands/weapons/xcom_righthand.dmi
  hippiestation/icons/obj/AA2.dmi
  hippiestation/sound/weapons/hit.ogg
  hippiestation/sound/weapons/reload.ogg
  hippiestation/sound/weapons/shoot.ogg
Labels: Feature, Sound, Sprites

#12322 Fixtherifle
  hippiestation/code/modules/projectiles/guns/ballistic/xcomrifle.dm
  hippiestation/icons/obj/AA2.dmi
Labels: Feature

#12315 Fix off-station vendors
  tgui-next/packages/tgui/interfaces/Vending.js
  tgui-next/packages/tgui/public/tgui.bundle.js
Labels: Fix, UI

#12326 Fix plants
  hippiestation/code/game/objects/structures/flora.dm
Labels: Fix

#12328 add triple barreled shotgun of the days of old
  code/datums/components/crafting/recipes.dm
  hippiestation/code/modules/projectiles/guns/ballistic/shotgun.dm
  hippiestation/code/modules/uplink/uplink_items.dm
  hippiestation/icons/obj/guns/projectile.dmi
Labels: Feature

#12318 Pool tgui-next and fixes [READY]
  code/modules/power/port_gen.dm
  hippiestation/code/modules/pool/pool_controller.dm
  hippiestation/code/modules/pool/pool_drain.dm
  hippiestation/code/modules/pool/pool_main.dm
  hippiestation/code/modules/power/port_gen.dm
  tgui-next/bin/tgui-build.bat
  tgui-next/packages/tgui/interfaces/Pool.js
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/packages/tgui/routes.js
Labels: Fix, Needs Review, UI

#12337 Fixes smoke not creating enough reagents
  hippiestation/code/modules/reagents/chemistry/holder.dm
  hippiestation/code/modules/reagents/chemistry/reagents.dm
Labels: Fix

#12336 added new sprite for triple barrel shotty made by mist furor
  hippiestation/icons/obj/guns/projectile.dmi
Labels: Feature

#12338 Tg power fixes
  code/modules/power/apc.dm
  code/modules/power/cable.dm
  code/modules/power/power.dm
Labels: Fix

#12276 makes catbeasts clumsy I think idk how to code
  hippiestation/code/modules/mob/living/carbon/human/species_types/tarajans.dm
Labels: Feature

#12324 Holoparasites are now bound to mind
  code/modules/fields/timestop.dm
  hippiestation/code/datums/mind.dm
  hippiestation/code/modules/guardian/abilities/major/explosive.dm
  hippiestation/code/modules/guardian/abilities/major/frenzy.dm
  hippiestation/code/modules/guardian/abilities/major/healing.dm
  hippiestation/code/modules/guardian/abilities/major/time.dm
  hippiestation/code/modules/guardian/abilities/minor/snares.dm
  hippiestation/code/modules/guardian/abilities/special/absolution.dm
  hippiestation/code/modules/guardian/abilities/special/pocket.dm
  hippiestation/code/modules/guardian/guardian.dm
  hippiestation/code/modules/guardian/guardianbuilder.dm
  hippiestation/code/modules/guardian/guardiandatum.dm
  hippiestation/code/modules/guardian/standarrow.dm
Labels: Feature

#12349 PORTS GRILLS AND BBQ RIBS
  code/datums/components/sizzle.dm
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/objects/items/gift.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/trash.dm
  code/modules/cargo/packs.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/food/condiment.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/food/snacks_sandwichtoast.dm
  code/modules/food_and_drinks/kitchen_machinery/grill.dm
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_sandwich.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/vending/cola.dm
  hippiestation.dme
  html/changelogs/AutoChangeLog-pr-46844.yml
  html/changelogs/AutoChangeLog-pr-46898.yml
  html/changelogs/AutoChangeLog-pr-46924.yml
  icons/obj/drinks.dmi
  icons/obj/food/containers.dmi
  icons/obj/food/food.dmi
  icons/obj/kitchen.dmi
  tgstation.dme
Labels: Sprites

#12350 Fixes ghost controlling the pool
  hippiestation/code/modules/pool/pool_controller.dm
Labels: Fix

#12357 Fixes ghost role spawner text having html headers in content
  code/game/objects/structures/ghost_role_spawners.dm
Labels: Fix

#12362 Singularity hammers no longer pull ghosts
  code/game/objects/items/singularityhammer.dm
Labels: Fix

#12353 Add Statbus button
  hippiestation/interface/interface.dm
  hippiestation/interface/skin.dmf
Labels: Feature

#12359 More tgui next stuff
  code/__DEFINES/machines.dm
  code/game/mecha/mech_bay.dm
  code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
  html/changelogs/AutoChangeLog-pr-47915.yml
  html/changelogs/AutoChangeLog-pr-47929.yml
  sound/machines/nuke/angry_beep.ogg
  sound/machines/nuke/confirm_beep.ogg
  sound/machines/nuke/general_beep.ogg
  tgui-next/packages/tgui/interfaces/ImplantChair.js
  tgui-next/packages/tgui/interfaces/KeycardAuth.js
  tgui-next/packages/tgui/interfaces/MechBayPowerConsole.js
  tgui-next/packages/tgui/interfaces/NuclearBomb.js
  tgui-next/packages/tgui/public/tgui.bundle.css
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/packages/tgui/routes.js
  tgui-next/packages/tgui/styles/components/NuclearBomb.scss
  tgui-next/packages/tgui/styles/main.scss
  tgui-next/packages/tgui/styles/themes/retro.scss
  tgui-next/packages/tgui/webpack.config.js
Labels: Sound, UI

#12364 Fix guardians being unable to toggle modes
  hippiestation/code/modules/guardian/guardian.dm
Labels: Fix

#12351 Adds HOS pug and grill
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Feature, Map Edit
