Repository HippieStation/HippieStation, pull requests merged in 2019-03, with the labels that each got.

#10777 Old Hippie Port: Saying "rouge" now gives you brain damage (and a random trauma)
  hippiestation/code/modules/mob/living/say.dm
  hippiestation/sound/effects/whistlefail.ogg
Labels: Feature, Needs Head Input, Ready for Review

#10796 Fixes stun gun/baton special attack exploding random machinery.
  hippiestation/code/game/objects/items/special_attacks.dm
Labels: Fix

#10776 Fixed traits and removed powergamey shit now you headmins better fucking re-enable it in the config or I'm gonna shoot up a school
  hippiestation.dme
  hippiestation/code/datums/traits/good.dm
  hippiestation/code/datums/traits/negative.dm
  hippiestation/code/datums/traits/neutral.dm
Labels: Balance/Rebalance, Needs Head Input, Ready for Review

#10836 Recompiles tgui
  tgui/assets/tgui.js
Labels: UI

#10693 [Ready for review] Added minesweeper to arcade machines
  hippiestation/code/game/machinery/computer/arcade.dm
  hippiestation/code/game/objects/items/circuitboards/computer_circuitboards.dm
  hippiestation/icons/arcade/minesweeper_1.dmi
  hippiestation/icons/arcade/minesweeper_2.dmi
  hippiestation/icons/arcade/minesweeper_3.dmi
  hippiestation/icons/arcade/minesweeper_4.dmi
  hippiestation/icons/arcade/minesweeper_5.dmi
  hippiestation/icons/arcade/minesweeper_6.dmi
  hippiestation/icons/arcade/minesweeper_7.dmi
  hippiestation/icons/arcade/minesweeper_8.dmi
  hippiestation/icons/arcade/minesweeper_empty.dmi
  hippiestation/icons/arcade/minesweeper_flag.dmi
  hippiestation/icons/arcade/minesweeper_hidden.dmi
  hippiestation/icons/arcade/minesweeper_mine.dmi
  hippiestation/icons/arcade/minesweeper_minehit.dmi
  hippiestation/sound/arcade/minesweeper_boardpress.ogg
  hippiestation/sound/arcade/minesweeper_emag1.ogg
  hippiestation/sound/arcade/minesweeper_emag2.ogg
  hippiestation/sound/arcade/minesweeper_explosion1.ogg
  hippiestation/sound/arcade/minesweeper_explosion2.ogg
  hippiestation/sound/arcade/minesweeper_explosion3.ogg
  hippiestation/sound/arcade/minesweeper_menuselect.ogg
  hippiestation/sound/arcade/minesweeper_startup.ogg
  hippiestation/sound/arcade/minesweeper_win.ogg
  hippiestation/sound/arcade/minesweeper_winfail.ogg
Labels: +3, Feature, Ready for Review

#10803 Crossbow Fixes
  hippiestation/code/modules/projectiles/guns/ballistic/launchers.dm
Labels: Fix

#10844 Runtime Error for Failing a Surgery Step Using Your Hands Fix
  hippiestation/code/modules/surgery/surgery_step.dm
Labels: Fix

#10847 [testmerge please] Revert "[Ready for review] Added minesweeper to arcade machines"
  hippiestation/code/game/machinery/computer/arcade.dm
  hippiestation/code/game/objects/items/circuitboards/computer_circuitboards.dm
  hippiestation/icons/arcade/minesweeper_1.dmi
  hippiestation/icons/arcade/minesweeper_2.dmi
  hippiestation/icons/arcade/minesweeper_3.dmi
  hippiestation/icons/arcade/minesweeper_4.dmi
  hippiestation/icons/arcade/minesweeper_5.dmi
  hippiestation/icons/arcade/minesweeper_6.dmi
  hippiestation/icons/arcade/minesweeper_7.dmi
  hippiestation/icons/arcade/minesweeper_8.dmi
  hippiestation/icons/arcade/minesweeper_empty.dmi
  hippiestation/icons/arcade/minesweeper_flag.dmi
  hippiestation/icons/arcade/minesweeper_hidden.dmi
  hippiestation/icons/arcade/minesweeper_mine.dmi
  hippiestation/icons/arcade/minesweeper_minehit.dmi
  hippiestation/sound/arcade/minesweeper_boardpress.ogg
  hippiestation/sound/arcade/minesweeper_emag1.ogg
  hippiestation/sound/arcade/minesweeper_emag2.ogg
  hippiestation/sound/arcade/minesweeper_explosion1.ogg
  hippiestation/sound/arcade/minesweeper_explosion2.ogg
  hippiestation/sound/arcade/minesweeper_explosion3.ogg
  hippiestation/sound/arcade/minesweeper_menuselect.ogg
  hippiestation/sound/arcade/minesweeper_startup.ogg
  hippiestation/sound/arcade/minesweeper_win.ogg
  hippiestation/sound/arcade/minesweeper_winfail.ogg
Labels: Revert

#10781 Makes the briefcase the lawyer starts with very robust, and makes it fit on the belt slot
  code/game/objects/items/storage/briefcase.dm
  hippiestation/code/game/objects/items/storage/briefcase.dm
Labels: Feature, Needs Head Input

#10774 Adds basic chems to underused plants
  hippiestation.dme
  hippiestation/code/modules/hydroponics/grown/cereals.dm
  hippiestation/code/modules/hydroponics/grown/flowers.dm
  hippiestation/code/modules/hydroponics/grown/grass_carpet.dm
  hippiestation/code/modules/hydroponics/grown/misc.dm
  hippiestation/code/modules/hydroponics/grown/onion.dm
  hippiestation/code/modules/hydroponics/grown/root.dm
  hippiestation/code/modules/hydroponics/grown/tobacco.dm
  hippiestation/code/modules/hydroponics/grown/towercap.dm
Labels: Needs Head Input, Tweak

#10846 More trait fixes and modifications
  hippiestation/code/datums/traits/good.dm
  hippiestation/code/datums/traits/negative.dm
  hippiestation/code/datums/traits/neutral.dm
Labels: Fix, Tweak

#10848 Minesweeper FIXES AND REINTRODUCTION
  hippiestation/code/game/machinery/computer/arcade.dm
  hippiestation/code/game/objects/items/circuitboards/computer_circuitboards.dm
  hippiestation/icons/arcade/minesweeper_1.dmi
  hippiestation/icons/arcade/minesweeper_2.dmi
  hippiestation/icons/arcade/minesweeper_3.dmi
  hippiestation/icons/arcade/minesweeper_4.dmi
  hippiestation/icons/arcade/minesweeper_5.dmi
  hippiestation/icons/arcade/minesweeper_6.dmi
  hippiestation/icons/arcade/minesweeper_7.dmi
  hippiestation/icons/arcade/minesweeper_8.dmi
  hippiestation/icons/arcade/minesweeper_empty.dmi
  hippiestation/icons/arcade/minesweeper_flag.dmi
  hippiestation/icons/arcade/minesweeper_hidden.dmi
  hippiestation/icons/arcade/minesweeper_mine.dmi
  hippiestation/icons/arcade/minesweeper_minehit.dmi
  hippiestation/sound/arcade/minesweeper_boardpress.ogg
  hippiestation/sound/arcade/minesweeper_emag1.ogg
  hippiestation/sound/arcade/minesweeper_emag2.ogg
  hippiestation/sound/arcade/minesweeper_explosion1.ogg
  hippiestation/sound/arcade/minesweeper_explosion2.ogg
  hippiestation/sound/arcade/minesweeper_explosion3.ogg
  hippiestation/sound/arcade/minesweeper_menuselect.ogg
  hippiestation/sound/arcade/minesweeper_startup.ogg
  hippiestation/sound/arcade/minesweeper_win.ogg
  hippiestation/sound/arcade/minesweeper_winfail.ogg
Labels: FUCK, Fix, Headmins approved, Ready for Review

#10852 Readds borg sprites and makes them selectable
  hippiestation.dme
  hippiestation/code/modules/mob/living/silicon/robot/robot.dm
  hippiestation/code/modules/mob/living/silicon/robot/robot_modules.dm
  hippiestation/icons/mob/robots.dmi
Labels: Feature, Fix, Sprites

#10861 Old DMAPI was used, now the correct one is used
  code/__DEFINES/tgs.config.dm
Labels: Do Not Merge

#10857 Nerf nanosuit slightly
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
  hippiestation/code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance, Removal

#10873 Fixes glow berries not initialization/adding genes properly
  hippiestation/code/modules/hydroponics/grown/berries.dm
Labels: Fix

#10882 even more minesweeping fixes
  hippiestation/code/game/machinery/computer/arcade.dm
Labels: Fix, Tweak

#10840 Kills triple virus stack
  hippiestation/code/datums/diseases/_MobProcs.dm
Labels: Balance/Rebalance, Needs Head Input

#10884 Nerfs charge time on nanosuit
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Balance/Rebalance, Fix

#10917 Fixes fastdrones exploit and some timing shitcode
  hippiestation/code/modules/integrated_electronics/subtypes/manipulation.dm
  hippiestation/code/modules/integrated_electronics/subtypes/time.dm
Labels: Fix

#10891 Traitor Changes
  code/game/objects/items/grenades/plastic.dm
  hippiestation.dme
  hippiestation/code/datums/martial/sleeping_carp.dm
  hippiestation/code/game/objects/items/grenades/plastic.dm
  hippiestation/code/game/objects/items/implants/implant_explosive.dm
  hippiestation/code/game/objects/items/melee/energy.dm
  hippiestation/code/game/objects/items/storage/backpack.dm
  hippiestation/code/game/objects/items/toy.dm
  hippiestation/code/modules/projectiles/guns/energy/special.dm
  hippiestation/code/modules/uplink/uplink_items.dm
  hippiestation/icons/obj/guns/energy.dmi
Labels: Balance/Rebalance, Feature, Removal, Tweak

#10819 [DNM] Revert "[MIRROR] Revert "Bandaid for the TGS4 Linux trusted mode bug""
  code/game/world.dm
  code/modules/tgs/event_handler.dm
  hippiestation.dme
  tgstation.dme
Labels: Do Not Merge, Revert

#10990 Updates metalake to latest version
  _maps/map_files/MetaLake/MetaLake.dmm
Labels: Fix, Map Edit
