Repository HippieStation/HippieStation, pull requests merged in 2019-06, with the labels that each got.

#11571 Better(?) Vampire blood draining
  hippiestation/code/datums/antagonists/vampire.dm
  hippiestation/sound/effects/vampsip.ogg
Labels: Balance/Rebalance, Sound

#11722 REDUCES EARDRUM OBLITERATION
  hippiestation/sound/misc/nanosuitengage.ogg
Labels: Sound

#11398 Makes gibs less OP
  hippiestation/code/modules/mob/living/simple_animal/hostile/sentientgibs.dm
Labels: Tweak

#11358 Adds Gatfruit as a botany only traitor item
  hippiestation.dme
  hippiestation/code/modules/hydroponics/grown/gatfruit.dm
  hippiestation/code/modules/uplink/uplink_items.dm
Labels: Feature, Head Maintainer Review, Headmins approved, Review Before Merging

#11723 Revert "[MIRROR] Fix scrubber network for the incinerator/janitor's/botany backroom/service rooms on Metastation"
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Map Edit, Revert

#11703 Update package-lock.json
  tgui/package-lock.json
Labels: UI

#11679 Reagent blacklist improvements and lube bars!
  hippiestation/code/_globalvars/lists/typecache.dm
  hippiestation/code/modules/reagents/chemistry/holder.dm
  hippiestation/code/modules/reagents/chemistry/reagents.dm
  hippiestation/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  hippiestation/code/modules/reagents/chemistry/reagents/drink_reagents.dm
  hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
  hippiestation/code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
  hippiestation/code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Code Improvement, Fix, Removal, Tweak

#11647 Buffs spatial gateways
  hippiestation.dme
  hippiestation/code/modules/antagonists/clockcult/clock_effects/spatial_gateway.dm
Labels: Balance/Rebalance, Head Maintainer Review, Headmins approved

#11507 Adminbus chem: Grape blast (WIP)
  hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
  hippiestation/code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Feature, Head Maintainer Review, Headmins approved

#11753 Toxins 3.0
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Feature, Map Edit

#11767 Adds High-Frequency Blades
  hippiestation.dme
  hippiestation/code/game/objects/items/melee/hfblade.dm
  hippiestation/code/modules/uplink/uplink_items.dm
  hippiestation/icons/mob/hfblade.dmi
  hippiestation/icons/mob/inhands/weapons/melee_lefthand.dmi
  hippiestation/icons/mob/inhands/weapons/melee_righthand.dmi
  hippiestation/icons/obj/hfblade.dmi
  hippiestation/sound/weapons/hfblade-music1.ogg
  hippiestation/sound/weapons/hfblade-music2.ogg
Labels: Feature, Sound

#11773 Update package-lock.json
  tgui/package-lock.json
Labels: UI

#11779 Fix PDA server, I think
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Map Edit

#11765 Unfucks vampires
  hippiestation/code/datums/antagonists/vampire.dm
Labels: Fix

#11781 Improves special attack logging
  hippiestation/code/game/objects/item.dm
  hippiestation/code/game/objects/items/special_attacks.dm
  hippiestation/code/game/objects/items/weaponry.dm
  hippiestation/code/modules/telescience/telepad.dm
Labels: Administration, Logging

#11627 Buffs locomotion circuit to be not utterly useless
  hippiestation/code/modules/integrated_electronics/subtypes/manipulation.dm
Labels: Head Maintainer Review, Headmins approved

#11780 Fixes beds
  code/game/objects/structures/beds_chairs/bed.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/he_pipes.dm
Labels: Fix

#11785 Revert genetics analyzer to old behavior
  hippiestation/code/game/objects/items/devices/scanners.dm
Labels: +1, Balance/Rebalance, Revert

#11786 Fix some things in Toxins 3.0
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Fix, Map Edit

#11568 Clockpod for the centcomm supplypod launcher for admemes
  code/__DEFINES/cargo.dm
  code/modules/cargo/centcom_podlauncher.dm
  icons/obj/supplypods.dmi
  tgui/src/interfaces/centcom_podlauncher.ract
Labels: Head Maintainer Review, Headmins approved, Sprites, UI

#11782 Badmin Gauntlet changes
  hippiestation/code/modules/clothing/outfits/ert.dm
  hippiestation/code/modules/gauntlet/gauntlet.dm
  hippiestation/code/modules/gauntlet/revengers.dm
  hippiestation/icons/mob/inhands/lefthand.dmi
  hippiestation/icons/mob/inhands/righthand.dmi
  hippiestation/icons/obj/items_and_weapons.dmi
Labels: +1, Balance/Rebalance, Feature

#11506 Hamon Martial Art
  hippiestation.dme
  hippiestation/code/datums/martial/hamon.dm
Labels: Feature, Head Maintainer Review, Headmins approved

#11788 Add chemical reaction for soda water 2: Electric Boogaloo
  hippiestation.dme
  hippiestation/code/modules/reagents/chemistry/recipes/Bar_Reactions.dm
Labels: Feature

#11792 Add new roundend sound
  hippiestation/code/controllers/subsystem/ticker.dm
  sound/roundend/you're not cool.ogg
Labels: Sound

#11048 Added a new chem, Randonium
  hippiestation/code/modules/reagents/chemistry/reagents/other_reagents.dm
  hippiestation/code/modules/reagents/chemistry/recipes/other.dm
Labels: Feature, Headmins approved, Stale

#11802 thanos sprite thanos sprite
  hippiestation/code/modules/gauntlet/ganymede.dm
  hippiestation/code/modules/gauntlet/gauntlet.dm
  hippiestation/icons/mob/head.dmi
  hippiestation/icons/mob/large-worn-icons/64x64/head.dmi
  hippiestation/icons/mob/mutant_bodyparts.dmi
  hippiestation/icons/mob/suit.dmi
  hippiestation/icons/obj/clothing/hats.dmi
  hippiestation/icons/obj/clothing/suits.dmi
  hippiestation/icons/obj/infinity.dmi
Labels: Sprites

#11812 BEHOLD, HANGED MAN!
  code/modules/mob/living/simple_animal/guardian/guardian.dm
  code/modules/mob/mob.dm
  hippiestation.dme
  hippiestation/code/modules/mob/living/carbon/human/human.dm
  hippiestation/code/modules/mob/living/simple_animal/guardian/types/reflective.dm
  hippiestation/icons/effects/beam.dmi
  hippiestation/icons/mob/actions.dmi
Labels: Designer +2, Feature, Headmins approved

#11815 Re-adds Screambots and Frightbots
  code/game/objects/items/stacks/sheets/sheet_types.dm
  hippiestation.dme
  hippiestation/code/game/machinery/bots/frightbot.dm
  hippiestation/code/game/machinery/bots/screambot.dm
  hippiestation/icons/obj/aibots_new.dmi
  hippiestation/sound/machines/fright.ogg
Labels: Feature, Old Hippiestation Port

#11817 Nerf reflective holoparasite
  hippiestation/code/modules/mob/living/simple_animal/guardian/types/reflective.dm
Labels: Balance/Rebalance, FUCK

#11814 gives me $1
  hippiestation/code/game/objects/items/cheapcuisine.dm
Labels: Tweak

#11808 Readds Null Crates
  code/modules/cargo/packs.dm
  code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance

#11809 Band-Aid fix for HF blade until I actually get around to adding more stuff to it
  hippiestation/code/modules/uplink/uplink_items.dm
Labels: Tweak
