Repository HippieStation/HippieStation, pull requests merged in 2019-05, with the labels that each got.

#11327 Fixes our alternate slip sounds
  code/game/turfs/open.dm
  hippiestation/code/datums/outputs.dm
  hippiestation/code/modules/clothing/shoe.dm
  hippiestation/code/modules/clothing/under/jobs/civilian.dm
Labels: Fix

#11322 Fixes floorcluwne getting confused when mob changes body
  hippiestation/code/modules/mob/living/simple_animal/floor_cluwne.dm
Labels: Fix

#11321 Stopped nanosuit from runtiming when using martial arts
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Fix

#11170 Adds a sentient pile of gibs monster for adminbus
  hippiestation.dme
  hippiestation/code/modules/antagonists/changeling/horrorform.dm
  hippiestation/code/modules/mob/living/simple_animal/hostile/sentientgibs.dm
Labels: Feature

#11319 Adds G17 to gangs and fixes shuttle not departing
  hippiestation/code/game/gamemodes/gangs/dominator.dm
  hippiestation/code/game/gamemodes/gangs/gang_items.dm
Labels: Feature, Fix

#11298 Infiltrator event!
  hippiestation.dme
  hippiestation/code/modules/events/infiltrators.dm
Labels: Feature

#11127 adds ghetto/improvised tools
  hippiestation/code/game/objects/items/tools.dm
  hippiestation/code/modules/crafting/recipes.dm
  hippiestation/icons/obj/tools.dmi
Labels: Feature

#11120 Beware of the blob...
  hippiestation.dme
  hippiestation/code/game/gamemodes/blob.dm
  hippiestation/sound/ambience/antag/blob.ogg
Labels: Feature

#11029 star trek redshirts (now with functionality)
  code/modules/clothing/under/trek.dm
Labels: Feature, Needs Head Input, Tweak

#11333 buffs IEDs [ready]
  hippiestation.dme
  hippiestation/code/game/objects/items/grenades/ghettobomb.dm
Labels: Needs Review, Tweak

#11128 Changes holochips to real wads of cash (digitalizable)
  hippiestation.dme
  hippiestation/code/game/objects/items/credit_holochip.dm
  hippiestation/icons/obj/economy.dmi
Labels: Sprites

#11328 zombies are told to behave as zombies [remade & ready]
  hippiestation.dme
  hippiestation/code/modules/zombie/organs.dm
Labels: Tweak

#11340 Gibs rework 2: Electric Boogaloo
  hippiestation/code/modules/antagonists/changeling/horrorform.dm
  hippiestation/code/modules/mob/living/simple_animal/hostile/sentientgibs.dm
Labels: Balance/Rebalance, Feature, Fix, Tweak

#11367 Remove CRAB-17 and Executioner's Sword from VR
  hippiestation/code/modules/uplink/uplink_items.dm
Labels: Fix, Removal

#11347 Make infiltrator pinpointer upgrade work better
  hippiestation/code/game/gamemodes/objective.dm
  hippiestation/code/modules/antagonists/infiltrator/items/pinpointer.dm
Labels: Feature

#11412 Fix #6781
  hippiestation/code/modules/reagents/chemistry/recipes/slime_extracts.dm
Labels: Fix

#11463 Fixes some sprites from previous Upstream PR's
  icons/mob/head.dmi
Labels: Fix, Sprites

#11464 fff
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#10850 Reverts perfluorodecalin BUT it no longer mutes
  hippiestation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Balance/Rebalance, Needs Head Input, Ready for Review, Revert

#11034 Dildos2
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Feature, Map Edit, Needs Head Input, Old Hippiestation Port

#11331 A more robust null rod revert (plus chappy traitor monk-fu)
  code/__DEFINES/~hippie_defines/dna.dm
  hippiestation.dme
  hippiestation/code/datums/mutations.dm
  hippiestation/code/game/objects/items/holy_weapons.dm
  hippiestation/code/modules/crafting/recipes.dm
  hippiestation/code/modules/jobs/job_types/chaplain.dm
  hippiestation/code/modules/uplink/uplink_items.dm
  hippiestation/icons/mob/inhands/lefthand.dmi
  hippiestation/icons/mob/inhands/righthand.dmi
Labels: Balance/Rebalance, Feature, Revert

#11346 [OLD HIPPIESTATION PORT] Reduces tourettes stun time from literally 20 seconds to 1 second
  code/datums/mutations/body.dm
Labels: Balance/Rebalance, Old Hippiestation Port, Ready for Review

#11173 Adds a shaft miner traitor item: Anti-gravity boots
  hippiestation/code/modules/clothing/shoes/magboots.dm
  hippiestation/code/modules/uplink/uplink_items.dm
Labels: Feature

#11490 Unfucks the Syndicate Shuttle turrets
  hippiestation.dme
  hippiestation/code/game/machinery/porta_turret/portable_turret.dm
Labels: Tweak

#11344 Vampires: Dead and not loathing it
  hippiestation/code/datums/antagonists/vampire.dm
  hippiestation/code/game/gamemodes/vampire/vampire_powers.dm
Labels: Balance/Rebalance

#11443 You can now eat through headgear
  code/modules/reagents/reagent_containers.dm
Labels: Feature, Old Hippiestation Port

#11508 Spacemen no longer take a ritual bite out of an organ before inserting it during surgery
  code/modules/food_and_drinks/food/snacks.dm
Labels: Fix

#11520 Revolvers get a better reload sound
  hippiestation/code/modules/projectiles/guns/ballistic/revolver.dm
Labels: Sound

#11542 Fixes noir suit coat missing sprite
  icons/obj/clothing/suits.dmi
Labels: Fix, Sprites

#11554 fixes missing sprite
  icons/mob/suit.dmi
Labels: Sprites

#11356 Changes disabler damage from 26 to 39
  hippiestation/code/modules/projectiles/projectile/energy.dm
Labels: Fix

#11521 Removes Floorlength Bedhead
  code/modules/mob/dead/new_player/sprite_accessories.dm
  hippiestation.dme
Labels: Removal

#11610 Fixed a plasma man sprite
  icons/mob/uniform.dmi
Labels: Sprites

#11426 Vr cam fix
  _maps/RandomZLevels/VR/vrhub.dmm
Labels: Fix, Map Edit, Priority: High

#11614 Adds a nanosuit engaged announcement sound
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
  hippiestation/sound/misc/nanosuitengage.ogg
Labels: Fix, Sound
