Repository HippieStation/HippieStation, pull requests merged in 2019-07, with the labels that each got.

#11810 Reverts No-Slips and Thermals back to their 2015 state.
  code/modules/uplink/uplink_items.dm
  hippiestation.dme
  hippiestation/code/modules/clothing/glasses/glasses.dm
  hippiestation/code/modules/clothing/shoes/shoes.dm
  hippiestation/code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance, Revert

#11828 Cloning fix
  code/game/machinery/cloning.dm
  code/game/machinery/computer/cloning.dm
  hippiestation/code/game/machinery/computer/cloning.dm
Labels: Feature

#11825 Adds the Syndie-Lad to the game.
  code/_globalvars/lists/flavor_misc.dm
  code/datums/mind.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/modules/mob/living/carbon/human/examine.dm
  hippiestation.dme
  hippiestation/code/game/objects/items/syndielad.dm
  hippiestation/code/modules/clothing/gloves/gloves.dm
  hippiestation/icons/mob/actions/syndielad.dmi
  hippiestation/icons/obj/syndielad.dmi
Labels: Feature, Sprites, Tweak

#11829 Fuck include_mode()
  code/modules/uplink/uplink_items.dm
  hippiestation/code/modules/uplink/uplink_items.dm
Labels: Code Improvement, Refactor

#11830 :smug:
  hippiestation.dme
  hippiestation/code/modules/mob/living/carbon/human/emote.dm
  hippiestation/icons/mob/smug.dmi
Labels: Feature

#11800 Dominator no longer works if it's in a wall
  hippiestation/code/game/gamemodes/gangs/dominator.dm
Labels: +1, Balance/Rebalance

#11842 Sleeping no longer heals you out of crit
  hippiestation/code/datums/status_effects/debuffs.dm
Labels: Removal

#11854 Blacklists mutation toxins from vapor and chempiles to prevent botanist grief
  hippiestation/code/_globalvars/lists/typecache.dm
Labels: Removal

#11849 Fixes broken gun sprites [READY]
  code/modules/projectiles/boxes_magazines/_box_magazine.dm
  code/modules/projectiles/guns/ballistic/toy.dm
  hippiestation/code/modules/projectiles/guns/ballistic/automatic.dm
  hippiestation/code/modules/projectiles/guns/ballistic/toy.dm
  hippiestation/icons/obj/guns/toy.dmi
Labels: Fix, Needs Review, Ready for Review

#11843 Local headmin merges shitty and broken code, puts up testmerge to resolve it.
  hippiestation/code/datums/status_effects/debuffs.dm
Labels: Fix, Headmins approved

#11856 Gun gifts
  code/game/objects/items/gift.dm
Labels: Feature

#11851 Energy Based Weaponry Rework | Gauss Rifle [Awaiting-Merge] [OLDBASE-PORT] [Modular]
  hippiestation.dme
  hippiestation/code/game/objects/items/stacks/rods.dm
  hippiestation/code/game/objects/items/stunbaton.dm
  hippiestation/code/modules/power/cell.dm
  hippiestation/code/modules/projectiles/ammunition/energy.dm
  hippiestation/code/modules/projectiles/gun.dm
  hippiestation/code/modules/projectiles/guns/energy.dm
  hippiestation/code/modules/projectiles/guns/energy/energy_gun.dm
  hippiestation/code/modules/projectiles/guns/energy/laser.dm
  hippiestation/code/modules/projectiles/guns/energy/pulse.dm
  hippiestation/code/modules/projectiles/guns/energy/special.dm
  hippiestation/code/modules/projectiles/guns/energy/stun.dm
  hippiestation/code/modules/projectiles/projectile/beams.dm
  hippiestation/code/modules/research/designs/weapon_designs.dm
  hippiestation/code/modules/research/techweb/all_nodes.dm
  hippiestation/icons/mob/inhands/weapons/guns_lefthand.dmi
  hippiestation/icons/mob/inhands/weapons/guns_righthand.dmi
  hippiestation/icons/obj/ammo/ammo.dmi
  hippiestation/icons/obj/guns/energy.dmi
  hippiestation/icons/obj/projectiles.dmi
  hippiestation/sound/misc/heavysmash.ogg
  hippiestation/sound/weapons/railgun.ogg
Labels: Feature, Fix, Refactor, Sound, Sprites, Tweak, Work In Progress

#11798 Map edits to AI core, Turbine room, and grav generator
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Map Edit

#11853 Stops idiotic wizards with polymorph staff from extending the round
  code/modules/antagonists/xeno/xeno.dm
Labels: Tweak

#11844 Sepia timestop now makes the user immune
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
Labels: Tweak

#11869 Remove gauss rifle from science
  hippiestation/code/modules/research/designs/weapon_designs.dm
  hippiestation/code/modules/research/techweb/all_nodes.dm
Labels: Removal

#11872 Contender Fixes
  hippiestation/code/modules/projectiles/ammunition/magazines.dm
  hippiestation/code/modules/projectiles/guns/ballistic/shotgun.dm
Labels: Fix

#11873 Invisible Foam Force Shotgun and Double Barrel Shotguns Fix
  code/modules/projectiles/guns/ballistic.dm
  hippiestation/code/modules/projectiles/guns/ballistic/toy.dm
  hippiestation/icons/obj/guns/projectile.dmi
Labels: Fix

#11841 Lavaland atmos, but I cherry-picked it edition
  _maps/RandomRuins/LavaRuins/lavaland_biodome_beach.dmm
  _maps/RandomRuins/LavaRuins/lavaland_biodome_clown_planet.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_animal_hospital.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_biodome_winter.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_cultaltar.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_dead_ratvar.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_golem_ship.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_hermit.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_pizzaparty.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_swarmer_crash.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_ufo_crash.dmm
  code/__DEFINES/atmospherics.dm
  code/controllers/subsystem/air.dm
  code/datums/atmosphere/_atmosphere.dm
  code/datums/atmosphere/planetary.dm
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/hydroponics/grown/towercap.dm
  hippiestation.dme
  html/changelogs/AutoChangeLog-pr-44427.yml
  tgstation.dme
Labels: Map Edit

#11833 ZA WARUDO!
  code/__DEFINES/~hippie_defines/traits.dm
  code/modules/antagonists/wizard/equipment/spellbook.dm
  hippiestation.dme
  hippiestation/code/modules/antagonists/wizard/equipment/spellbook.dm
  hippiestation/code/modules/timestop/spell.dm
  hippiestation/code/modules/timestop/timestop.dm
  hippiestation/icons/effects/96x96.dmi
  hippiestation/icons/obj/projectiles.dmi
  hippiestation/sound/effects/S_JOT_00015.wav
  hippiestation/sound/effects/S_JOT_00016.wav
  hippiestation/sound/effects/S_JOT_00028.wav
  hippiestation/sound/effects/dzw-end.ogg
  hippiestation/sound/effects/dzw-success.ogg
  hippiestation/sound/effects/dzw.ogg
  hippiestation/sound/effects/spzw.ogg
Labels: Designer +2, Feature

#11881 CQC Relearning
  hippiestation/code/datums/martial/cqc.dm
Labels: Fix

#11882 Replace nukie's warm donks with a pinpointer
  code/game/gamemodes/nuclear/nuclear.dm
Labels: Feature
