Repository HippieStation/HippieStation, pull requests merged in 2019-08, with the labels that each got.

#11889 STEAMPOOOOOOOOORT
  code/modules/reagents/reagent_containers/spray.dm
Labels: Botched Mirror, STEAMPOOOORT

#11890 PYKOAI RETURNS
  code/__HELPERS/priority_announce.dm
  code/game/gamemodes/cult/ritual.dm
  code/game/gamemodes/extended/extended.dm
  code/game/gamemodes/game_mode.dm
  code/game/machinery/computer/communications.dm
  code/modules/admin/secrets.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/antagonists/blob/structures/core.dm
  code/modules/antagonists/cult/ritual.dm
  code/modules/events/blob.dm
  code/modules/events/disease_outbreak.dm
  code/modules/events/ion_storm.dm
  code/modules/events/meateor_wave.dm
  code/modules/events/meteor_wave.dm
  code/modules/events/wormholes.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/shuttle/emergency.dm
  code/modules/station_goals/station_goal.dm
  hippiestation/code/controllers/subsystem/shuttle.dm
  hippiestation/code/modules/shuttle/emergency.dm
  hippiestation/sound/pyko/WelcomeHippie.ogg
  hippiestation/sound/pyko/WelcomeUh.ogg
  hippiestation/sound/pyko/attention.ogg
  hippiestation/sound/pyko/catastrophic.ogg
  hippiestation/sound/pyko/commandreport.ogg
  hippiestation/sound/pyko/intercept.ogg
  hippiestation/sound/pyko/ionstorm.ogg
  hippiestation/sound/pyko/meteors.ogg
  hippiestation/sound/pyko/nukemanreport.ogg
  hippiestation/sound/pyko/outbreak5.ogg
  hippiestation/sound/pyko/outbreak7.ogg
  hippiestation/sound/pyko/shuttlecall.ogg
  hippiestation/sound/pyko/shuttlecallF.ogg
  hippiestation/sound/pyko/shuttledock.ogg
  hippiestation/sound/pyko/shuttleleave.ogg
  hippiestation/sound/pyko/shuttlerecall.ogg
  hippiestation/sound/pyko/spanomalies.ogg
  hippiestation/sound/pyko/very_bordt.ogg
  hippiestation/sound/pyko/who_the_fuck_just_recalled.ogg
Labels: Sound

#11891 Changes roundstart sounds to the ones before mirror (Vinesauce Vinny and Michael Rosen)
  code/controllers/subsystem/ticker.dm
  hippiestation/sound/ai/welcome1.ogg
  hippiestation/sound/ai/welcome2.ogg
Labels: Old Hippiestation Port, Sound

#11871 removes moth week
  code/modules/holiday/holidays.dm
Labels: 80 year old man eating ten bags of Cheetos

#11866 Adds a perfectly normal wife-beater
  hippiestation.dme
  hippiestation/code/modules/clothing/suits/misc.dm
  hippiestation/code/modules/vending/clothesmate.dm
  hippiestation/icons/mob/suit.dmi
  hippiestation/icons/obj/clothing/suits.dmi
  hippiestation/sound/voice/alpha1.ogg
  hippiestation/sound/voice/alpha2.ogg
  hippiestation/sound/voice/alpha3.ogg
  hippiestation/sound/voice/alpha4.ogg
Labels: Feature, Sound

#11883 Adds Sharplipium
  hippiestation/code/modules/reagents/chemistry/reagents/other_reagents.dm
  hippiestation/code/modules/reagents/chemistry/recipes/other.dm
Labels: Feature

#11895 makes the wife-beater's custom screams the same volume, if not slightly louder than regular screams
  hippiestation/sound/voice/alpha1.ogg
  hippiestation/sound/voice/alpha2.ogg
  hippiestation/sound/voice/alpha3.ogg
  hippiestation/sound/voice/alpha4.ogg
Labels: Tweak

#11893 ED209 recipe change
  code/modules/mob/living/simple_animal/bot/construction.dm
  code/modules/mob/living/simple_animal/bot/ed209bot.dm
Labels: Feature Request, Tweak

#11848 Holoparasite rework: build-a-bear edition
  _maps/RandomRuins/LavaRuins/lavaland_surface_stand.dmm
  _maps/RandomZLevels/Academy.dmm
  _maps/templates/pocket_dimension.dmm
  code/__DEFINES/~hippie_defines/components.dm
  code/__DEFINES/~hippie_defines/traits.dm
  code/_onclick/hud/guardian.dm
  code/game/atoms.dm
  code/game/gamemodes/meteor/meteors.dm
  code/game/machinery/cloning.dm
  code/game/machinery/doors/door.dm
  code/modules/antagonists/wizard/equipment/spellbook.dm
  code/modules/fields/timestop.dm
  code/modules/mob/living/simple_animal/guardian/types/ranged.dm
  code/modules/mob/mob.dm
  code/modules/modular_computers/laptop_vendor.dm
  code/modules/research/xenobiology/crossbreeding/_misc.dm
  code/modules/uplink/uplink_items.dm
  hippiestation.dme
  hippiestation/code/datums/mind.dm
  hippiestation/code/datums/ruins/lavaland.dm
  hippiestation/code/game/gamemodes/meteor/meteors.dm
  hippiestation/code/modules/guardian/abilities/_ability.dm
  hippiestation/code/modules/guardian/abilities/major/assassin.dm
  hippiestation/code/modules/guardian/abilities/major/explosive.dm
  hippiestation/code/modules/guardian/abilities/major/gravity.dm
  hippiestation/code/modules/guardian/abilities/major/healing.dm
  hippiestation/code/modules/guardian/abilities/major/scout.dm
  hippiestation/code/modules/guardian/abilities/major/time.dm
  hippiestation/code/modules/guardian/abilities/minor/snares.dm
  hippiestation/code/modules/guardian/abilities/minor/teleport.dm
  hippiestation/code/modules/guardian/abilities/special/absolution.dm
  hippiestation/code/modules/guardian/abilities/special/pocket.dm
  hippiestation/code/modules/guardian/abilities/special/time.dm
  hippiestation/code/modules/guardian/guardian.dm
  hippiestation/code/modules/guardian/guardianability.dm
  hippiestation/code/modules/guardian/guardianbuilder.dm
  hippiestation/code/modules/guardian/guardiandatum.dm
  hippiestation/code/modules/guardian/guardianstats.dm
  hippiestation/code/modules/guardian/standarrow.dm
  hippiestation/code/modules/mob/living/carbon/human/say.dm
  hippiestation/code/modules/mob/living/living.dm
  hippiestation/icons/mob/inhands/lefthand.dmi
  hippiestation/icons/mob/inhands/righthand.dmi
  hippiestation/icons/obj/items_and_weapons.dmi
  hippiestation/sound/effects/kingcrimson_end.ogg
  hippiestation/sound/effects/kingcrimson_start.ogg
  tgui/assets/tgui.css
  tgui/assets/tgui.js
  tgui/src/components/button.ract
  tgui/src/components/button.styl
  tgui/src/interfaces/guardian.ract
  tgui/src/styles/clockwork.styl
  tgui/src/styles/syndicate.styl
  tgui/src/tgui.styl
Labels: Do Not Merge, Feature, Map Edit, Removal, UI

#11909 Fix service buttons not working
  hippiestation/code/modules/antagonists/infiltrator/items/services.dm
Labels: Fix

#11907 Crab bans
  code/__DEFINES/~hippie_defines/admin.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/processing/quirks.dm
  code/game/gamemodes/game_mode.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/awaymissions/corpse.dm
  code/modules/client/preferences.dm
  hippiestation/code/controllers/subsystem/job.dm
  hippiestation/code/game/gamemodes/game_mode.dm
  hippiestation/code/modules/client/verbs/g2g.dm
  hippiestation/code/modules/jobs/job_types/job.dm
Labels: 80 year old man eating ten bags of Cheetos, Feature

#11918 Latejoin crabbans shouldn't get stuck at the menu anymore
  hippiestation/code/modules/jobs/job_types/job.dm
Labels: Fix

#11920 [s] Fix crabbans taking up actual job slots
  hippiestation/code/modules/mob/dead/new_player/new_player.dm
Labels: Fix

#11922 makes only one traitor per "create traitors" button press
  code/modules/admin/verbs/one_click_antag.dm
Labels: Tweak

#11904 Adds a GeoIP subsystem
  code/modules/admin/admin.dm
  config/hippiestation_config.txt
  hippiestation.dme
  hippiestation/SQL/brdetector.sql
  hippiestation/code/__HELPERS/unsorted.dm
  hippiestation/code/controllers/configuration/entries/hippiestation_config.dm
  hippiestation/code/controllers/subsystem/ipstack.dm
  hippiestation/code/modules/client/client_defines.dm
  hippiestation/code/modules/client/client_procs.dm
Labels: Administration, Config Update, SQL

#11929 You can no longer spam wizard apprentice/demons/nukeop reinforcements
  code/modules/antagonists/_common/antag_spawner.dm
Labels: Tweak

#11902 Chem dispenser supports negative macro values according to macroresolution
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Labels: Tweak

#11917 Build-a-stand stuff
  code/__DEFINES/role_preferences.dm
  code/modules/admin/sql_ban_system.dm
  hippiestation.dme
  hippiestation/code/modules/guardian/abilities/major/frenzy.dm
  hippiestation/code/modules/guardian/abilities/major/hand.dm
  hippiestation/code/modules/guardian/abilities/major/predator.dm
  hippiestation/code/modules/guardian/abilities/minor/teleport.dm
  hippiestation/code/modules/guardian/guardian.dm
  hippiestation/code/modules/guardian/guardianability.dm
  hippiestation/code/modules/guardian/guardianbuilder.dm
  hippiestation/code/modules/guardian/standarrow.dm
  hippiestation/icons/mob/actions.dmi
  hippiestation/sound/effects/vector_appear.ogg
  hippiestation/sound/effects/vector_rush.ogg
  hippiestation/sound/effects/zahando.ogg
Labels: Feature

#11927 Makes monkey dynamic rule cost shit
  hippiestation/code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Labels: Fix, STEAMPOOOORT

#11930 Fixes a mousetrap exploit involving click+dragging your backpack (or opening it) while stunned to instantly annihilate everyone around you
  code/modules/assembly/mousetrap.dm
Labels: Balance/Rebalance, Fix, In Game Exploit, Oversight

#11932 Fix syndie borg/reinforcements not working
  code/modules/antagonists/_common/antag_spawner.dm
Labels: Fix, STEAMPOOOORT

#11931 Dyanoomic fixes
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  html/changelogs/AutoChangeLog-pr-46027.yml
Labels: Fix

#11934 Fixes undeleted queries in GeoIP subsystem
  hippiestation/code/controllers/subsystem/ipstack.dm
Labels: STEAMPOOOORT

#11940 Update printer.dm
  hippiestation/code/modules/integrated_electronics/core/printer.dm
Labels: Fix, Priority: CRITICAL

#11943 fix chem dispenser precision
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Labels: Fix

#11925 makes chem puddles not appear where you draw
  code/game/objects/items/crayons.dm
Labels: Tweak

#11911 Nukie reinforcments can now choose a kit upon spawn
  hippiestation.dme
  hippiestation/code/modules/antagonists/_common/antag_spawner.dm
  hippiestation/code/modules/uplink/uplink_items.dm
Labels: Feature

#11947 fix NODEATH mobs from being able to whisper their way into death
  code/modules/mob/living/say.dm
Labels: Fix

#11953 Removes lings from dynamic
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Labels: Removal

#11951 Vending machines now give off a small amount of light
  hippiestation.dme
  hippiestation/code/modules/vending/_vending.dm
  hippiestation/code/modules/vending/assist.dm
  hippiestation/code/modules/vending/autodrobe.dm
  hippiestation/code/modules/vending/cartridge.dm
  hippiestation/code/modules/vending/cigarette.dm
  hippiestation/code/modules/vending/clothesmate.dm
  hippiestation/code/modules/vending/coffee.dm
  hippiestation/code/modules/vending/cola.dm
  hippiestation/code/modules/vending/engivend.dm
  hippiestation/code/modules/vending/megaseed.dm
  hippiestation/code/modules/vending/nutrimax.dm
  hippiestation/code/modules/vending/security.dm
  hippiestation/code/modules/vending/wardrobes.dm
Labels: Feature

#11965 fixes guardian potential
  hippiestation/code/modules/guardian/standarrow.dm
Labels: Fix

#11957 Badmin Gauntlet Update
  _maps/map_files/generic/CentCom.dmm
  _maps/templates/garden.dmm
  code/datums/components/stationloving.dm
  code/modules/antagonists/wizard/equipment/spellbook.dm
  code/modules/mob/living/bloodcrawl.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/say.dm
  code/modules/spells/spell_types/conjure.dm
  hippiestation.dme
  hippiestation/code/_onclick/hud/fullscreen.dm
  hippiestation/code/datums/mutations.dm
  hippiestation/code/game/objects/effects/landmarks.dm
  hippiestation/code/modules/antagonists/wizard/equipment/spellbook.dm
  hippiestation/code/modules/clothing/outfits/ert.dm
  hippiestation/code/modules/gauntlet/_stone.dm
  hippiestation/code/modules/gauntlet/clown.dm
  hippiestation/code/modules/gauntlet/farm.dm
  hippiestation/code/modules/gauntlet/gauntlet.dm
  hippiestation/code/modules/gauntlet/ghost.dm
  hippiestation/code/modules/gauntlet/syndie.dm
  hippiestation/icons/mob/screen_full.dmi
  hippiestation/sound/effects/SNAP.ogg
Labels: Balance/Rebalance, Feature, Fix, Map Edit, Removal, Sound, Sprites, Tweak

#11968 Update slime.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
Labels: Balance/Rebalance, Tweak
