Repository HippieStation/HippieStation, pull requests merged in 2019-10, with the labels that each got.

#12136 Fixes tasers not stunning
  code/modules/projectiles/projectile/energy/stun.dm
Labels: Fix, Priority: CRITICAL

#12132 Hacked cargo consoles sell contraband again
  code/modules/cargo/console.dm
Labels: Fix

#12133 Fixes a logging runtime for nooses
  hippiestation/code/game/objects/noose.dm
Labels: Fix

#12147 Fix tgui on IE8
  tgui/gulp/js.js
  tgui/package-lock.json
Labels: Fix, Requires tgui rebuild, UI

#12158 Indestructible objects don't explode from tesla
  code/game/machinery/_machinery.dm
Labels: Code Improvement

#12128 Adds the Auto-Doc Mark IX
  hippiestation.dme
  hippiestation/code/__HELPERS/unsorted.dm
  hippiestation/code/datums/components/storage/concrete/autodoc.dm
  hippiestation/code/game/machinery/autodoc.dm
  hippiestation/code/game/objects/items/circuitboards/machine_circuitboards.dm
  hippiestation/code/modules/research/designs/machine_designs.dm
  hippiestation/code/modules/research/stock_parts.dm
  hippiestation/code/modules/research/techweb/all_nodes.dm
  hippiestation/code/modules/surgery/autodoc_stuff.dm
  hippiestation/code/modules/surgery/surgery_step.dm
  hippiestation/icons/obj/machines/autodoc.dmi
  tgui/assets/tgui.css
  tgui/assets/tgui.js
  tgui/src/interfaces/autodoc.ract
Labels: Feature, UI

#12115 Buff devil
  code/modules/antagonists/devil/devil.dm
Labels: Balance/Rebalance

#12166 Fix the holoparasite barrier sprites
  hippiestation/code/modules/guardian/guardian.dm
Labels: Fix

#12168 Fixes some autodoc bugs
  hippiestation/code/game/machinery/autodoc.dm
Labels: Administration, Fix

#12097 No more dynamic ayys
  hippiestation/code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Labels: Removal

#12169 Fixes wrestling button sprites
  code/datums/martial/wrestling.dm
Labels: Fix

#12170 Auto-doc is no longer useless on augumented people
  hippiestation/code/game/machinery/autodoc.dm
Labels: Fix

#12180 Fix country flags
  hippiestation/code/modules/client/client_procs.dm
  hippiestation/icons/ooc_icons/countries.dmi
Labels: Fix

#12160 APC UI autoupdates properly
  code/modules/power/apc.dm
Labels: Fix

#12182 Summon guns/magic/etc actually no longer works on dynamic
  hippiestation/code/modules/antagonists/wizard/equipment/spellbook.dm
Labels: Fix

#12130 #11887 but remade (plate armor)
  hippiestation/code/modules/crafts/vest.dm
  hippiestation/icons/mob/head.dmi
  hippiestation/icons/mob/suit.dmi
  hippiestation/icons/obj/clothing/hats.dmi
  hippiestation/icons/obj/clothing/suits.dmi
Labels: Feature, Sprites

#12138 Threat marking goggles [READY]
  code/__DEFINES/~hippie_defines/atom_hud.dm
  code/datums/hud.dm
  code/modules/mob/living/carbon/examine.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/uplink/uplink_items.dm
  hippiestation.dme
  hippiestation/code/game/action.dm
  hippiestation/code/game/data_huds.dm
  hippiestation/code/modules/clothing/glasses/glasses.dm
  hippiestation/code/modules/mob/living/carbon/examine.dm
  hippiestation/code/modules/mob/living/carbon/human/human.dm
  hippiestation/code/modules/uplink/uplink_items.dm
Labels: Feature, Needs Review

#12193 [DNM] 513 support
  Dockerfile
  code/__DEFINES/misc.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/hud/plane_master.dm
Labels: Do Not Merge, ✋ Do Not Merge ✋

#12203 Pocket Dimension Rework
  _maps/templates/pocket_dimension.dmm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/living.dm
  hippiestation/code/modules/guardian/abilities/special/pocket.dm
  hippiestation/code/modules/guardian/guardian.dm
  hippiestation/code/modules/timestop/timestop.dm
Labels: Feature, Map Edit

#12185 Adds a new brain trauma line
  strings/traumas.json
Labels: Feature

#12216 Fixes pocket dimension things
  _maps/templates/pocket_dimension.dmm
  hippiestation/code/modules/guardian/abilities/special/pocket.dm
Labels: Map Edit

#12199 Give more information about zombie infected patients
  code/game/objects/items/devices/scanners.dm
Labels: Feature

#12175 Craftable Rubber Ducks.
  code/modules/research/designs/misc_designs.dm
  hippiestation/code/modules/research/techweb/all_nodes.dm
Labels: Feature

#12167 Silicons can now see blood runes and daggers
  code/modules/antagonists/cult/cult_items.dm
  code/modules/antagonists/cult/runes.dm
Labels: Tweak

#11995 Nanosuit can now be emagged [READY]
  hippiestation.dme
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
  hippiestation/code/modules/mob/inventory.dm
Labels: Balance/Rebalance, Feature, Fix, Needs Review, Removal, Tweak
