Repository HippieStation/HippieStation, pull requests merged in 2019-02, with the labels that each got.

#10533 Fixes player previews and some other skin.dmf stuff
  code/modules/client/preferences.dm
  hippiestation/code/modules/mob/living/carbon/human/human.dm
  hippiestation/interface/skin.dmf
Labels: Fix

#10565 fixes a config entry
  code/controllers/configuration/entries/general.dm
Labels: Config Update

#10561 fixes the help_verb runtime in Nanosuit
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Code Improvement

#10583 Fixes invisible mass driver
  hippiestation/code/game/machinery/computer/_computer.dm
Labels: Fix

#10591 Fixes clown shoes and suit not playing sounds
  hippiestation.dme
  hippiestation/code/datums/outputs.dm
  hippiestation/code/modules/clothing/under/jobs/civilian.dm
Labels: Fix

#10598 Properly fixes chapel mass driver computer being invisible
  _maps/map_files/HippieStation/hippiestation.dmm
  hippiestation/code/game/machinery/computer/_computer.dm
Labels: Map Edit

#10624 fix admin-made infiltrator teams not having objectives
  hippiestation/code/modules/admin/verbs/one_click_antag.dm
Labels: Fix

#10572 Removed mindshielded midround antags
  code/game/gamemodes/game_mode.dm
Labels: Fix

#10617 Reduces blood cost for a large amount of vamp abilities
  hippiestation/code/game/gamemodes/vampire/vampire_powers.dm
Labels: Balance/Rebalance

#10187 [DNM] Deathsquad buffing
  hippiestation.dme
  hippiestation/code/datums/martial/elite_cqc.dm
  hippiestation/code/game/objects/items/implants/implant_explosive.dm
  hippiestation/code/game/objects/items/shields.dm
  hippiestation/code/modules/clothing/outfits/standard.dm
  hippiestation/code/modules/clothing/spacesuits/hardsuit.dm
Labels: +2, Do Not Merge

#10216 [Ready] Adding Selfchanging Assemblies
  hippiestation/code/modules/integrated_electronics/subtypes/manipulation.dm
Labels: Feature, Needs Review

#10636 Fixes ducking travis runtimes
  hippiestation/code/datums/outputs.dm
Labels: Fix

#10497 Makes buying Wiz spells not a complete gamble.
  hippiestation/code/modules/antagonists/wizard/equipment/spellbook.dm
Labels: Feature

#10649 No Valentines day allowed
  hippiestation/code/modules/events/holiday/vday.dm
Labels: Tweak

#10679 no more fucking spam autobans for kicking the shit outta someone
  hippiestation/code/datums/martial/armstrong.dm
Labels: Fix

#10681 Bone hurting juice won't ban you anymore
  hippiestation/code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Fix

#10680 Fixes chef cqc working outside kitchen
  hippiestation/code/datums/martial/elite_cqc.dm
Labels: Fix

#10225 [READY]Circuitry Copyright Agreement Of 2018 (make circuits id-lockable and sealable)
  hippiestation/code/modules/integrated_electronics/core/analyzer.dm
  hippiestation/code/modules/integrated_electronics/core/assemblies.dm
  hippiestation/code/modules/integrated_electronics/core/debugger.dm
  hippiestation/code/modules/integrated_electronics/core/printer.dm
Labels: Needs Review, Tweak

#10697 Removes Thrower circuit
  hippiestation/code/modules/integrated_electronics/subtypes/manipulation.dm
Labels: Removal

#10657 Separated chems have a 10% spawn chance
  hippiestation/code/modules/hydroponics/grown/berries.dm
Labels: Balance/Rebalance

#10629 Nanosuit can now tac reload in speed and light step with cloak
  code/__DEFINES/~hippie_defines/traits.dm
  code/modules/projectiles/guns/ballistic.dm
  hippiestation.dme
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Feature

#10715 A Fix for Invisible Cardboard Boxes
  hippiestation/code/modules/paperwork/photography.dm
Labels: Fix

#10698 Adds healing while asleep
  hippiestation.dme
  hippiestation/code/datums/status_effects/debuffs.dm
Labels: Feature, Needs Head Input

#10687 you can now use 50 units of mutagen to mutate plant species
  hippiestation.dme
  hippiestation/code/modules/hydroponics/hydroponics.dm
Labels: Removal

#10717 Removes ayy and syndie tech for advanced nanites, but multiplies their price by 10
  code/modules/research/techweb/all_nodes.dm
Labels: Feature, Removal

#10752 Reduces the price of combat and hazard nanites slightly, and adds adrenaline burst under combat nanites
  code/modules/research/designs/nanite_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Balance/Rebalance, Feature

#10756 Revert "Reduces the price of combat and hazard nanites slightly, and adds adrenaline burst under combat nanites"
  code/modules/research/designs/nanite_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Revert
