Repository HippieStation/HippieStation, pull requests merged in 2019-12, with the labels that each got.

#12343 removes bees, adds bee crate to botany
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Feature, Map Edit, Removal

#12378 Catbeasts are now hurt by chocolate
  code/modules/mob/living/carbon/human/species_types/felinid.dm
Labels: Feature

#12285 Replaces rusty toolbox sprite with Punkinguy's #12245
  icons/obj/storage.dmi
Labels: Sprites

#12371 Removes lizards having a heat resistance and also makes Toxic go on a soyrage
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
Labels: Removal

#12374 Hiveminds now require 20 players in dynamic
  hippiestation/code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Labels: Tweak

#12366 makeshift laser rifle
  hippiestation/code/datums/components/crafting/recipes.dm
  hippiestation/code/modules/projectiles/guns/energy/laser.dm
  hippiestation/icons/mob/inhands/weapons/guns_lefthand.dmi
  hippiestation/icons/mob/inhands/weapons/guns_righthand.dmi
  hippiestation/icons/obj/guns/energy.dmi
Labels: Feature

#12384 Removes useless documentation generator
  .travis.yml
Labels: Removal

#12381 Winter is coming
  code/modules/admin/secrets.dm
  hippiestation.dme
  hippiestation/code/modules/admin/secrets.dm
  hippiestation/code/modules/events/winter.dm
Labels: Administration, Feature, Headmins approved

#12311 Scrake zombie species event [READY]
  hippiestation.dme
  hippiestation/code/modules/clothing/scrake.dm
  hippiestation/code/modules/events/scrake.dm
  hippiestation/code/modules/mob/living/carbon/human/species_types/scrake.dm
  hippiestation/code/modules/uplink/uplink_items.dm
  hippiestation/sound/creatures/SawIdle.ogg
  hippiestation/sound/creatures/ScrakeGiggle.ogg
  hippiestation/sound/creatures/ScrakeVoice1.ogg
  hippiestation/sound/creatures/ScrakeVoice2.ogg
  hippiestation/sound/creatures/ScrakeVoice3.ogg
  hippiestation/sound/creatures/ScrakeVoice4.ogg
  hippiestation/sound/creatures/ScrakeVoice7.ogg
  hippiestation/sound/creatures/ScrakeVoice8.ogg
  hippiestation/sound/creatures/ZombieDie2.ogg
  hippiestation/sound/creatures/zombiegrowl1.ogg
Labels: Feature, Needs Review

#12385 Fixes ghosts ctrl-click on autodoc
  hippiestation/code/game/machinery/autodoc.dm
Labels: Fix

#12382 Port /tg/'s VV/trait refactor
  code/__DEFINES/traits.dm
  code/__DEFINES/vv.dm
  code/__DEFINES/~hippie_defines/vv.dm
  code/__HELPERS/type_processing.dm
  code/_globalvars/traits.dm
  code/controllers/subsystem/input.dm
  code/datums/datumvars.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/objects/objs.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/callproc/callproc.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/admin/view_variables/admin_delete.dm
  code/modules/admin/view_variables/debug_variables.dm
  code/modules/admin/view_variables/get_variables.dm
  code/modules/admin/view_variables/mark_datum.dm
  code/modules/admin/view_variables/mass_edit_variables.dm
  code/modules/admin/view_variables/modify_variables.dm
  code/modules/admin/view_variables/topic.dm
  code/modules/admin/view_variables/topic_basic.dm
  code/modules/admin/view_variables/topic_list.dm
  code/modules/admin/view_variables/view_variables.dm
  code/modules/events/spacevine.dm
  code/modules/keybindings/bindings_atom.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  hippiestation.dme
  hippiestation/code/modules/mob/living/carbon/human/human.dm
  tgstation.dme
Labels: Config Update, Refactor

#12272 Scientists now randomly burst into flames
  code/__DEFINES/~hippie_defines/traits.dm
  code/game/machinery/_machinery.dm
  code/game/mecha/mech_fabricator.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/research/machinery/_production.dm
  hippiestation/code/__HELPERS/game.dm
Labels: Code Improvement, Designer +3, Feature, Headmins approved

#12365 Initial dwarf commit (Sprint 1)
  code/__DEFINES/~hippie_defines/mobs.dm
  code/modules/mob/living/carbon/human/species.dm
  hippiestation.dme
  hippiestation/code/modules/language/dwarven.dm
  hippiestation/code/modules/mob/living/carbon/human/species_types/dwarves.dm
  hippiestation/code/modules/mob/living/carbon/human/update_icons.dm
  hippiestation/code/modules/surgery/organs/lungs.dm
  hippiestation/code/modules/surgery/organs/tongue.dm
  hippiestation/icons/misc/language.dmi
  hippiestation/icons/mob/mutant_bodyparts.dmi
Labels: Do Not Merge

#12396 Dwarf Sprint 1 finishing touches: I do it for free edition
  hippiestation.dme
  hippiestation/code/__HELPERS/names.dm
  hippiestation/code/_globalvars/lists/names.dm
  hippiestation/code/game/objects/items/tanks/tank_types.dm
  hippiestation/code/game/objects/structures/mirror.dm
  hippiestation/code/modules/clothing/outfits/dwarf.dm
  hippiestation/code/modules/clothing/shoes/shoes.dm
  hippiestation/code/modules/clothing/under/dwarf.dm
  hippiestation/code/modules/mob/living/carbon/human/species_types/dwarves.dm
  hippiestation/icons/mob/belt.dmi
  hippiestation/icons/mob/feet.dmi
  hippiestation/icons/mob/inhands/lefthand.dmi
  hippiestation/icons/mob/inhands/righthand.dmi
  hippiestation/icons/mob/mutant_bodyparts.dmi
  hippiestation/icons/mob/uniform.dmi
  hippiestation/icons/obj/clothing/shoes.dmi
  hippiestation/icons/obj/clothing/uniforms.dmi
  hippiestation/icons/obj/tank.dmi
  hippiestation/strings/names/dwarf_first.txt
  hippiestation/strings/names/dwarf_last.txt
Labels: Administration, Feature, Headmins approved, Review Before Merging

#12383 Change taskbar icon to Hippie logo
  hippiestation/interface/skin.dmf
Labels: Sprites

#12373 Abductors now has a minimum playercount of 20
  hippiestation/code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Labels: Tweak

#12379 Allows heads of staff to just connect to other holopads, rather than call
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/HippieStation/hippiestation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/datums/holocall.dm
  code/game/machinery/hologram.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
Labels: Feature, Map Edit, Tweak

#12394 Scrake announcement + nerfs
  hippiestation/code/modules/clothing/scrake.dm
  hippiestation/code/modules/events/scrake.dm
  hippiestation/code/modules/mob/living/carbon/human/species_types/scrake.dm
Labels: Balance/Rebalance, Feature

#12391 Port customizable keybinds from /tg/
  code/__DEFINES/admin.dm
  code/__HELPERS/cmp.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/sanitize_values.dm
  code/_globalvars/lists/client.dm
  code/_globalvars/lists/keybindings.dm
  code/controllers/subsystem/input.dm
  code/datums/keybinding/_defines.dm
  code/datums/keybinding/_keybindings.dm
  code/datums/keybinding/admin.dm
  code/datums/keybinding/carbon.dm
  code/datums/keybinding/client.dm
  code/datums/keybinding/emote.dm
  code/datums/keybinding/human.dm
  code/datums/keybinding/living.dm
  code/datums/keybinding/mob.dm
  code/datums/keybinding/movement.dm
  code/datums/keybinding/robot.dm
  code/modules/admin/secrets.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/keybindings/bindings_admin.dm
  code/modules/keybindings/bindings_atom.dm
  code/modules/keybindings/bindings_carbon.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/keybindings/bindings_human.dm
  code/modules/keybindings/bindings_living.dm
  code/modules/keybindings/bindings_mob.dm
  code/modules/keybindings/bindings_robot.dm
  code/modules/keybindings/setup.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/say.dm
  hippiestation.dme
  hippiestation/code/datums/keybinding/admin.dm
  hippiestation/code/modules/client/preferences.dm
  hippiestation/code/modules/keybindings/bindings_client.dm
  hippiestation/code/modules/keybindings/bindings_hippie.dm
  hippiestation/code/modules/keybindings/bindings_mentor.dm
  hippiestation/code/modules/mob/emote.dm
  hippiestation/code/modules/mob/living/carbon/human/emote.dm
  hippiestation/code/modules/mob/living/emote.dm
  hippiestation/interface/interface.dm
  hippiestation/interface/skin.dmf
  interface/interface.dm
  interface/skin.dmf
  tgstation.dme
Labels: Feature

#12398 Makes snacks, cola cheaper, buffs IED
  hippiestation/code/game/objects/items/grenades/ghettobomb.dm
  hippiestation/code/modules/vending/cola.dm
  hippiestation/code/modules/vending/snack.dm
Labels: Balance/Rebalance

#12407 patches BZ canister infinite money exploit [speedmerge]
  hippiestation/code/modules/cargo/packs.dm
Labels: Fix

#12410 Adds old hippie space funeral mobs
  code/modules/mob/living/simple_animal/hostile/retaliate/spacefuneral.dm
  icons/mob/spacefuneral.dmi
  sound/weapons/leghorse.ogg
  sound/weapons/philip.ogg
Labels: Feature, Sound, Sprites

#12413 Y E E T
  code/modules/projectiles/guns/ballistic/revolver.dm
  hippiestation/code/modules/projectiles/gun.dm
Labels: Feature

#12408 Adds random parallax layers
  code/_onclick/hud/parallax.dm
  code/controllers/subsystem/parallax.dm
  icons/effects/parallax.dmi
Labels: Feature, Sprites

#12271 Suit Sensors start on [Bounty from Higitus!]
  hippiestation/code/modules/clothing/under.dm
Labels: Balance/Rebalance, Do Not Merge, Tweak

#12344 [REVERT/PORT]Reverts TG #28851 - Removal Of Cortical Borers
  code/_compile_options.dm
  hippiestation.dme
  hippiestation/code/game/gamemodes/miniantags/borer/borer.dm
  hippiestation/code/game/gamemodes/miniantags/borer/borer_chemicals.dm
  hippiestation/code/game/gamemodes/miniantags/borer/borer_events.dm
  hippiestation/code/game/gamemodes/miniantags/borer/borer_html.dm
  hippiestation/code/game/gamemodes/miniantags/borer/borer_topic.dm
  icons/mob/animal.dmi
Labels: Feature, Revert, Sprites

#12415 Port nanite changes from /tg/
  code/__DEFINES/combat.dm
  code/__DEFINES/components.dm
  code/__DEFINES/nanites.dm
  code/__DEFINES/research.dm
  code/__DEFINES/~hippie_defines/nanites.dm
  code/controllers/subsystem/processing/nanites.dm
  code/datums/components/nanites.dm
  code/datums/mood_events/generic_negative_events.dm
  code/datums/mood_events/generic_positive_events.dm
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/simple_animal/slime/powers.dm
  code/modules/research/designs/nanite_designs.dm
  code/modules/research/nanites/extra_settings/_extra_setting.dm
  code/modules/research/nanites/extra_settings/boolean.dm
  code/modules/research/nanites/extra_settings/number.dm
  code/modules/research/nanites/extra_settings/text.dm
  code/modules/research/nanites/extra_settings/type.dm
  code/modules/research/nanites/nanite_chamber.dm
  code/modules/research/nanites/nanite_chamber_computer.dm
  code/modules/research/nanites/nanite_cloud_controller.dm
  code/modules/research/nanites/nanite_hijacker.dm
  code/modules/research/nanites/nanite_program_hub.dm
  code/modules/research/nanites/nanite_programmer.dm
  code/modules/research/nanites/nanite_programs.dm
  code/modules/research/nanites/nanite_programs/buffing.dm
  code/modules/research/nanites/nanite_programs/healing.dm
  code/modules/research/nanites/nanite_programs/sensor.dm
  code/modules/research/nanites/nanite_programs/suppression.dm
  code/modules/research/nanites/nanite_programs/utility.dm
  code/modules/research/nanites/nanite_programs/weapon.dm
  code/modules/research/nanites/nanite_remote.dm
  code/modules/research/nanites/program_disks.dm
  code/modules/research/nanites/public_chamber.dm
  code/modules/research/nanites/rules.dm
  code/modules/research/techweb/__techweb_helpers.dm
  code/modules/research/techweb/all_nodes.dm
  hippiestation.dme
  hippiestation/code/datums/components/nanites.dm
  hippiestation/code/modules/research/nanites/nanite_programs.dm
  hippiestation/code/modules/research/nanites/nanite_programs/sensor.dm
  icons/mob/actions/actions_items.dmi
  tgstation.dme
  tgui-next/README.md
  tgui-next/packages/tgui/components/Input.js
  tgui-next/packages/tgui/components/index.js
  tgui-next/packages/tgui/interfaces/NaniteCloudControl.js
  tgui-next/packages/tgui/interfaces/NaniteRemote.js
  tgui-next/packages/tgui/public/tgui.bundle.css
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/packages/tgui/routes.js
  tgui-next/packages/tgui/styles/components/Dropdown.scss
  tgui-next/packages/tgui/styles/components/NumberInput.scss
  tgui-next/packages/tgui/styles/main.scss
  tgui/assets/tgui.css
  tgui/assets/tgui.js
  tgui/src/interfaces/nanite_chamber_control.ract
  tgui/src/interfaces/nanite_cloud_control.ract
  tgui/src/interfaces/nanite_programmer.ract
Labels: Balance/Rebalance, Feature, Removal, Sprites, Tweak, UI

#12416 Moves detective office beside lawyers
  _maps/map_files/HippieStation/hippiestation.dmm
  hippiestation.dme
Labels: Balance/Rebalance, Feature, Map Edit, Tweak

#12360 Ports the luxury bar survival pod from TG
  _maps/templates/shelter_3.dmm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/mining/machine_vending.dm
  code/modules/mining/shelters.dm
Labels: Feature, Map Edit

#12419 Fixes APC namestring + other stuff
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Fix, Map Edit

#12427 No more emote keybinds!
  code/_globalvars/lists/keybindings.dm
  hippiestation.dme
  hippiestation/code/datums/keybinding/emote.dm
  hippiestation/code/modules/mob/emote.dm
  hippiestation/code/modules/mob/living/carbon/human/emote.dm
  hippiestation/code/modules/mob/living/emote.dm
Labels: Removal

#12429 Tgui next updates
  .github/workflows/autobuild_tgui.yml
  code/modules/atmospherics/machinery/portable/pump.dm
  code/modules/atmospherics/machinery/portable/scrubber.dm
  tgui-next/package.json
  tgui-next/packages/common/collections.js
  tgui-next/packages/common/vector.js
  tgui-next/packages/tgui-dev-server/link/client.js
  tgui-next/packages/tgui-dev-server/link/server.js
  tgui-next/packages/tgui/backend.js
  tgui-next/packages/tgui/components/TitleBar.js
  tgui-next/packages/tgui/drag.js
  tgui-next/packages/tgui/interfaces/Gps.js
  tgui-next/packages/tgui/interfaces/PortableAtmos.js
  tgui-next/packages/tgui/package.json
  tgui-next/packages/tgui/public/tgui.bundle.css
  tgui-next/packages/tgui/public/tgui.bundle.js
  tgui-next/packages/tgui/routes.js
  tgui-next/packages/tgui/styles/components/TitleBar.scss
  tgui-next/yarn.lock
Labels: GitHub, UI

#12426 dream update
  strings/dreamstrings.txt
Labels: Feature

#12423 new sprite for makeshift laser rifle thanks gorram_swangs #12421
  hippiestation/icons/obj/guns/energy.dmi
Labels: Sprites

#12422 Immensely speeds up explosion code [READY]
  code/datums/explosion.dm
  code/game/objects/obj_defense.dm
  code/modules/atmospherics/environmental/LINDA_fire.dm
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Candidate for Testmerge, Code Improvement, Needs Review, Performance, Tweak

#12433 Hacking vending machines now makes the product free
  hippiestation/code/modules/vending/_vending.dm
  tgui-next/packages/tgui/interfaces/Vending.js
  tgui-next/packages/tgui/public/tgui.bundle.js
Labels: Feature, UI

#12223 Superboom Changes (N-amino)
  hippiestation/code/modules/reagents/chemistry/reagents/pyrotechnic_reagents.dm
Labels: Tweak

#12432 handpressed paper
  hippiestation/code/modules/crafts/weaponry.dm
Labels: Tweak

#12224 [REVIEW HEAVILY] SCP 173, 999 and 294
  hippiestation.dme
  hippiestation/code/init.dm
  hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
  hippiestation/code/modules/SCPmodular/scps/euclid/SCP-294.dm
  hippiestation/code/modules/SCPmodular/scps/safe/scp999.dm
  hippiestation/code/modules/SCPmodular/spcicon/scpobj/scp.dmi
  hippiestation/code/modules/SCPmodular/spcicon/scpobj/scp294.dmi
  hippiestation/icons/mob/scpicon/scpmobs/32x64.dmi
  hippiestation/icons/mob/scpicon/scpmobs/SCP-131.dmi
  hippiestation/icons/mob/scpicon/scpmobs/cage.dmi
  hippiestation/icons/mob/scpicon/scpmobs/item.dmi
  hippiestation/icons/mob/scpicon/scpmobs/josie.dmi
  hippiestation/icons/mob/scpicon/scpmobs/scp-173.dmi
  hippiestation/icons/mob/scpicon/scpmobs/scp-999.dmi
  hippiestation/icons/mob/scpicon/scpmobs/scp012.dmi
  hippiestation/icons/mob/scpicon/scpmobs/scp049.dmi
  hippiestation/icons/mob/scpicon/scpmobs/scp106.dmi
  hippiestation/icons/mob/scpicon/scpobj/scp.dmi
  hippiestation/icons/mob/scpicon/scpobj/scp294.dmi
  hippiestation/sound/scpsounds/scp/012.ogg
  hippiestation/sound/scpsounds/scp/chase/scp106chase.ogg
  hippiestation/sound/scpsounds/scp/machinery/femur_breaker.ogg
  hippiestation/sound/scpsounds/scp/machinery/femur_breaker_success.ogg
  hippiestation/sound/scpsounds/scp/spook/Bell2.ogg
  hippiestation/sound/scpsounds/scp/spook/Bell3.ogg
  hippiestation/sound/scpsounds/scp/spook/NeckSnap1.ogg
  hippiestation/sound/scpsounds/scp/spook/NeckSnap3.ogg
  hippiestation/sound/scpsounds/scp/voice/SCP049_1.ogg
  hippiestation/sound/scpsounds/scp/voice/SCP049_2.ogg
  hippiestation/sound/scpsounds/scp/voice/SCP049_3.ogg
  hippiestation/sound/scpsounds/scp/voice/SCP049_4.ogg
  hippiestation/sound/scpsounds/scp/voice/SCP049_5.ogg
Labels: Feature

#12436 Bug Fixes
  code/modules/hydroponics/gene_modder.dm
  hippiestation/code/modules/detectivework/footprints_and_rag.dm
  hippiestation/code/modules/integrated_electronics/subtypes/smart.dm
  hippiestation/code/modules/surgery/organs/tongue.dm
Labels: Fix

#12435 removes a MLP reference [is #12431]
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
Labels: Fix, Removal

#12438 Adds size check to explosion
  code/datums/explosion.dm
Labels: Code Improvement

#12441 Reverts the explosion MC shit
  code/datums/explosion.dm
Labels: Candidate for Testmerge, Revert

#12444 Revert "Reverts the explosion MC shit"
  code/datums/explosion.dm
Labels: Revert

#12439 Conveyor belt performance
  code/modules/recycling/conveyor2.dm
Labels: Code Improvement, Performance

#12449 Fixes pool breaking when cutting wires
  hippiestation/code/modules/pool/pool_controller.dm
Labels: Fix

#12145 Freon but I made it cooler [READY]
  code/__HELPERS/icons.dm
  code/game/turfs/open.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/atmospherics/machinery/portable/portable_atmospherics.dm
  code/modules/power/supermatter/supermatter.dm
  hippiestation.dme
  hippiestation/code/game/turfs/turf.dm
  hippiestation/code/modules/atmospherics/gasmixtures/gas_types.dm
  hippiestation/code/modules/atmospherics/gasmixtures/reactions.dm
  hippiestation/code/modules/atmospherics/machinery/portable/canister.dm
  hippiestation/code/modules/atmospherics/machinery/portable/other/miner.dm
  hippiestation/code/modules/cargo/packs.dm
Labels: Feature, Needs Review, Old Hippiestation Port

#12450 Explosion signal
  code/__DEFINES/components.dm
  code/datums/explosion.dm
  code/game/machinery/doppler_array.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
  hippiestation/code/modules/clothing/suits/utility.dm
Labels: Code Improvement

#12461 Field generator no longer alerts of loose singulo from BOH realm
  code/modules/power/singularity/field_generator.dm
Labels: Tweak

#12386 Christmas theme map generator [WIP]
  hippiestation.dme
  hippiestation/code/modules/procedural_mapping/mapGenerators/christmas.dm
Labels: Feature, Work In Progress

#12471 Fix vending machine UIs not autoclosing
  hippiestation/code/modules/vending/_vending.dm
Labels: Fix

#12465 Converts all HTML windows to support UTF-8 encoding
  code/__DEFINES/misc.dm
  code/datums/browser.dm
  code/datums/datacore.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/pipe/pipe_dispenser.dm
  code/game/machinery/telecomms/machine_interactions.dm
  code/game/machinery/telecomms/machines/message_server.dm
  code/game/mecha/combat/honker.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/mecha/mech_fabricator.dm
  code/game/mecha/mecha_control_console.dm
  code/game/mecha/mecha_topic.dm
  code/game/objects/items/blueprints.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/storage/book.dm
  code/game/objects/structures/noticeboard.dm
  code/game/objects/structures/safe.dm
  code/modules/admin/admin.dm
  code/modules/admin/check_antagonists.dm
  code/modules/admin/outfits.dm
  code/modules/admin/permissionedit.dm
  code/modules/admin/player_panel.dm
  code/modules/admin/stickyban.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/beakerpanel.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/admin/view_variables/view_variables.dm
  code/modules/antagonists/wizard/equipment/spellbook.dm
  code/modules/client/verbs/ooc.dm
  code/modules/events/holiday/vday.dm
  code/modules/mining/machine_silo.dm
  code/modules/mob/dead/new_player/poll.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/pai/software.dm
  code/modules/paperwork/filingcabinet.dm
  code/modules/paperwork/paper.dm
  code/modules/photography/photos/photo.dm
  hippiestation/code/game/gamemodes/miniantags/borer/borer_html.dm
  hippiestation/code/game/machinery/computer/arcade.dm
  hippiestation/code/game/objects/items/manuals.dm
  hippiestation/code/modules/events/holiday/vday.dm
  hippiestation/code/modules/integrated_electronics/core/assemblies.dm
  hippiestation/code/modules/integrated_electronics/core/integrated_circuit.dm
Labels: 513 Prep

#12470 Juggernaut
  code/__DEFINES/traits.dm
  hippiestation.dme
  hippiestation/code/game/objects/items/juggernaut.dm
  hippiestation/code/modules/mob/living/living.dm
  hippiestation/code/modules/uplink/uplink_items.dm
  hippiestation/icons/mob/head.dmi
Labels: Feature

#12472 Revert "Juggernaut"
  code/__DEFINES/traits.dm
  hippiestation.dme
  hippiestation/code/game/objects/items/juggernaut.dm
  hippiestation/code/modules/mob/living/living.dm
  hippiestation/code/modules/uplink/uplink_items.dm
  hippiestation/icons/mob/head.dmi
Labels: Revert

#12414 It's just a box
  code/game/objects/items/implants/implant_stealth.dm
  code/game/objects/structures/crates_lockers/closets/cardboardbox.dm
  hippiestation/code/modules/uplink/uplink_items.dm
Labels: Balance/Rebalance, Fix, Tweak

#12440 Phoneposted 294 chemical name changes
  hippiestation/code/modules/SCPmodular/scps/euclid/SCP-294.dm
Labels: Tweak

#12462 Fixes pAI host scan
  code/modules/mob/living/silicon/pai/software.dm
Labels: Fix

#12400 Tasertron, the Great Dabbening Weapon
  code/modules/projectiles/guns/energy/special.dm
  hippiestation/code/modules/crafts/weaponry.dm
  hippiestation/icons/mob/inhands/weapons/lefthand_tasertron.dmi
  hippiestation/icons/mob/inhands/weapons/righthand_tasertron.dmi
  icons/obj/tasertron.dmi
Labels: Feature, Sprites

#12480 Tasertron sprite
  hippiestation/icons/obj/tasertron.dmi
Labels: Sprites

#12466 Freon Formation
  hippiestation/code/modules/atmospherics/gasmixtures/reactions.dm
Labels: Feature

#12486 Fixes supermatter AC. Keeps max subtract below current power. (#47943)
  code/modules/power/supermatter/supermatter.dm
  html/changelogs/AutoChangeLog-pr-47943.yml
Labels: Atmospherics, Fix

#12489 Change SQL files to use utf8mb4
  SQL/tgstation_schema.sql
  SQL/tgstation_schema_prefixed.sql
  hippiestation/SQL/brdetector.sql
  hippiestation/SQL/donator.sql
  hippiestation/SQL/mentor.sql
Labels: SQL

#12490 More tg fixes
  code/datums/diseases/advance/advance.dm
  code/game/gamemodes/objective.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/constructable_frame.dm
  code/game/objects/items/devices/desynchronizer.dm
  code/modules/antagonists/swarmer/swarmer.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/research/nanites/nanite_programs/healing.dm
  hippiestation/code/modules/mob/living/simple_animal/floor_cluwne.dm
  hippiestation/code/modules/reagents/reagent_dispenser.dm
Labels: Code Improvement, Fix

#12485 Funny suicide from /tg/
  code/game/objects/items/tanks/tanks.dm
  code/modules/mob/living/carbon/death.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  html/changelogs/AutoChangeLog-pr-47714.yml
Labels: Feature

#12475 Removes hygiene for real
  code/modules/mob/living/carbon/human/life.dm
Labels: Removal
