Repository HippieStation/HippieStation, pull requests merged in 2019-09, with the labels that each got.

#11971 ERTs no longer stop the round from ending
  hippiestation/code/modules/antagonists/ert/ert.dm
Labels: Fix

#11926 Adds country flags to OOC
  hippiestation/code/modules/client/client_procs.dm
  hippiestation/icons/ooc_icons/countries.dmi
Labels: Feature

#11985 Midround abductors shouldn't be spammed anymore
  hippiestation/code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
Labels: Fix

#11976 Adds an ending cinematic after THE SNAP happens
  code/__DEFINES/cinematics.dm
  hippiestation.dme
  hippiestation/code/datums/cinematic.dm
  hippiestation/code/modules/gauntlet/gauntlet.dm
  hippiestation/icons/effects/station_explosion.dmi
  hippiestation/icons/mob/screen_full.dmi
  hippiestation/sound/misc/theend.ogg
Labels: Feature

#11982 Shuttle refuel delay is now 30 minutes during thanus
  hippiestation/code/modules/gauntlet/gauntlet.dm
Labels: Tweak

#11978 Buffs golden apples
  hippiestation.dme
  hippiestation/code/modules/hydroponics/grown/apple.dm
Labels: Feature

#11973 Shooting certain weapons with a Range F guardian is no longer suicide
  code/modules/projectiles/projectile.dm
Labels: Fix

#11955 Add Stand Arrow to Summon magic
  code/modules/spells/spell_types/rightandwrong.dm
Labels: Feature

#11986 Fixes dynamic not respecting prefs
  code/game/gamemodes/dynamic/dynamic_rulesets.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
Labels: Fix

#11974 Adds cool huds
  code/__DEFINES/~hippie_defines/misc.dm
  hippiestation/code/game/gamemodes/gangs/dominator.dm
  hippiestation/code/game/gamemodes/gangs/gang_items.dm
  hippiestation/code/modules/guardian/guardian.dm
  hippiestation/code/modules/guardian/guardianbuilder.dm
  hippiestation/code/modules/guardian/standarrow.dm
  hippiestation/icons/effects/effects.dmi
Labels: Feature

#11979 BRINGS BACK TTS
  code/modules/client/preferences.dm
  config/hippiestation_config.txt
  hippiestation/code/controllers/configuration/entries/hippiestation_config.dm
  hippiestation/code/controllers/subsystem/tts.dm
  hippiestation/code/datums/dna.dm
  hippiestation/code/modules/admin/admin_verbs.dm
  hippiestation/code/modules/client/client_procs.dm
  hippiestation/code/modules/client/preferences.dm
  hippiestation/code/modules/client/preferences_savefile.dm
  hippiestation/code/modules/mob/living/say.dm
Labels: Config Update, Feature

#11990 Fix some flag BS
  hippiestation/code/modules/client/client_defines.dm
  hippiestation/code/modules/client/client_procs.dm
  hippiestation/icons/ooc_icons/countries.dmi
Labels: Fix

#11989 Projectiles can no longer dismember un-dismemerable things
  hippiestation/code/modules/mob/living/carbon/carbon_defense.dm
Labels: Fix

#11991 Revert "I think the linux OpenPort bug is fixed"
  code/game/world.dm
Labels: Revert, STEAMPOOOORT

#11993 Actually fixes tts
  hippiestation/code/controllers/subsystem/ticker.dm
  hippiestation/code/controllers/subsystem/tts.dm
Labels: Fix

#11996 Fix more TTS crap
  hippiestation/code/controllers/subsystem/tts.dm
Labels: Fix

#11998 I dunno, this might fix the server dying ocassionally?
  hippiestation/code/controllers/subsystem/ticker.dm
Labels: HHHHOLY FUCK IM GOING TO ACTUALLY DIE

#12002 Fix tts hangs
  .gitignore
  config/hippiestation_config.txt
  hippiestation/code/controllers/subsystem/ticker.dm
  hippiestation/code/controllers/subsystem/tts.dm
Labels: Config Update, Fix

#11950 Nerfs science a little bit and other adjustments
  _maps/map_files/HippieStation/hippiestation.dmm
  hippiestation/code/modules/power/port_gen.dm
  hippiestation/code/modules/research/designs/machine_designs.dm
  hippiestation/code/modules/research/techweb/all_nodes.dm
Labels: Balance/Rebalance, Fix, Map Edit, Removal

#12018 Fixes borg heads giving humans lisps
  hippiestation/code/modules/teeth/misc.dm
Labels: Fix

#12019 REMOVES A SLEEP FROM sparks LateInitialize
  code/game/objects/effects/effect_system/effects_sparks.dm
Labels: Removal

#11992 Makes shotguns better
  hippiestation/code/modules/projectiles/guns/ballistic/shotgun.dm
Labels: Feature

#12022 Nerf suicide bombs
  code/datums/wires/explosive.dm
Labels: Balance/Rebalance, Feature

#12024 Shotgun Update - FUCKING AMARI edition
  hippiestation/code/modules/projectiles/guns/ballistic/shotgun.dm
Labels: 80 year old man eating ten bags of Cheetos, Fix

#12027 Dynamic from-ghosts rulesets should no longer make 1-man abductor teams and stuff
  hippiestation/code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
Labels: Fix

#12023 Antagonist tips
  hippiestation.dme
  hippiestation/code/modules/antagonists/_common/antag_datum.dm
  hippiestation/code/modules/antagonists/_common/tips.dm
  hippiestation/code/modules/antagonists/traitor/datum_traitor.dm
  hippiestation/code/modules/client/asset_cache.dm
  hippiestation/html/antagtips/abductor.html
  hippiestation/html/antagtips/nukie.html
  hippiestation/html/antagtips/traitor.html
  hippiestation/html/antagtips/wizard.html
  hippiestation/html/img/abaton.png
  hippiestation/html/img/alienorgan.png
  hippiestation/html/img/ayylmao.png
  hippiestation/html/img/disk.png
  hippiestation/html/img/eshield.png
  hippiestation/html/img/gauntlet.png
  hippiestation/html/img/headset.png
  hippiestation/html/img/mech.png
  hippiestation/html/img/nuke.png
  hippiestation/html/img/nukie.png
  hippiestation/html/img/pda.png
  hippiestation/html/img/pen.png
  hippiestation/html/img/scitool.png
  hippiestation/html/img/scroll.png
  hippiestation/html/img/spellbook.png
  hippiestation/html/img/syndielad.png
  hippiestation/html/img/traitor.png
  hippiestation/html/img/wizard.png
Labels: Feature

#12020 Prevent thanos from spamming gauntlet prompts for multiple stones
  hippiestation/code/modules/gauntlet/gauntlet.dm
Labels: Fix, STEAMPOOOORT

#11980 [FIXED] Add :feelsoldman: in icons
  hippiestation/icons/emoji.dmi
Labels: Feature, Sprites

#12080 Logs canister label changing [READY]
  code/modules/atmospherics/machinery/portable/canister.dm
Labels: Administration, Logging, Needs Review

#12078 Dependeabot fixes
  tgui/assets/font-awesome.min.css
  tgui/assets/fonts/fontawesome-webfont.eot
  tgui/assets/fonts/fontawesome-webfont.svg
  tgui/assets/fonts/fontawesome-webfont.ttf
  tgui/assets/fonts/fontawesome-webfont.woff
  tgui/assets/fonts/fontawesome-webfont.woff2
  tgui/assets/tgui.css
  tgui/assets/tgui.js
  tgui/gulp/css.js
  tgui/src/tgui.js
Labels: UI

#12084 Tgui fix
  code/modules/client/asset_cache.dm
  code/modules/client/darkmode.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/goonchat/browserassets/css/browserOutput_white.css
  code/modules/goonchat/browserassets/css/font-awesome.css
  code/modules/goonchat/browserassets/html/browserOutput.html
  code/modules/tgui/tgui.dm
  html/font-awesome/README.MD
  html/font-awesome/css/all.min.css
  html/font-awesome/css/v4-shims.min.css
  html/font-awesome/webfonts/fa-regular-400.eot
  html/font-awesome/webfonts/fa-regular-400.woff
  html/font-awesome/webfonts/fa-solid-900.eot
  html/font-awesome/webfonts/fa-solid-900.woff
  tgui/assets/font-awesome.min.css
  tgui/assets/fonts/SIL-OFL-1.1-LICENSE.md
  tgui/assets/fonts/fontawesome-webfont.eot
  tgui/assets/fonts/fontawesome-webfont.svg
  tgui/assets/fonts/fontawesome-webfont.ttf
  tgui/assets/fonts/fontawesome-webfont.woff
  tgui/assets/fonts/fontawesome-webfont.woff2
  tgui/assets/tgui.css
  tgui/assets/tgui.js
  tgui/src/components/titlebar.ract
  tgui/src/components/titlebar.styl
  tgui/src/components/warnings.ract
  tgui/src/tgui.js
Labels: UI

#12090 removes moths
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
Labels: Removal

#12094 Fixes CQC manuals and a code redundancy
  hippiestation/code/modules/uplink/uplink_items.dm
Labels: Fix

#12095 Infiltrators will now spawn with nuke core/SM shard stealy thingies
  hippiestation/code/modules/antagonists/infiltrator/team.dm
Labels: Fix

#12104 Fixes shield wall gen disappearing
  icons/obj/stationobjs.dmi
Labels: Fix, Sprites

#12106 Update some tgui stuff
  .editorconfig
  tgui/assets/tgui.js
  tgui/gulp/css.js
  tgui/src/components/titlebar.ract
  tgui/src/util/byond.js
  tgui/src/util/dragresize.js
Labels: UI

#12112 Actually fixes robotic heads giving lisps
  hippiestation/code/modules/teeth/misc.dm
Labels: Fix

#12114 Fix teeth code lisps
  hippiestation/code/modules/mob/living/carbon/human/human.dm
  hippiestation/code/modules/teeth/misc.dm
  hippiestation/code/modules/teeth/teeth.dm
Labels: Fix

#12079 Sawn-off Shotgun Invisibility Fix
  code/modules/projectiles/guns/ballistic.dm
  hippiestation/code/modules/projectiles/guns/ballistic/shotgun.dm
  hippiestation/icons/obj/guns/projectile.dmi
Labels: Fix

#12096 [SPEEDMERGE THIS ALREADY] Saying "owo" or "uwu" now gives you brain damage
  hippiestation/code/modules/mob/living/say.dm
Labels: Feature

#12006 You can no longer make yourself immune to non-advanced viruses with a healing virus
  hippiestation/code/datums/diseases/_MobProcs.dm
Labels: Balance/Rebalance, Fix, Tweak

#12110 renames Morphine to Sleep Toxin
  hippiestation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Tweak

#12116 Fixes a lot of ganger stuff
  code/__DEFINES/cinematics.dm
  hippiestation/code/datums/cinematic.dm
  hippiestation/code/game/gamemodes/gangs/dominator.dm
  hippiestation/code/game/gamemodes/gangs/gang_items.dm
  hippiestation/code/game/gamemodes/gangs/gangtool.dm
  hippiestation/code/game/objects/effects/countdown.dm
  hippiestation/code/modules/antagonists/gang/gang.dm
Labels: Administration, Feature, Fix, Old Hippiestation Port, Tweak

#12085 Reduces Predator cost to 2 points
  hippiestation/code/modules/guardian/abilities/major/predator.dm
Labels: Fix

#12015 Removes reactive teleport armor from RD's locker
  code/game/gamemodes/objective_items.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
Labels: Old Hippiestation Port, Removal

#12009 More thanos crap
  hippiestation/code/modules/gauntlet/clown.dm
  hippiestation/code/modules/gauntlet/gauntlet.dm
  hippiestation/code/modules/gauntlet/syndie.dm
  hippiestation/icons/obj/infinity.dmi
Labels: Balance/Rebalance, Feature, Fix, Sprites

#12100 Fixes hippiestation and metalake toxins burn chamber
  _maps/map_files/HippieStation/hippiestation.dmm
  _maps/map_files/MetaLake/MetaLake.dmm
Labels: Feature, Fix, Map Edit

#12121 Fix for the fun filter
  hippiestation/code/modules/mob/living/say.dm
Labels: Fix

#12120 Revert "[SPEEDMERGE THIS ALREADY] Saying "owo" or "uwu" now gives you brain damage"
  hippiestation/code/modules/mob/living/say.dm
Labels: Revert

#12117 Space no longer gets hot and other atmos fixes
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/atmospherics/machinery/portable/canister.dm
Labels: Fix

#12119 The solid chemicals melt into a liquid!
  hippiestation/code/_globalvars/lists/typecache.dm
  hippiestation/code/modules/reagents/chemistry/holder.dm
Labels: Fix

#12123 Revert "Fix for the fun filter"
  hippiestation/code/modules/mob/living/say.dm
Labels: Revert

#12127 Fix magic projectiles mirror
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/spells/spell_types/wizard.dm
Labels: Fix
