Repository HippieStation/HippieStation, pull requests merged in 2019-01, with the labels that each got.

#10188 Sacrificing a catbeast to the SM can now avert a delamination
  code/modules/power/supermatter/supermatter.dm
  hippiestation.dme
  hippiestation/code/modules/power/supermatter/supermatter.dm
Labels: Feature

#10289 Fixes ss13 logo and pipe causing runtimes
  _maps/map_files/HippieStation/hippiestation.dmm
  hippiestation/code/game/turfs/simulated/floor.dm
Labels: Fix, Map Edit, Ready for Review

#10290 Fixed nanosuit runtiming
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Code Improvement, Fix

#10262 Nerfs meth/black powder/superboom smoke
  hippiestation/code/modules/reagents/chemistry/recipes/pyrotechnics.dm
Labels: Balance/Rebalance

#9858 Guillotines have a chance to fail on fat people
  code/game/objects/structures/guillotine.dm
  hippiestation.dme
  hippiestation/code/game/objects/structures/guillotine.dm
Labels: Feature

#10310 Fixed unconnected vents/scrubbers
  _maps/map_files/HippieStation/hippiestation.dmm
  hippiestation.dme
Labels: Fix, Map Edit

#10313 Fixes double examine message
  code/modules/mob/living/carbon/examine.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Fix

#10336 Compiled tgui
  tgui/assets/tgui.js
Labels: UI

#10330 A Fix for the Split Body Ability of Slimepeople
  hippiestation/code/datums/dna.dm
Labels: Fix

#10141 NullCrate price change
  hippiestation/code/modules/cargo/packs.dm
Labels: Tweak

#10349 Fixed decal corner rotation, unconnected tank, disposal conveyor.
  _maps/map_files/HippieStation/hippiestation.dmm
  hippiestation/code/modules/pool/pool_controller.dm
Labels: Code Improvement, Fix, Map Edit

#10356 Actually fix disposals corner conveyor and a visible pipe
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Map Edit

#10398 Removes TTS libraries, doing this in advance
  hippiestation/code/modules/mob/living/say.dm
  tts_generator/FonixTalk.dll
  tts_generator/OggEnc.exe
  tts_generator/SharpTalk.dll
  tts_generator/ftalk_us.dic
  tts_generator/ftalk_us.dll
  tts_generator/tts_generator.exe
Labels: FUCK, Removal

#10354 Removes hygiene
  code/__DEFINES/mobs.dm
Labels: Removal

#10421 Fix teeth, lisps and other some other old, broken code.
  code/modules/mob/living/carbon/human/species.dm
  hippiestation.dme
  hippiestation/code/modules/mob/living/carbon/human/human.dm
  hippiestation/code/modules/mob/living/carbon/human/life.dm
  hippiestation/code/modules/mob/living/carbon/human/species.dm
  hippiestation/code/modules/mob/living/say.dm
  hippiestation/code/modules/teeth/misc.dm
Labels: Code Improvement, Fix

#10389 Chem piles are now immune to acid and fire
  hippiestation/code/game/objects/effects/decals/cleanable/chem.dm
Labels: Tweak

#10370 Added clf3 to reagent state change blacklist.
  hippiestation/code/_globalvars/lists/typecache.dm
Labels: Balance/Rebalance, Fix

#10180 Shotguns fire double pellets but deal half damage
  hippiestation.dme
  hippiestation/code/modules/projectiles/ammunition/ballistic/shotgun.dm
  hippiestation/code/modules/projectiles/projectile/bullets.dm
Labels: Balance/Rebalance

#10428 Fix clothing stat examine message not appearing
  code/modules/clothing/clothing.dm
Labels: Fix

#10215 Added hurt sounds for brute and burn damage
  code/game/sound.dm
  code/modules/mob/living/carbon/human/species.dm
  hippiestation/code/modules/mob/living/carbon/human/species.dm
  hippiestation/code/modules/vehicles/pimpin_ride.dm
  hippiestation/sound/voice/gib_scream.ogg
  hippiestation/sound/voice/male_hurt1.ogg
  hippiestation/sound/voice/male_hurt10.ogg
  hippiestation/sound/voice/male_hurt11.ogg
  hippiestation/sound/voice/male_hurt12.ogg
  hippiestation/sound/voice/male_hurt13.ogg
  hippiestation/sound/voice/male_hurt14.ogg
  hippiestation/sound/voice/male_hurt15.ogg
  hippiestation/sound/voice/male_hurt16.ogg
  hippiestation/sound/voice/male_hurt17.ogg
  hippiestation/sound/voice/male_hurt18.ogg
  hippiestation/sound/voice/male_hurt19.ogg
  hippiestation/sound/voice/male_hurt2.ogg
  hippiestation/sound/voice/male_hurt20.ogg
  hippiestation/sound/voice/male_hurt21.ogg
  hippiestation/sound/voice/male_hurt3.ogg
  hippiestation/sound/voice/male_hurt4.ogg
  hippiestation/sound/voice/male_hurt5.ogg
  hippiestation/sound/voice/male_hurt6.ogg
  hippiestation/sound/voice/male_hurt7.ogg
  hippiestation/sound/voice/male_hurt8.ogg
  hippiestation/sound/voice/male_hurt9.ogg
Labels: Feature, Sound

#10440 Fixes throw impact doing twice the normal damage
  code/modules/mob/living/carbon/carbon.dm
  hippiestation/code/modules/mob/living/carbon/carbon.dm
Labels: Fix

#10463 Re-adds old 2015 sounds, again.
  code/controllers/subsystem/communications.dm
  code/game/machinery/doors/windowdoor.dm
  code/modules/reagents/reagent_containers/spray.dm
  hippiestation.dme
  hippiestation/code/__HELPERS/priority_announce.dm
  hippiestation/code/controllers/subsystem/communications.dm
  hippiestation/code/game/machinery/doors/airlock.dm
  hippiestation/code/modules/mob/living/carbon/human/species.dm
  hippiestation/code/modules/projectiles/projectile/energy.dm
  hippiestation/sound/effects/spray2.ogg
  hippiestation/sound/machines/airlock.ogg
  hippiestation/sound/machines/windowdoor.ogg
  hippiestation/sound/misc/announce.ogg
  hippiestation/sound/misc/notice1.ogg
  hippiestation/sound/misc/notice2.ogg
  hippiestation/sound/weapons/Laser.ogg
  hippiestation/sound/weapons/punch1.ogg
  hippiestation/sound/weapons/punchmiss.ogg
Labels: Sound

#10456 Nanosuit upgrades, balance changes, bug squashing. [READY]
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Balance/Rebalance, Feature, Fix, Grammar and Formatting, Needs Review, Tweak

#10489 Floor cluwne bug fixes
  code/__DEFINES/~hippie_defines/dna.dm
  hippiestation/code/modules/mob/living/simple_animal/floor_cluwne.dm
  hippiestation/icons/turf/floors.dmi
Labels: Fix, Tweak

#10486 Reverts Energy/Disabler speed.
  hippiestation/code/modules/projectiles/projectile.dm
Labels: Balance/Rebalance, Revert

#10493 [READY] Fixes floor cluwne locker check and some other exploits
  code/__DEFINES/~hippie_defines/flags.dm
  hippiestation.dme
  hippiestation/code/modules/events/floorcluwne.dm
  hippiestation/code/modules/mob/living/simple_animal/floor_cluwne.dm
Labels: Fix, Needs Review, Tweak

#10509 Fixes the Sleeping Carp Scroll
  hippiestation/code/modules/uplink/uplink_items.dm
Labels: Fix

#10510 Fixes nanosuit not killing cloak when it was supposed to
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Fix
