Repository HippieStation/HippieStation, pull requests merged in 2019-04, with the labels that each got.

#11054 Fixes catbans and cleaned up some other minor code [READY]
  code/__DEFINES/~hippie_defines/admin.dm
  code/__DEFINES/~hippie_defines/atom_hud.dm
  code/__DEFINES/~hippie_defines/layers.dm
  code/controllers/subsystem/job.dm
  code/modules/admin/admin_investigate.dm
  hippiestation/code/controllers/subsystem/job.dm
  hippiestation/code/datums/dna.dm
Labels: Fix, Needs Review

#11053 Fixes "Now playing: ." menu music helper
  hippiestation/code/controllers/subsystem/ticker.dm
Labels: Fix

#11051 adds throwsounds again
  code/modules/mob/living/carbon/carbon.dm
  hippiestation/sound/effects/throw.ogg
  hippiestation/sound/effects/throw2.ogg
  hippiestation/sound/effects/throw3.ogg
Labels: Old Hippiestation Port, Sound

#11068 Fixes world and reverts the revert of the mirror revert
  code/game/world.dm
  code/modules/tgs/event_handler.dm
  hippiestation.dme
  tgstation.dme
Labels: Do Not Merge, Revert

#11095 Revert^5 because the linux bug may not be fixed yet
  code/game/world.dm
  code/modules/tgs/event_handler.dm
  hippiestation.dme
Labels: Revert

#11088 Minesweeper huge performance fix
  hippiestation/code/game/machinery/computer/arcade.dm
  hippiestation/icons/arcade/minesweeper_1.dmi
  hippiestation/icons/arcade/minesweeper_2.dmi
  hippiestation/icons/arcade/minesweeper_3.dmi
  hippiestation/icons/arcade/minesweeper_4.dmi
  hippiestation/icons/arcade/minesweeper_5.dmi
  hippiestation/icons/arcade/minesweeper_6.dmi
  hippiestation/icons/arcade/minesweeper_7.dmi
  hippiestation/icons/arcade/minesweeper_8.dmi
  hippiestation/icons/arcade/minesweeper_empty.dmi
  hippiestation/icons/arcade/minesweeper_flag.dmi
  hippiestation/icons/arcade/minesweeper_hidden.dmi
  hippiestation/icons/arcade/minesweeper_mine.dmi
  hippiestation/icons/arcade/minesweeper_minehit.dmi
  hippiestation/icons/arcade/minesweeper_tiles.dmi
Labels: Candidate for Testmerge, FUCK, Fix

#11089 Fixes some outdated/old hippie map stuff
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Fix, Map Edit, Tweak

#11096 Chempiles are now affected by explosions! (Chain reaction explosions) [WIP]
  code/game/objects/effects/effect_system/effects_smoke.dm
  hippiestation.dme
  hippiestation/code/game/gamemodes/gangs/dominator.dm
  hippiestation/code/game/gamemodes/gangs/gang_pen.dm
  hippiestation/code/game/gamemodes/gangs/gangtool.dm
  hippiestation/code/game/objects/effects/decals/cleanable/chem.dm
  hippiestation/code/game/objects/effects/decals/crayon.dm
  hippiestation/code/game/objects/effects/effect_system/effects_foam.dm
  hippiestation/code/game/objects/effects/effect_system/effects_other.dm
  hippiestation/code/game/objects/effects/effect_system/effects_smoke.dm
  hippiestation/code/game/objects/effects/effect_system/effects_vapour.dm
  hippiestation/code/game/objects/inflatables.dm
  hippiestation/code/game/objects/item.dm
  hippiestation/code/modules/reagents/chemistry/holder.dm
  hippiestation/code/modules/reagents/chemistry/reagents/food_reagents.dm
Labels: Code Improvement, Feature, Work In Progress

#10812 you can now black list reagents from strange seeds using can_synth_seeds
  code/modules/hydroponics/seeds.dm
  hippiestation.dme
  hippiestation/code/modules/hydroponics/seeds.dm
  hippiestation/code/modules/reagents/chemistry/reagents.dm
Labels: Needs Head Input, Tweak

#11052 Re-adds old zippo icons
  hippiestation/code/game/objects/items/cigs_lighters.dm
Labels: Old Hippiestation Port, Sprites

#11075 Shuttle be gone
  _maps/shuttles/emergency_big.dmm
  config/unbuyableshuttles.txt
  hippiestation/code/datums/shuttles.dm
Labels: BASED AND REDPILLED, Config Update, Map Edit, Needs Head Input, Revert/Removal

#11114 Webeditor PR touching chem-pile reaction chance
  hippiestation/code/game/objects/effects/decals/cleanable/chem.dm
Labels: Tweak

#11115 Slightly increases amount of chemicals smoke adds
  code/game/objects/effects/effect_system/effects_smoke.dm
Labels: Tweak

#11108 Revert "Removes antistun from hulk - keeps wall punching"
  code/datums/mutations/hulk.dm
Labels: Needs Head Input, Removal, Revert

#11105 Fixes some runtimes, poor initialization parent calls and chem tanks.
  code/modules/admin/admin_verbs.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/manifold.dm
  hippiestation/code/datums/dna.dm
  hippiestation/code/game/atoms.dm
  hippiestation/code/game/turfs/turf.dm
  hippiestation/code/modules/admin/verbs/randomverbs.dm
  hippiestation/code/modules/mob/living/carbon/human/human.dm
  hippiestation/code/modules/reagents/reagent_dispenser.dm
Labels: Administration, Code Improvement, Fix, Tweak

#11038 OOC icons for staff and donators, donator gold OOC colour & the ability to add and remove donators from the database
  code/__DEFINES/~hippie_defines/donator.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/verbs/ooc.dm
  config/donators.txt
  hippiestation.dme
  hippiestation/SQL/donator.sql
  hippiestation/code/init.dm
  hippiestation/code/modules/admin/admin.dm
  hippiestation/code/modules/admin/topic.dm
  hippiestation/code/modules/client/client_procs.dm
  hippiestation/code/modules/donator/donator.dm
  hippiestation/code/modules/mob/login.dm
  hippiestation/icons/ooc_icons/banhammer.dmi
  hippiestation/icons/ooc_icons/brain.dmi
  hippiestation/icons/ooc_icons/gold_coin.dmi
Labels: 80 year old man eating 10 bags of Cheetos., Candidate for Testmerge, Config Update, Difficulty: ROCK HARD, Feature, Needs Head Input, Ready for Review

#11126 Fixes for some IC tools
  hippiestation/code/modules/integrated_electronics/core/debugger.dm
  hippiestation/code/modules/integrated_electronics/subtypes/input.dm
  hippiestation/code/modules/integrated_electronics/subtypes/reagents.dm
Labels: Fix

#11142 answer to issue #10535
  hippiestation/code/modules/uplink/uplink_items.dm
Labels: Tweak

#11129 Realclown
  hippiestation.dme
  hippiestation/code/modules/jobs/job_types/clown.dm
Labels: Feature

#11172 Fixes stun nettles
  hippiestation/code/modules/hydroponics/grown/nettle.dm
  hippiestation/icons/obj/hydroponics/growing.dmi
Labels: Removal

#11218 Moths are no longer immune to flashes
  hippiestation/code/modules/mob/living/carbon/human/species_types/mothmen.dm
Labels: Fix

#11176 Add the Interdimensional Sword
  hippiestation.dme
  hippiestation/code/modules/antagonists/wizard/equipment/spellbook.dm
  hippiestation/code/modules/spells/spell_types/bfs.dm
  hippiestation/icons/effects/bfs.dmi
Labels: Feature

#11266 [s] CRITICAL ANTAG FIX
  hippiestation/code/modules/antagonists/changeling/powers/tiny_prick.dm
Labels: >Amari: Confrim code is tested, Priority: CRITICAL

#11268 Ports yogstation fix for people literally respawning
  code/modules/antagonists/wizard/equipment/soulstone.dm
Labels: Fix

#11276 Recompiles tgui
  tgui/assets/tgui.js
Labels: UI

#11247 Surplus Exclusive Items Two Electric Boogaloo
  code/modules/uplink/uplink_items.dm
  hippiestation.dme
  hippiestation/code/modules/uplink/surplus_items.dm
  hippiestation/icons/mob/feet.dmi
  hippiestation/icons/mob/inhands/equipment/custodial_lefthand.dmi
  hippiestation/icons/mob/inhands/equipment/custodial_righthand.dmi
  hippiestation/icons/obj/clothing/shoes.dmi
  hippiestation/icons/obj/guns/projectile.dmi
  hippiestation/icons/obj/hydroponics/harvest.dmi
  hippiestation/icons/obj/janitor.dmi
  hippiestation/sound/misc/lubricator.ogg
  hippiestation/sound/weapons/blood_debt.ogg
Labels: Feature

#11281 Fix some infiltrator stuff
  hippiestation/code/game/gamemodes/objective.dm
  hippiestation/code/modules/antagonists/infiltrator/objectives.dm
Labels: Fix

#11301 Sseth sounds
  hippiestation/code/controllers/subsystem/ticker.dm
  hippiestation/sound/roundend/ssethdisappointed.ogg
  hippiestation/sound/roundend/ssethenjoyedyourchaos.ogg
  hippiestation/sound/roundend/ssethyoumakemesick.ogg
Labels: Feature

#11267 Adds another hardsuit reaction message
  hippiestation/code/modules/clothing/spacesuits/hardsuit.dm
Labels: Feature, Tweak

#11241 No more dumb foam!
  hippiestation.dme
  hippiestation/code/modules/events/vent_clog.dm
Labels: Removal
