Repository HippieStation/HippieStation, pull requests merged in 2020-02, with the labels that each got.

#12576 Various tg stuff
  code/__DEFINES/profile.dm
  code/__DEFINES/subsystems.dm
  code/_globalvars/lists/admin.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/air.dm
  code/controllers/subsystem/profiler.dm
  code/controllers/subsystem/stickyban.dm
  code/game/world.dm
  code/modules/admin/IsBanned.dm
  code/modules/admin/verbs/debug.dm
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/atmospherics/machinery/components/components_base.dm
  code/modules/client/client_procs.dm
  code/modules/mob/living/say.dm
  config/config.txt
  hippiestation.dme
  html/changelogs/AutoChangeLog-pr-48871.yml
  tgstation.dme
Labels: Config Update

#12578 Revert "Only allow one call to IsBanned to process at a time, per ckey"
  code/modules/admin/IsBanned.dm
Labels: Revert

#12580 Makes the mechfab use the ore silo.
  _maps/map_files/Deltastation/DeltaStation2.dmm
  code/game/mecha/mech_fabricator.dm
  code/modules/mining/machine_silo.dm
Labels: Map Edit

#12585 Fixes not being able to resist cuffs while pinned
  hippiestation/code/modules/mob/living/carbon/carbon.dm
  hippiestation/code/modules/mob/living/living.dm
Labels: Fix

#12589 Fixes radium reference
  hippiestation/code/modules/reagents/chemistry/reagents/density.dm
Labels: Fix

#12592 Revert "Revert "Makes the mechfab use the ore silo.""
  _maps/map_files/Deltastation/DeltaStation2.dmm
  code/game/mecha/mech_fabricator.dm
Labels: Map Edit, Revert, Tweak

#12587 Probably fixes storage spray issue
  code/modules/reagents/reagent_containers/spray.dm
Labels: Fix

#12593 Coffin and staple gun fixes
  hippiestation/code/datums/antagonists/vampire.dm
  hippiestation/code/game/objects/items/staples.dm
Labels: Code Improvement, Fix

#12595 Refactors examine on hippie code since it wasn't properly done
  hippiestation/code/game/gamemodes/gangs/dominator.dm
  hippiestation/code/game/machinery/cloning.dm
  hippiestation/code/game/machinery/dna_scanner.dm
  hippiestation/code/game/machinery/reagent_sheet.dm
  hippiestation/code/game/machinery/sprinkler.dm
  hippiestation/code/game/objects/items/holotool/holotool.dm
  hippiestation/code/game/objects/items/melee/hfblade.dm
  hippiestation/code/modules/antagonists/infiltrator/items/pinpointer.dm
  hippiestation/code/modules/clothing/shoes/magboots.dm
  hippiestation/code/modules/crafts/shield.dm
  hippiestation/code/modules/events/holiday/vday.dm
  hippiestation/code/modules/integrated_electronics/core/assemblies.dm
  hippiestation/code/modules/integrated_electronics/subtypes/memory.dm
  hippiestation/code/modules/mining/machine_redemption.dm
  hippiestation/code/modules/paperwork/photography.dm
  hippiestation/code/modules/projectiles/guns/ballistic/launchers.dm
  hippiestation/code/modules/projectiles/guns/ballistic/magweapon_energy.dm
  hippiestation/code/modules/projectiles/guns/energy/special.dm
  hippiestation/code/modules/telescience/telesci_computer.dm
Labels: Fix, Refactor

#12596 Fixes pandemic being unable to rename diseases
  tgui-next/packages/tgui/interfaces/Pandemic.js
  tgui-next/packages/tgui/public/tgui.bundle.js
Labels: Fix, UI

#12598 Fixes automatic changelog compile
  .github/workflows/compile_changelogs.yml
Labels: GitHub

#12599 Updates token to be secret name
  .github/workflows/compile_changelogs.yml
Labels: GitHub

#12600 Fix non-working TGUI autobuild
  .github/workflows/autobuild_tgui.yml
Labels: GitHub

#12601 Fixes map rotation chance delta config
  config/config.txt
Labels: Config Update

#12606 Nuka Cola Tweak
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/vending/cola.dm
Labels: Feature, Tweak

#12613 adds cost and comments out dwarves template
  code/datums/ruins/lavaland.dm
Labels: Fix

#12572 173 Improvements 2.0 (LESS FUCK VIVADEL)
  code/modules/mob/living/simple_animal/hostile/statue.dm
  hippiestation/code/modules/SCPmodular/scps/euclid/SCP-173.dm
Labels: Fix, Tweak
