Repository HippieStation/HippieStation, pull requests merged in 2020-04, with the labels that each got.

#12688 Fixed white screen for contraband-less vending machines
  hippiestation/code/modules/vending/_vending.dm
Labels: Fix

#12687 Swinging Revolver in hand
  hippiestation/code/modules/projectiles/guns/ballistic/revolver.dm
Labels: Feature

#12655 Roundstart Honkbot
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Map Edit

#12690 Potentially fixes hippie logo floor tiles breaking
  hippiestation/code/game/turfs/simulated/floor.dm
Labels: Fix

#12692 Light overlay fix
  code/modules/power/lighting.dm
Labels: Fix

#12696 Fixes defib mounts not working properly
  code/game/objects/items/defib.dm
Labels: Fix

#12695 Fixes drying racks disappearing when unanchoring
  hippiestation/code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
Labels: Fix

#12694 Fixes some suicide vest shit
  code/modules/clothing/suits/armor.dm
Labels: Balance/Rebalance, Fix

#12683 Bananium in the miner
  hippiestation/code/modules/mining/machine_bluespace.dm
Labels: Tweak

#12676 Make blood splatters fly for longer
  code/modules/mob/living/carbon/human/species.dm
  hippiestation/code/game/objects/effects/decals/cleanable/humans.dm
  hippiestation/code/modules/projectiles/projectile/bullets.dm
Labels: Tweak

#12697 Makes the forge bullets all change into the same caliber at once
  hippiestation/code/game/objects/items/forged_weapons.dm
Labels: Tweak

#12701 Shuttle fixes
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/shuttle.dm
  code/modules/mapping/map_template.dm
Labels: Fix, Priority: High

#12698 Safety Doors port from TG(#46332)
  _maps/map_files/HippieStation/hippiestation.dmm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
Labels: Feature, Map Edit

#12658 Greytide worldwide
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/components/crafting/recipes.dm
  code/datums/mind.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/objects/items/granters.dm
  code/modules/antagonists/revolution/revolution.dm
  code/modules/cargo/packs.dm
  code/modules/uplink/uplink_items.dm
  hippiestation.dme
  hippiestation/code/datums/components/crafting/recipes.dm
  hippiestation/code/game/objects/items/granters.dm
  hippiestation/code/game/objects/items/storage/uplink_kits.dm
  hippiestation/code/modules/projectiles/guns/ballistic/pistols.dm
  hippiestation/code/modules/research/designs/autolathe_designs.dm
  hippiestation/code/modules/uplink/uplink_items.dm
  hippiestation/icons/obj/guns/projectile.dmi
  hippiestation/icons/obj/library.dmi
  hippiestation/sound/effects/liberty.ogg
  icons/obj/library.dmi
Labels: Balance/Rebalance, Feature, Sprites

#12703 Fixes some map areas + adds an extra chem tank
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Feature, Fix, Map Edit

#12699 Re-adds directly attaching assemblies to chem grenades
  code/game/objects/items/grenades/chem_grenade.dm
  hippiestation/code/game/objects/items/grenades/chem_grenade.dm
Labels: Feature

#12709 Nano guy specific headset change
  code/modules/food_and_drinks/food/snacks_meat.dm
  hippiestation/code/modules/gauntlet/revengers.dm
Labels: Fix, Tweak

#12713 Explosions no longer leave behind gas overlays
  code/datums/components/orbiter.dm
  code/game/turfs/open/space/space.dm
  hippiestation/code/modules/admin/verbs/fillbreach.dm
Labels: Administration, Fix

#12712 Fixes some more defib bugs
  code/game/objects/items/defib.dm
Labels: Fix

#12711 Adds a nebula background to parallax
  code/_onclick/hud/parallax.dm
  icons/effects/parallax.dmi
Labels: Feature, Sprites

#12716 Get rid of ismovableatom
  code/__DEFINES/is_helpers.dm
  code/__HELPERS/icon_smoothing.dm
  code/_onclick/observer.dm
  code/datums/components/beetlejuice.dm
  code/datums/components/edit_complainer.dm
  code/datums/components/infective.dm
  code/datums/components/knockback.dm
  code/datums/components/magnetic_catch.dm
  code/datums/components/plumbing/_plumbing.dm
  code/datums/components/riding.dm
  code/datums/components/rotation.dm
  code/datums/components/squeak.dm
  code/datums/components/stationloving.dm
  code/datums/elements/cleaning.dm
  code/datums/movement_detector.dm
  code/game/atoms.dm
  code/game/machinery/teleporter.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/objects/effects/step_triggers.dm
  code/game/objects/items/singularityhammer.dm
  code/game/objects/items/theft_tools.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/morgue.dm
  code/game/objects/structures/tables_racks.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/blob/structures/_blob.dm
  code/modules/buildmode/submodes/copy.dm
  code/modules/events/wormholes.dm
  code/modules/language/language_holder.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/mob.dm
  code/modules/photography/camera/camera_image_capturing.dm
  code/modules/power/singularity/narsie.dm
  code/modules/projectiles/guns/misc/beam_rifle.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/recycling/sortingmachinery.dm
  hippiestation/code/controllers/subsystem/demo.dm
  hippiestation/code/modules/gauntlet/supermatter.dm
  hippiestation/code/modules/projectiles/projectile/magic.dm
  hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
Labels: Maintainability/Hinders improvements

#12717 3 More parallax backgrounds
  code/_onclick/hud/parallax.dm
  icons/effects/parallax.dmi
Labels: Feature, Sprites

#12720 Fixed forged weapon equipping being broken
  hippiestation/code/game/objects/items/forged_weapons.dm
Labels: Fix

#12723 Fixes parallax transit glitches
  code/_onclick/hud/parallax.dm
Labels: Fix

#12724 Fixes planet parallax being missing
  code/_onclick/hud/parallax.dm
Labels: Fix

#12702 Adds gravity room to the power failure safe areas
  code/__HELPERS/areas.dm
Labels: Tweak

#12710 syndicate firesuit description fix
  hippiestation/code/modules/uplink/uplink_items.dm
Labels: Fix, Grammar and Formatting

#12725 Removes all that stuff that was non-compliant of GitHub's TOS
  _maps/RandomRuins/SpaceRuins/bus.dmm
  _maps/RandomZLevels/caves.dmm
  code/__DEFINES/inventory.dm
  code/__HELPERS/game.dm
  code/datums/diseases/wizarditis.dm
  code/datums/mutations/speech.dm
  code/game/machinery/doors/checkForMultipleDoors.dm
  code/game/objects/items/manuals.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/structures/signs/signs_plaques.dm
  code/modules/admin/secrets.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/head/misc.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/recipes/processor_recipes.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pizza.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_salad.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_soup.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_spaghetti.dm
  code/modules/holiday/easter.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/lighting/lighting_corner.dm
  code/modules/mob/living/carbon/alien/humanoid/update_icons.dm
  code/modules/vending/wardrobes.dm
  hippiestation/code/datums/diseases/cluwnification.dm
  hippiestation/code/modules/projectiles/guns/ballistic/shotgun.dm
  html/archivedchangelog.html
  html/changelog.html
  html/changelogs/.all_changelog.yml
  icons/obj/clothing/hats.dmi
  icons/obj/food/food.dmi
  strings/hippie_word_replacement.json
  strings/ion_laws.json
  strings/names/death_commando.txt
  strings/traumas.json
Labels: Fix, GitHub, Grammar and Formatting

#12731 Last TOS cleanups
  _maps/map_files/HippieStation/hippiestation.dmm
  code/datums/mutations/speech.dm
  code/game/objects/items/dna_injector.dm
  code/modules/admin/secrets.dm
  code/modules/clothing/shoes/colour.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  hippiestation/code/game/objects/items/clown_items.dm
  hippiestation/code/modules/mob/living/carbon/human/species_types/meeseeks.dm
  hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
  hippiestation/code/modules/uplink/uplink_items.dm
  html/archivedchangelog.html
  strings/hippie_word_replacement.json
  strings/ion_laws.json
  strings/names/ai.txt
Labels: Fix, Grammar and Formatting

#12719 [Ready] adding some (tame) mining circuitry
  hippiestation.dme
  hippiestation/code/modules/integrated_electronics/subtypes/mining.dm
Labels: Feature, Needs Review

#12718 Adds character limit to stripped inputs
  code/datums/diseases/advance/advance.dm
  code/game/gamemodes/sandbox/airlock_maker.dm
  hippiestation/code/game/objects/items/execution_sword.dm
Labels: Fix, Tweak
