Repository HippieStation/HippieStation, pull requests merged in 2020-05, with the labels that each got.

#12722 Minor nanosuit buff
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Balance/Rebalance, Code Improvement, Tweak

#12747 Throw at fix for explosions
  code/modules/mob/living/carbon/alien/special/facehugger.dm
  code/modules/paperwork/paperplane.dm
  code/modules/spells/spell_types/wizard.dm
  hippiestation/code/game/objects/items/singularityhammer.dm
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
  hippiestation/code/modules/gauntlet/revengers.dm
  hippiestation/code/modules/sports/bowling.dm
Labels: Fix

#12745 Probably fixes hippie logo floors
  hippiestation/code/game/turfs/open/floor.dm
  icons/turf/floors.dmi
Labels: Fix

#12741 Curator Buff + Origami Book
  _maps/map_files/HippieStation/hippiestation.dmm
  code/__DEFINES/construction.dm
  code/datums/components/crafting/crafting.dm
  code/game/objects/items/granters.dm
  code/modules/cargo/packs.dm
  hippiestation.dme
  hippiestation/code/datums/components/crafting/learnedrecipes.dm
  hippiestation/code/datums/components/crafting/recipes.dm
  hippiestation/code/game/objects/items/granters.dm
  hippiestation/code/modules/crafts/origami.dm
  hippiestation/icons/mob/inhands/equipment/shields_lefthand.dmi
  hippiestation/icons/mob/inhands/equipment/shields_righthand.dmi
  hippiestation/icons/mob/inhands/weapons/melee_lefthand.dmi
  hippiestation/icons/mob/inhands/weapons/melee_righthand.dmi
  hippiestation/icons/obj/card.dmi
  hippiestation/icons/obj/items_and_weapons.dmi
  hippiestation/icons/obj/library.dmi
  hippiestation/icons/obj/weapons.dmi
  icons/obj/library.dmi
  icons/obj/storage.dmi
Labels: Feature, Tweak

#12706 allows people to eat monkey cubes to commit sudoku
  code/modules/food_and_drinks/food/snacks_meat.dm
Labels: Tweak

#12761 Ports thief gloves and changes stripping system (Old Hippie Port)
  code/__HELPERS/mobs.dm
  code/modules/clothing/gloves/_gloves.dm
  code/modules/clothing/gloves/boxing.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/clothing/gloves.dmi
Labels: Feature, Old Hippiestation Port, Tweak

#12775 Removes some sleep/spawns in replace of timers
  code/__DEFINES/callbacks.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/unsorted.dm
  code/datums/callback.dm
  code/datums/components/_component.dm
  code/datums/martial/plasma_fist.dm
  code/game/machinery/computer/cloning.dm
  code/game/machinery/dance_machine.dm
  code/game/machinery/exp_cloner.dm
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/machinery/telecomms/machines/broadcaster.dm
  code/game/objects/effects/decals/cleanable/misc.dm
  code/game/objects/effects/effect_system/effects_smoke.dm
  code/game/objects/items/devices/taperecorder.dm
  code/game/objects/items/tanks/watertank.dm
  code/game/objects/items/twohanded.dm
  code/game/objects/structures/crates_lockers/crates/bins.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/antagonists/wizard/equipment/artefact.dm
  code/modules/clothing/clothing.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/monkey/combat.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/pai/pai_defense.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/mob/living/simple_animal/friendly/pet.dm
  code/modules/mob/living/simple_animal/guardian/types/lightning.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/paperwork/filingcabinet.dm
  code/modules/paperwork/photocopier.dm
  code/modules/power/lighting.dm
  code/modules/power/singularity/particle_accelerator/particle.dm
  html/changelogs/AutoChangeLog-pr-44895.yml
Labels: Code Improvement, Performance

#12776 fixes some log stuff
  code/__HELPERS/files.dm
  code/game/world.dm
  code/modules/mining/machine_silo.dm
Labels: Code Improvement

#12778 Adds a huge 500 unit beaker and other fixes and additions
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  hippiestation/code/game/objects/effects/effect_system/effects_vapour.dm
  hippiestation/code/modules/reagents/reagent_containers/glass.dm
  hippiestation/code/modules/reagents/reagent_dispenser.dm
  hippiestation/code/modules/vending/wardrobes.dm
Labels: Feature, Fix, Tweak
