Repository HippieStation/HippieStation, pull requests merged in 2020-03, with the labels that each got.

#12614 Adds bluespace mining to hippie upstream
  hippiestation/code/modules/mining/machine_bluespace.dm
Labels: Feature

#12628 Ports BobbahBrown's goonchat xss exploit fix from /tg/.
  code/modules/goonchat/browserassets/js/browserOutput.js
Labels: FUCK, Priority: CRITICAL

#12623 removes stand arrow ruin but actually works
  hippiestation/code/datums/ruins/lavaland.dm
Labels: Removal

#12620 Voice of God: Fart & Scream Edition
  code/modules/surgery/organs/vocal_cords.dm
Labels: Feature

#12597 hey guys I think I fixed a thing
  code/modules/research/nanites/nanite_chamber_computer.dm
  code/modules/research/nanites/nanite_programs/utility.dm
Labels: Fix

#12633 Gulag Gourmet
  hippiestation.dme
  hippiestation/code/modules/food_and_drinks/food/snacks_other.dm
  hippiestation/code/modules/food_and_drinks/food/snacks_vend.dm
  hippiestation/code/modules/vending/sustenance.dm
  hippiestation/icons/obj/food/food.dmi
Labels: Feature, Fix, Sprites

#12639 Protected Roles in Dynamic are now Protected
  config/game_options.txt
Labels: Config Update, Fix

#12637 Maintenance Longface Lair (Fixed version)
  _maps/map_files/HippieStation/hippiestation.dmm
  code/game/area/Space_Station_13_areas.dm
Labels: Feature, Map Edit

#12640 Longface Lair Improvement
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Map Edit

#12644 Firefix
  code/game/objects/obj_defense.dm
  code/modules/mob/living/carbon/carbon.dm
Labels: Fix

#12654 Solar improvements
  code/__DEFINES/components.dm
  code/__DEFINES/power.dm
  code/controllers/subsystem/sun.dm
  code/modules/power/solar.dm
  code/modules/power/tracker.dm
  goon/icons/obj/power.dmi
  hippiestation/code/datums/antagonists/vampire.dm
  html/changelogs/AutoChangeLog-pr-48110.yml
  html/changelogs/AutoChangeLog-pr-49303.yml
  tgui-next/packages/tgui/interfaces/SolarControl.js
  tgui-next/packages/tgui/public/tgui.bundle.js
Labels: Code Improvement, UI

#12656 MC Improvements and less explosion lag
  code/__DEFINES/MC.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/datums/explosion.dm
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/power/solar.dm
Labels: Fix

#12645 Fixed Chaplain rolling Anti-Chap Antagonists
  hippiestation/code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
Labels: Fix

#12648 Clown Office Cap Gun
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Feature, Map Edit

#12662 smart asset cache
  code/modules/asset_cache/asset_cache.dm
  code/modules/asset_cache/asset_cache_client.dm
  code/modules/asset_cache/asset_list.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/asset_cache/validate_assets.html
  code/modules/client/client_procs.dm
  hippiestation.dme
  html/changelogs/AutoChangeLog-pr-49982.yml
  tgstation.dme
Labels: Code Improvement

#12664 Adds clogged vents chaos edition
  hippiestation/code/modules/events/vent_clog.dm
  hippiestation/code/modules/reagents/chemistry/reagents/other_reagents.dm
  hippiestation/code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Feature

#12669 Saves a bit of memory per decal (#48985)
  code/__DEFINES/cleaning.dm
  code/datums/components/decal.dm
  code/game/objects/effects/decals/decal.dm
Labels: Performance

#12661 Lowers rev player requirement from 30 to 18
  code/game/gamemodes/revolution/revolution.dm
Labels: Tweak

#12668 Spurdo Spadre mask usable as a gas mask
  hippiestation/code/modules/clothing/masks/spurdo.dm
Labels: Tweak

#12660 Suicide Vest
  code/datums/action.dm
  code/datums/components/crafting/recipes.dm
  code/game/sound.dm
  code/modules/clothing/suits/armor.dm
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
  sound/items/Alah.ogg
  sound/items/alah_grib.ogg
Labels: Feature, Sound, Sprites

#12665 Magical Item Room (2nd PR)
  _maps/map_files/HippieStation/hippiestation.dmm
  hippiestation/code/modules/clothing/head/helmet.dm
  hippiestation/code/modules/clothing/shoes/shoes.dm
Labels: Map Edit

#12663 Title screen fix
  .gitignore
  code/controllers/subsystem/title.dm
  code/game/turfs/closed.dm
  html/changelogs/AutoChangeLog-pr-45181.yml
Labels: Fix, Test Merge Candidate

#12673 You can now quick swap worn equipment
  hippiestation/code/modules/mob/inventory.dm
Labels: Feature

#12674 Fixes quick swap priority
  code/modules/mob/inventory.dm
  hippiestation/code/modules/mob/inventory.dm
Labels: Fix

#12677 Fix broken dominator spam
  hippiestation/code/game/gamemodes/gangs/dominator.dm
Labels: Fix

#12679 Finally fixes all storage bugs
  hippiestation/code/modules/mob/inventory.dm
Labels: Fix

#12680 Grape Blast Wave Fix
  hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
Labels: Fix

#12682 Defibrillation Station
  _maps/map_files/HippieStation/hippiestation.dmm
Labels: Map Edit
