Repository HippieStation/HippieStation, pull requests merged in 2020-01, with the labels that each got.

#12479 Removes chef CQC from the bar
  hippiestation/code/datums/martial/cqc.dm
Labels: Removal

#12455 Engraved messages no longer give off light
  code/modules/library/soapstone.dm
Labels: Tweak

#12495 Adds extremely trippy sound effects to grape blast [READY]
  hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm
Labels: Needs Review, Tweak

#12496 Makes freon production less cancerous
  hippiestation/code/modules/atmospherics/gasmixtures/reactions.dm
Labels: Tweak

#12508 Makes clean bots clean chempiles
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
Labels: Tweak

#12356 Adds the Vice Officer
  _maps/map_files/HippieStation/hippiestation.dmm
  code/__DEFINES/~hippie_defines/jobs.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/hivemind/hivemind.dm
  code/game/gamemodes/overthrow/overthrow.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/traitor/traitor.dm
  hippiestation.dme
  hippiestation/code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  hippiestation/code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  hippiestation/code/game/objects/effects/landmarks.dm
  hippiestation/code/modules/clothing/shoes/shoes.dm
  hippiestation/code/modules/clothing/suits/misc.dm
  hippiestation/code/modules/clothing/under/jobs/vice_officer.dm
  hippiestation/code/modules/jobs/job_types/vice_officer.dm
  hippiestation/icons/mob/feet.dmi
  hippiestation/icons/mob/suit.dmi
  hippiestation/icons/mob/uniform.dmi
Labels: Feature, Fix, Map Edit

#12389 adds new laugh sounds
  code/modules/mob/living/emote.dm
  hippiestation/sound/misc/laugh03.ogg
  hippiestation/sound/misc/laugh04.ogg
Labels: Feature, Sound, Stale

#12446 Forge "Shotgun" Caliber Addition
  hippiestation/code/game/objects/items/forged_weapons.dm
Labels: Feature

#12454 Adds new abandoned crate loot [READY]
  code/modules/mining/abandoned_crates.dm
  code/modules/reagents/reagent_containers/bottle.dm
Labels: Needs Review

#12460 T-ray scanners can now find wire breaks
  code/__DEFINES/~hippie_defines/tools.dm
  hippiestation.dme
  hippiestation/code/game/objects/items/devices/multitool.dm
  hippiestation/code/game/objects/items/devices/scanners.dm
  hippiestation/code/modules/power/cable.dm
Labels: Feature, Needs Review

#12492 slightly buffs floor tiles
  code/game/objects/items/stacks/tiles/tile_types.dm
Labels: Balance/Rebalance, FUCK

#12499 No more macrobombs for infiltrators
  hippiestation/code/modules/uplink/uplink_items.dm
Labels: Tweak

#12196 Cool see-through portals
  code/modules/lighting/lighting_object.dm
  hippiestation.dme
  hippiestation/code/game/objects/effects/portals.dm
  hippiestation/code/game/turfs/turf.dm
  hippiestation/icons/effects/portal.dmi
Labels: Do Not Merge, Feature

#12513 Improvements to GODMODE status flag
  hippiestation.dme
  hippiestation/code/modules/mob/living/carbon/carbon.dm
  hippiestation/code/modules/mob/living/carbon/carbon_defense.dm
  hippiestation/code/modules/mob/living/carbon/human/human_defense.dm
  hippiestation/code/modules/mob/status_procs.dm
  hippiestation/code/modules/surgery/organs/ears.dm
Labels: Code Improvement

#12521 Removes admin logging from nanosuit
  hippiestation/code/modules/clothing/spacesuits/nanosuit.dm
Labels: Removal

#12519 Adds palpatine lighting effects to Shock Touch
  code/datums/mutations/touch.dm
Labels: Tweak

#12526 Add a config option for replay subsystem.
  config/hippiestation_config.txt
  hippiestation/code/controllers/configuration/entries/hippiestation_config.dm
  hippiestation/code/controllers/subsystem/demo.dm
Labels: Config Update

#12535 Fixes cable bridge recipe
  hippiestation/code/modules/power/cable.dm
Labels: Fix

#12536 Fixes garrote recipe
  hippiestation/code/game/objects/items/garrote.dm
Labels: Fix

#12537 Makes upgraded emitters actually fire on time
  code/modules/power/singularity/emitter.dm
Labels: Code Improvement

#12522 Upgrade pygit2 dependency to v1.0.1
  tools/mapmerge2/requirements.txt
Labels: Tools

#12550 Bullets now cause blood splatter
  hippiestation/code/game/objects/effects/decals/cleanable/humans.dm
  hippiestation/code/modules/mob/living/carbon/human/human_defense.dm
  hippiestation/code/modules/projectiles/projectile/bullets.dm
Labels: Feature, Tweak

#12516 Removing Statechange Restrictions (Dont close it randomly)
  hippiestation/code/_globalvars/lists/typecache.dm
Labels: Toxiccode, ✋ Do Not Merge ✋

#12551 Makes hippiestation logo burn away properly
  hippiestation/code/game/turfs/simulated/floor.dm
Labels: Fix

#12557 Better looking portals
  hippiestation/code/game/objects/effects/portals.dm
  hippiestation/icons/effects/portal.dmi
Labels: Fix, Tweak

#12560 [DNM] Temporairly disable see-through portals
  hippiestation.dme
Labels: Candidate for Testmerge, Do Not Merge, ✋ Do Not Merge ✋

#12565 Fixes 'change color' not working in char setup
  code/modules/client/preferences.dm
Labels: Fix

#12570 Create compile_changelogs.yml
  .github/workflows/compile_changelogs.yml
Labels: GitHub

#12554 The PR that makes medborgs actually useful without needing mid-game research.
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Balance/Rebalance, Removal

#12564 Lowers minimum pop for Badmin Gauntlet to 18
  hippiestation/code/modules/antagonists/wizard/equipment/spellbook.dm
Labels: Tweak
